var modules =
[
    [ "Analog to Digital Converter (ADC)", "group__adc.html", "group__adc" ],
    [ "Camera Interface", "group__cameraif.html", "group__cameraif" ],
    [ "Color LCD", "group__clcd.html", "group__clcd" ],
    [ "CTB", "group__ctb.html", "group__ctb" ],
    [ "Direct Memory Access (DMA)", "group__dma.html", "group__dma" ],
    [ "Ethernet Media Access Controller (EMAC)", "group__emac.html", "group__emac" ],
    [ "Flash Controller  (FLC)", "group__flc.html", "group__flc" ],
    [ "General-Purpose Input/Output (GPIO)", "group__gpio.html", "group__gpio" ],
    [ "HTMR", "group__htmr.html", "group__htmr" ],
    [ "I2C", "group__i2c.html", "group__i2c" ],
    [ "ICC", "group__icc.html", "group__icc" ],
    [ "Low Power (LP)", "group__pwrseq.html", "group__pwrseq" ],
    [ "Assertion Checks for Debugging", "group__mxc__assertions.html", "group__mxc__assertions" ],
    [ "Delay Utility Functions", "group___m_x_c__delay.html", "group___m_x_c__delay" ],
    [ "Error Codes", "group___m_x_c___error___codes.html", "group___m_x_c___error___codes" ],
    [ "Exclusive Access Locks", "group__mxc__lock__utilities.html", "group__mxc__lock__utilities" ],
    [ "System Configuration (MXC_SYS)", "group__mxc__sys.html", "group__mxc__sys" ],
    [ "1-Wire Master (OWM)", "group__owm.html", "group__owm" ],
    [ "Pulse Train Engine", "group__pt.html", "group__pt" ],
    [ "Real Time Clock (RTC)", "group__rtc.html", "group__rtc" ],
    [ "Smart Card (SC)", "group__scn.html", "group__scn" ],
    [ "SDHC", "group__sdhc.html", "group__sdhc" ],
    [ "Semaphore (SEMA)", "group__sema.html", "group__sema" ],
    [ "SFCC", "group__sfcc.html", "group__sfcc" ],
    [ "Secure Keyboard (SKBD)", "group__skbd.html", "group__skbd" ],
    [ "Security Monitor(SMON)", "group__smon.html", "group__smon" ],
    [ "Serial Peripheral Interface (SPI)", "group__spi.html", "group__spi" ],
    [ "SPI External Flash (SPIXF)", "group__spixf.html", "group__spixf" ],
    [ "SPI External RAM (SPIXR)", "group__spixr.html", "group__spixr" ],
    [ "SPIX Cache Controller (SRCC)", "group__srcc.html", "group__srcc" ],
    [ "Timer (TMR)", "group__tmr.html", "group__tmr" ],
    [ "UART", "group__uart.html", "group__uart" ],
    [ "Watchdog Timer (WDT)", "group__wdt.html", "group__wdt" ],
    [ "ADC9_Registers", "group__adc9__registers.html", "group__adc9__registers" ],
    [ "AES_Registers", "group__aes__registers.html", "group__aes__registers" ],
    [ "FCR_Registers", "group__fcr__registers.html", "group__fcr__registers" ],
    [ "GCR_Registers", "group__gcr__registers.html", "group__gcr__registers" ],
    [ "HA_Registers", "group__ha__registers.html", "group__ha__registers" ],
    [ "MCR_Registers", "group__mcr__registers.html", "group__mcr__registers" ],
    [ "PTG_Registers", "group__ptg__registers.html", "group__ptg__registers" ],
    [ "SDMA_Registers", "group__sdma__registers.html", "group__sdma__registers" ],
    [ "SIR_Registers", "group__sir__registers.html", "group__sir__registers" ],
    [ "TRIMSIR_Registers", "group__trimsir__registers.html", "group__trimsir__registers" ],
    [ "TRNG_Registers", "group__trng__registers.html", "group__trng__registers" ],
    [ "USBHS_Registers", "group__usbhs__registers.html", "group__usbhs__registers" ]
];