var modules =
[
    [ "ADC", "group__adc.html", "group__adc" ],
    [ "AES", "group__aes.html", "group__aes" ],
    [ "CAN", "group__can.html", "group__can" ],
    [ "CRC", "group__crc.html", "group__crc" ],
    [ "CTB", "group__ctb.html", "group__ctb" ],
    [ "Direct Memory Access (DMA)", "group__dma.html", "group__dma" ],
    [ "Flash Controller  (FLC)", "group__flc.html", "group__flc" ],
    [ "General-Purpose Input/Output (GPIO)", "group__gpio.html", "group__gpio" ],
    [ "HyperBus (HPB)", "group__hpb.html", "group__hpb" ],
    [ "I2C", "group__i2c.html", "group__i2c" ],
    [ "Inter-Integrated Sound (I2S)", "group__i2s.html", "group__i2s" ],
    [ "ICC", "group__icc.html", "group__icc" ],
    [ "Low Power (LP)", "group__pwrseq.html", "group__pwrseq" ],
    [ "Assertion Checks for Debugging", "group__mxc__assertions.html", "group__mxc__assertions" ],
    [ "Delay Utility Functions", "group___m_x_c__delay.html", "group___m_x_c__delay" ],
    [ "Error Codes", "group___m_x_c___error___codes.html", "group___m_x_c___error___codes" ],
    [ "Exclusive Access Locks", "group__mxc__lock__utilities.html", "group__mxc__lock__utilities" ],
    [ "System Configuration (MXC_SYS)", "group__mxc__sys.html", "group__mxc__sys" ],
    [ "1-Wire Master (OWM)", "group__owm.html", "group__owm" ],
    [ "Pulse Train Engine", "group__pulsetrain.html", "group__pulsetrain" ],
    [ "Real Time Clock (RTC)", "group__rtc.html", "group__rtc" ],
    [ "Semaphore (SEMA)", "group__sema.html", "group__sema" ],
    [ "SPI", "group__spi.html", "group__spi" ],
    [ "SPI External Flash (SPIXF)", "group__spixf.html", "group__spixf" ],
    [ "SPI External RAM (SPIXR)", "group__spixr.html", "group__spixr" ],
    [ "Timer (TMR)", "group__tmr.html", "group__tmr" ],
    [ "TRNG", "group__trng.html", "group__trng" ],
    [ "UART", "group__uart.html", "group__uart" ],
    [ "WDT", "group__wdt.html", "group__wdt" ],
    [ "Wakeup Timer (WUT)", "group__wut.html", "group__wut" ],
    [ "AES_KEY_Registers", "group__aes__key__registers.html", "group__aes__key__registers" ],
    [ "AESKEYS_Registers", "group__aeskeys__registers.html", "group__aeskeys__registers" ],
    [ "EMCC_Registers", "group__emcc__registers.html", "group__emcc__registers" ],
    [ "FCR_Registers", "group__fcr__registers.html", "group__fcr__registers" ],
    [ "GCFR_Registers", "group__gcfr__registers.html", "group__gcfr__registers" ],
    [ "GCR_Registers", "group__gcr__registers.html", "group__gcr__registers" ],
    [ "LPCMP_Registers", "group__lpcmp__registers.html", "group__lpcmp__registers" ],
    [ "LPGCR_Registers", "group__lpgcr__registers.html", "group__lpgcr__registers" ],
    [ "MCR_Registers", "group__mcr__registers.html", "group__mcr__registers" ],
    [ "PT_Registers", "group__pt__registers.html", "group__pt__registers" ],
    [ "PTG_Registers", "group__ptg__registers.html", "group__ptg__registers" ],
    [ "SIR_Registers", "group__sir__registers.html", "group__sir__registers" ],
    [ "SMON_Registers", "group__smon__registers.html", "group__smon__registers" ],
    [ "TRIMSIR_Registers", "group__trimsir__registers.html", "group__trimsir__registers" ],
    [ "USBHS_Registers", "group__usbhs__registers.html", "group__usbhs__registers" ]
];