var searchData=
[
  ['sema_5firq0_0',['SEMA_IRQ0',['../group___s_e_m_a___i_r_q0.html',1,'']]],
  ['sema_5firq1_1',['SEMA_IRQ1',['../group___s_e_m_a___i_r_q1.html',1,'']]],
  ['sema_5fmail0_2',['SEMA_MAIL0',['../group___s_e_m_a___m_a_i_l0.html',1,'']]],
  ['sema_5fmail1_3',['SEMA_MAIL1',['../group___s_e_m_a___m_a_i_l1.html',1,'']]],
  ['sema_5fregisters_4',['SEMA_Registers',['../group__sema__registers.html',1,'']]],
  ['sema_5fsemaphores_5',['SEMA_SEMAPHORES',['../group___s_e_m_a___s_e_m_a_p_h_o_r_e_s.html',1,'']]],
  ['sema_5fstatus_6',['SEMA_STATUS',['../group___s_e_m_a___s_t_a_t_u_s.html',1,'']]],
  ['semaphore_20_28sema_29_7',['Semaphore (SEMA)',['../group__sema.html',1,'']]],
  ['sir_5fbtle_5fldo_5ftrim_8',['SIR_BTLE_LDO_TRIM',['../group___s_i_r___b_t_l_e___l_d_o___t_r_i_m.html',1,'']]],
  ['sir_5ffstat_9',['SIR_FSTAT',['../group___s_i_r___f_s_t_a_t.html',1,'']]],
  ['sir_5fregisters_10',['SIR_Registers',['../group__sir__registers.html',1,'']]],
  ['sir_5fsfstat_11',['SIR_SFSTAT',['../group___s_i_r___s_f_s_t_a_t.html',1,'']]],
  ['sir_5fsiaddr_12',['SIR_SIADDR',['../group___s_i_r___s_i_a_d_d_r.html',1,'']]],
  ['sir_5fsistat_13',['SIR_SISTAT',['../group___s_i_r___s_i_s_t_a_t.html',1,'']]],
  ['smon_5fdlrtc_14',['SMON_DLRTC',['../group___s_m_o_n___d_l_r_t_c.html',1,'']]],
  ['smon_5fextscn_15',['SMON_EXTSCN',['../group___s_m_o_n___e_x_t_s_c_n.html',1,'']]],
  ['smon_5fintscn_16',['SMON_INTSCN',['../group___s_m_o_n___i_n_t_s_c_n.html',1,'']]],
  ['smon_5fmeucfg_17',['SMON_MEUCFG',['../group___s_m_o_n___m_e_u_c_f_g.html',1,'']]],
  ['smon_5fregisters_18',['SMON_Registers',['../group__smon__registers.html',1,'']]],
  ['smon_5fsdbe_19',['SMON_SDBE',['../group___s_m_o_n___s_d_b_e.html',1,'']]],
  ['smon_5fsecalm_20',['SMON_SECALM',['../group___s_m_o_n___s_e_c_a_l_m.html',1,'']]],
  ['smon_5fsecdiag_21',['SMON_SECDIAG',['../group___s_m_o_n___s_e_c_d_i_a_g.html',1,'']]],
  ['smon_5fsecst_22',['SMON_SECST',['../group___s_m_o_n___s_e_c_s_t.html',1,'']]],
  ['spi_23',['SPI',['../group__spi.html',1,'']]],
  ['spi_20external_20flash_20_28spixf_29_24',['SPI External Flash (SPIXF)',['../group__spixf.html',1,'']]],
  ['spi_20external_20flash_20controller_20_28spixfc_29_25',['SPI External Flash Controller (SPIXFC)',['../group__spixfc.html',1,'']]],
  ['spi_20external_20flash_20controller_20fifo_20_28spixfc_5ffifo_29_26',['SPI External Flash Controller FIFO (SPIXFC_FIFO)',['../group__spixfc__fifo.html',1,'']]],
  ['spi_20external_20flash_20master_20_28spixfm_29_27',['SPI External Flash Master (SPIXFM)',['../group__spixfm.html',1,'']]],
  ['spi_20external_20ram_20_28spixr_29_28',['SPI External RAM (SPIXR)',['../group__spixr.html',1,'']]],
  ['spi_5fclkctrl_29',['SPI_CLKCTRL',['../group___s_p_i___c_l_k_c_t_r_l.html',1,'']]],
  ['spi_5fctrl0_30',['SPI_CTRL0',['../group___s_p_i___c_t_r_l0.html',1,'']]],
  ['spi_5fctrl1_31',['SPI_CTRL1',['../group___s_p_i___c_t_r_l1.html',1,'']]],
  ['spi_5fctrl2_32',['SPI_CTRL2',['../group___s_p_i___c_t_r_l2.html',1,'']]],
  ['spi_5fdma_33',['SPI_DMA',['../group___s_p_i___d_m_a.html',1,'']]],
  ['spi_5ffifo16_34',['SPI_FIFO16',['../group___s_p_i___f_i_f_o16.html',1,'']]],
  ['spi_5ffifo32_35',['SPI_FIFO32',['../group___s_p_i___f_i_f_o32.html',1,'']]],
  ['spi_5ffifo8_36',['SPI_FIFO8',['../group___s_p_i___f_i_f_o8.html',1,'']]],
  ['spi_5finten_37',['SPI_INTEN',['../group___s_p_i___i_n_t_e_n.html',1,'']]],
  ['spi_5fintfl_38',['SPI_INTFL',['../group___s_p_i___i_n_t_f_l.html',1,'']]],
  ['spi_5fregisters_39',['SPI_Registers',['../group__spi__registers.html',1,'']]],
  ['spi_5fsstime_40',['SPI_SSTIME',['../group___s_p_i___s_s_t_i_m_e.html',1,'']]],
  ['spi_5fstat_41',['SPI_STAT',['../group___s_p_i___s_t_a_t.html',1,'']]],
  ['spi_5fwken_42',['SPI_WKEN',['../group___s_p_i___w_k_e_n.html',1,'']]],
  ['spi_5fwkfl_43',['SPI_WKFL',['../group___s_p_i___w_k_f_l.html',1,'']]],
  ['spixfc_5fctrl0_44',['SPIXFC_CTRL0',['../group___s_p_i_x_f_c___c_t_r_l0.html',1,'']]],
  ['spixfc_5fctrl1_45',['SPIXFC_CTRL1',['../group___s_p_i_x_f_c___c_t_r_l1.html',1,'']]],
  ['spixfc_5fctrl2_46',['SPIXFC_CTRL2',['../group___s_p_i_x_f_c___c_t_r_l2.html',1,'']]],
  ['spixfc_5fctrl3_47',['SPIXFC_CTRL3',['../group___s_p_i_x_f_c___c_t_r_l3.html',1,'']]],
  ['spixfc_5ffifo_5fregisters_48',['SPIXFC_FIFO_Registers',['../group__spixfc__fifo__registers.html',1,'']]],
  ['spixfc_5finten_49',['SPIXFC_INTEN',['../group___s_p_i_x_f_c___i_n_t_e_n.html',1,'']]],
  ['spixfc_5fintfl_50',['SPIXFC_INTFL',['../group___s_p_i_x_f_c___i_n_t_f_l.html',1,'']]],
  ['spixfc_5fregisters_51',['SPIXFC_Registers',['../group__spixfc__registers.html',1,'']]],
  ['spixfc_5fsimple_5fheader_52',['SPIXFC_SIMPLE_HEADER',['../group___s_p_i_x_f_c___s_i_m_p_l_e___h_e_a_d_e_r.html',1,'']]],
  ['spixfc_5fsspol_53',['SPIXFC_SSPOL',['../group___s_p_i_x_f_c___s_s_p_o_l.html',1,'']]],
  ['spixfm_5fbusidle_54',['SPIXFM_BUSIDLE',['../group___s_p_i_x_f_m___b_u_s_i_d_l_e.html',1,'']]],
  ['spixfm_5fctrl_55',['SPIXFM_CTRL',['../group___s_p_i_x_f_m___c_t_r_l.html',1,'']]],
  ['spixfm_5ffbctrl_56',['SPIXFM_FBCTRL',['../group___s_p_i_x_f_m___f_b_c_t_r_l.html',1,'']]],
  ['spixfm_5ffetchctrl_57',['SPIXFM_FETCHCTRL',['../group___s_p_i_x_f_m___f_e_t_c_h_c_t_r_l.html',1,'']]],
  ['spixfm_5fioctrl_58',['SPIXFM_IOCTRL',['../group___s_p_i_x_f_m___i_o_c_t_r_l.html',1,'']]],
  ['spixfm_5fmemsecctrl_59',['SPIXFM_MEMSECCTRL',['../group___s_p_i_x_f_m___m_e_m_s_e_c_c_t_r_l.html',1,'']]],
  ['spixfm_5fmodectrl_60',['SPIXFM_MODECTRL',['../group___s_p_i_x_f_m___m_o_d_e_c_t_r_l.html',1,'']]],
  ['spixfm_5fmodedata_61',['SPIXFM_MODEDATA',['../group___s_p_i_x_f_m___m_o_d_e_d_a_t_a.html',1,'']]],
  ['spixfm_5fregisters_62',['SPIXFM_Registers',['../group__spixfm__registers.html',1,'']]],
  ['spixr_5fbrgctrl_63',['SPIXR_BRGCTRL',['../group___s_p_i_x_r___b_r_g_c_t_r_l.html',1,'']]],
  ['spixr_5fctrl0_64',['SPIXR_CTRL0',['../group___s_p_i_x_r___c_t_r_l0.html',1,'']]],
  ['spixr_5fctrl1_65',['SPIXR_CTRL1',['../group___s_p_i_x_r___c_t_r_l1.html',1,'']]],
  ['spixr_5fctrl2_66',['SPIXR_CTRL2',['../group___s_p_i_x_r___c_t_r_l2.html',1,'']]],
  ['spixr_5fctrl3_67',['SPIXR_CTRL3',['../group___s_p_i_x_r___c_t_r_l3.html',1,'']]],
  ['spixr_5fdata16_68',['SPIXR_DATA16',['../group___s_p_i_x_r___d_a_t_a16.html',1,'']]],
  ['spixr_5fdata32_69',['SPIXR_DATA32',['../group___s_p_i_x_r___d_a_t_a32.html',1,'']]],
  ['spixr_5fdata8_70',['SPIXR_DATA8',['../group___s_p_i_x_r___d_a_t_a8.html',1,'']]],
  ['spixr_5fdma_71',['SPIXR_DMA',['../group___s_p_i_x_r___d_m_a.html',1,'']]],
  ['spixr_5finten_72',['SPIXR_INTEN',['../group___s_p_i_x_r___i_n_t_e_n.html',1,'']]],
  ['spixr_5fintfl_73',['SPIXR_INTFL',['../group___s_p_i_x_r___i_n_t_f_l.html',1,'']]],
  ['spixr_5fregisters_74',['SPIXR_Registers',['../group__spixr__registers.html',1,'']]],
  ['spixr_5fstat_75',['SPIXR_STAT',['../group___s_p_i_x_r___s_t_a_t.html',1,'']]],
  ['spixr_5fwken_76',['SPIXR_WKEN',['../group___s_p_i_x_r___w_k_e_n.html',1,'']]],
  ['spixr_5fwkfl_77',['SPIXR_WKFL',['../group___s_p_i_x_r___w_k_f_l.html',1,'']]],
  ['spixr_5fxmemctrl_78',['SPIXR_XMEMCTRL',['../group___s_p_i_x_r___x_m_e_m_c_t_r_l.html',1,'']]],
  ['system_20configuration_20_28mxc_5fsys_29_79',['System Configuration (MXC_SYS)',['../group__mxc__sys.html',1,'']]]
];
