/*******************************************************************************
* Copyright (C) 2019-2023 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// dotprod_comb_112
// This file was @generated by ai8xize.py --test-dir sdk/Examples/MAX78002/CNN --prefix dotprod_comb_112 --checkpoint-file trained/dot_emb_112_checkpoint-q.pth.tar --config-file networks/dotprod.yaml --overwrite --start-layer 73 --weight-start 2000 --device MAX78002 --timer 0 --display-checkpoint --verbose

// DO NOT EDIT - regenerate this file instead!

// Configuring 74 layers
// Input data: HWC
// Layer 73: 64x1x1, no pooling, linear, no activation, 1024x1x1 output

#include <assert.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "cnn_1.h"
#include "cnn_3.h"
#include "weights_3.h"
#include "MAXCAM_Debug.h"
#include "record.h"

#define S_MODULE_NAME "cnn_3"

void CNN_3_ISR(void)
{
    // Acknowledge interrupt to all quadrants
    *((volatile uint32_t *)0x51000000) &= ~((1 << 12) | 1);
    *((volatile uint32_t *)0x52000000) &= ~((1 << 12) | 1);
    *((volatile uint32_t *)0x53000000) &= ~((1 << 12) | 1);
    *((volatile uint32_t *)0x54000000) &= ~((1 << 12) | 1);

    CNN_COMPLETE; // Signal that processing is complete
#ifdef CNN_INFERENCE_TIMER
    cnn_time = MXC_TMR_SW_Stop(CNN_INFERENCE_TIMER);
#else
    cnn_time = 1;
#endif
}

static const uint32_t kernels_3[] = KERNELS_3;

static uint8_t mexpress_byte(const uint32_t **addr, uint32_t *val, int *avail)
{
    if (*avail == 0) {
        *val = *(*addr)++;
        *avail = 4;
    }

    return (*val >> (--(*avail) * 8)) & 0xff;
}

int cnn_verify_weights(void)
{
    uint32_t len, data, val;
    volatile uint32_t *addr, *ptr;
    const uint32_t *compare = kernels_3;
    int av;

    while ((addr = (volatile uint32_t *)*compare++) != 0) {
        len = (*compare++ * 4) / 9;
        ptr =
            (volatile uint32_t *)(((uint32_t)addr & 0xffffe000) | (((uint32_t)addr & 0x1fff) << 2));
        av = 0;
        val = 0;

        while (len-- > 0) {
            data = mexpress_byte(&compare, &val, &av);
            printf("Addr[0]: %08x, read: %08x, expected: %08x\n", ptr, *(ptr), data);
            ptr++;
            /*if (*ptr++ != data) {
        printf("Addr[0]: %08x, read: %08x, expected: %08x\n", ptr-1, *(ptr-1), data);
        return CNN_FAIL;
      }*/
            data = mexpress_byte(&compare, &val, &av) << 24 |
                   mexpress_byte(&compare, &val, &av) << 16 |
                   mexpress_byte(&compare, &val, &av) << 8 | mexpress_byte(&compare, &val, &av);
            printf("Addr[1]: %08x, read: %08x, expected: %08x\n", ptr, *(ptr), data);
            ptr++;
            /*if (*ptr++ != data) {
        printf("Addr[1]: %08x, read: %08x, expected: %08x\n", ptr-1, *(ptr-1), data);
        return CNN_FAIL;
      }*/
            data = mexpress_byte(&compare, &val, &av) << 24 |
                   mexpress_byte(&compare, &val, &av) << 16 |
                   mexpress_byte(&compare, &val, &av) << 8 | mexpress_byte(&compare, &val, &av);
            printf("Addr[2]: %08x, read: %08x, expected: %08x\n", ptr, *(ptr), data);
            ptr++;
            /*if (*ptr++ != data) {
        printf("Addr[2]: %08x, read: %08x, expected: %08x\n", ptr-1, *(ptr-1), data);
        return CNN_FAIL;
      }*/
            printf("Addr[3]: %08x, read: %08x, expected: 00000000\n", ptr, *(ptr));
            ptr++;
            /*if (*ptr++ != 0) {
        printf("Addr[3]: %08x, read: %08x, expected: 00000000\n", ptr-1, *(ptr-1));
        return CNN_FAIL;
      }*/
        }
    }

    return CNN_OK;
}

int cnn_3_load_weights(void)
{
    uint32_t len;
    volatile uint32_t *addr;
    const uint32_t *ptr = kernels_3;

    while ((addr = (volatile uint32_t *)*ptr++) != 0) {
        //PR_DEBUG("Loading %d bytes at 0x%x\n", len = *ptr, addr);
        *((volatile uint8_t *)((uint32_t)addr | 1)) = 0x01; // Set address
        len = *ptr++;
        while (len-- > 0) {
            //PR_DEBUG("Writing 0x%x to 0x%x\n", *ptr, addr);
            *addr++ = *ptr++;
        }
    }
    return CNN_OK;
}

int cnn_3_load_bias(void)
{
    // Not used in this network
    return CNN_OK;
}

int cnn_3_init(void)
{
    *((volatile uint32_t *)0x51000000) = 0x00000008; // Enable clocks
    *((volatile uint32_t *)0x52000000) = 0x00000008; // Enable clocks
    *((volatile uint32_t *)0x53000000) = 0x00000008; // Enable clocks
    *((volatile uint32_t *)0x54000000) = 0x00000008; // Enable clocks
    *((volatile uint32_t *)0x50001000) = 0x00000000; // AON control
    *((volatile uint32_t *)0x51000004) = 0x0000040e; // SRAM control
    *((volatile uint32_t *)0x52000004) = 0x0000040e; // SRAM control
    *((volatile uint32_t *)0x53000004) = 0x0000040e; // SRAM control
    *((volatile uint32_t *)0x54000004) = 0x0000040e; // SRAM control
    *((volatile uint32_t *)0x5100000c) = 0x00001880; // Clear registers
    *((volatile uint32_t *)0x5200000c) = 0x00001880; // Clear registers
    *((volatile uint32_t *)0x5300000c) = 0x00001880; // Clear registers
    *((volatile uint32_t *)0x5400000c) = 0x00001880; // Clear registers
    while ((*((volatile uint32_t *)0x5100000c) & 0x2000000) != 0x2000000)
        ; // Wait for clear
    while ((*((volatile uint32_t *)0x5200000c) & 0x2000000) != 0x2000000)
        ; // Wait for clear
    while ((*((volatile uint32_t *)0x5300000c) & 0x2000000) != 0x2000000)
        ; // Wait for clear
    while ((*((volatile uint32_t *)0x5400000c) & 0x2000000) != 0x2000000)
        ; // Wait for clear
    *((volatile uint32_t *)0x5100000c) = 0x00000000; // Reset BIST
    *((volatile uint32_t *)0x5200000c) = 0x00000000; // Reset BIST
    *((volatile uint32_t *)0x5300000c) = 0x00000000; // Reset BIST
    *((volatile uint32_t *)0x5400000c) = 0x00000000; // Reset BIST

    *((volatile uint32_t *)0x51000000) = 0x00100008; // Stop SM
    *((volatile uint32_t *)0x51000008) = 0x00004949; // Layer count
    *((volatile uint32_t *)0x52000000) = 0x00100008; // Stop SM
    *((volatile uint32_t *)0x52000008) = 0x00004949; // Layer count
    *((volatile uint32_t *)0x53000000) = 0x00100008; // Stop SM
    *((volatile uint32_t *)0x53000008) = 0x00004949; // Layer count
    *((volatile uint32_t *)0x54000000) = 0x00100008; // Stop SM
    *((volatile uint32_t *)0x54000008) = 0x00004949; // Layer count

    return CNN_OK;
}

int cnn_3_configure(void)
{
    // Layer 73 quadrant 0
    *((volatile uint32_t *)0x51104904) = 0x00010000; // Rows
    *((volatile uint32_t *)0x51104908) = 0x00010000; // Columns
    *((volatile uint32_t *)0x51104918) = 0x00000010; // Stride
    *((volatile uint32_t *)0x5110491c) = 0x00001000; // SRAM write ptr
    *((volatile uint32_t *)0x51104920) = 0x00000001; // Write ptr time slot offs
    *((volatile uint32_t *)0x51104924) = 0x00008000; // Write ptr mask offs
    *((volatile uint32_t *)0x51104928) = 0x00000001; // Write ptr multi-pass channel offs
    *((volatile uint32_t *)0x51104930) = 0x0000e920; // Layer control
    *((volatile uint32_t *)0x51104934) = 0x001f80f0; // Layer control 2
    *((volatile uint32_t *)0x51104938) = 0x00025278; // Mask count
    *((volatile uint32_t *)0x5110493c) = 0x00023280; // Mask offset
    *((volatile uint32_t *)0x51104940) = 0x000003ff; // Output channel count
    *((volatile uint32_t *)0x5110490c) = 0x00000100; // 1D
    *((volatile uint32_t *)0x5110494c) = 0x00022000; // Post processing register
    *((volatile uint32_t *)0x51104948) = 0xffffffff; // Mask and processor enables

    // Layer 73 quadrant 1
    *((volatile uint32_t *)0x52104904) = 0x00010000; // Rows
    *((volatile uint32_t *)0x52104908) = 0x00010000; // Columns
    *((volatile uint32_t *)0x52104918) = 0x00000010; // Stride
    *((volatile uint32_t *)0x5210491c) = 0x00001000; // SRAM write ptr
    *((volatile uint32_t *)0x52104920) = 0x00000001; // Write ptr time slot offs
    *((volatile uint32_t *)0x52104924) = 0x00008000; // Write ptr mask offs
    *((volatile uint32_t *)0x52104928) = 0x00000001; // Write ptr multi-pass channel offs
    *((volatile uint32_t *)0x52104930) = 0x00000920; // Layer control
    *((volatile uint32_t *)0x52104934) = 0x001f80f0; // Layer control 2
    *((volatile uint32_t *)0x52104938) = 0x00025278; // Mask count
    *((volatile uint32_t *)0x5210493c) = 0x00023280; // Mask offset
    *((volatile uint32_t *)0x52104940) = 0x000003ff; // Output channel count
    *((volatile uint32_t *)0x5210490c) = 0x00000100; // 1D
    *((volatile uint32_t *)0x5210494c) = 0x00022000; // Post processing register
    *((volatile uint32_t *)0x52104948) = 0xffffffff; // Mask and processor enables

    // Layer 73 quadrant 2
    *((volatile uint32_t *)0x53104904) = 0x00010000; // Rows
    *((volatile uint32_t *)0x53104908) = 0x00010000; // Columns
    *((volatile uint32_t *)0x53104918) = 0x00000010; // Stride
    *((volatile uint32_t *)0x5310491c) = 0x00001000; // SRAM write ptr
    *((volatile uint32_t *)0x53104920) = 0x00000001; // Write ptr time slot offs
    *((volatile uint32_t *)0x53104924) = 0x00008000; // Write ptr mask offs
    *((volatile uint32_t *)0x53104928) = 0x00000001; // Write ptr multi-pass channel offs
    *((volatile uint32_t *)0x53104930) = 0x00000920; // Layer control
    *((volatile uint32_t *)0x53104934) = 0x001f80f0; // Layer control 2
    *((volatile uint32_t *)0x53104938) = 0x00025278; // Mask count
    *((volatile uint32_t *)0x5310493c) = 0x00023280; // Mask offset
    *((volatile uint32_t *)0x53104940) = 0x000003ff; // Output channel count
    *((volatile uint32_t *)0x5310490c) = 0x00000100; // 1D
    *((volatile uint32_t *)0x5310494c) = 0x00022000; // Post processing register
    *((volatile uint32_t *)0x53104948) = 0xffffffff; // Mask and processor enables

    // Layer 73 quadrant 3
    *((volatile uint32_t *)0x54104904) = 0x00010000; // Rows
    *((volatile uint32_t *)0x54104908) = 0x00010000; // Columns
    *((volatile uint32_t *)0x54104918) = 0x00000010; // Stride
    *((volatile uint32_t *)0x5410491c) = 0x00001000; // SRAM write ptr
    *((volatile uint32_t *)0x54104920) = 0x00000001; // Write ptr time slot offs
    *((volatile uint32_t *)0x54104924) = 0x00008000; // Write ptr mask offs
    *((volatile uint32_t *)0x54104928) = 0x00000001; // Write ptr multi-pass channel offs
    *((volatile uint32_t *)0x54104930) = 0x00000920; // Layer control
    *((volatile uint32_t *)0x54104934) = 0x001f80f0; // Layer control 2
    *((volatile uint32_t *)0x54104938) = 0x00025278; // Mask count
    *((volatile uint32_t *)0x5410493c) = 0x00023280; // Mask offset
    *((volatile uint32_t *)0x54104940) = 0x000003ff; // Output channel count
    *((volatile uint32_t *)0x5410490c) = 0x00000100; // 1D
    *((volatile uint32_t *)0x5410494c) = 0x00022000; // Post processing register
    *((volatile uint32_t *)0x54104948) = 0xffffffff; // Mask and processor enables

    return CNN_OK;
}

int cnn_3_start(void)
{
    cnn_time = 0;

    *((volatile uint32_t *)0x51000000) = 0x00100808; // Enable quadrant 0
    *((volatile uint32_t *)0x52000000) = 0x00100809; // Enable quadrant 1
    *((volatile uint32_t *)0x53000000) = 0x00100809; // Enable quadrant 2
    *((volatile uint32_t *)0x54000000) = 0x00100809; // Enable quadrant 3

#ifdef CNN_INFERENCE_TIMER
    MXC_TMR_SW_Start(CNN_INFERENCE_TIMER);
#endif

    CNN_START; // Allow capture of processing time
    *((volatile uint32_t *)0x51000000) = 0x00100009; // Master enable quadrant 0

    return CNN_OK;
}

int cnn_3_unload(uint32_t *out_buf32)
{
    uint8_t *out_buf = (uint8_t *)out_buf32;
    uint32_t val;
    volatile uint32_t *addr;
    int i;

    // Custom unload for this network, layer 73: 8-bit data, shape: (1024, 1, 1)
    addr = (volatile uint32_t *)0x51804000;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x52804000;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x53804000;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x54804000;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x51804004;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x52804004;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x53804004;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x54804004;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x51804008;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x52804008;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x53804008;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x54804008;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x5180400c;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x5280400c;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x5380400c;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x5480400c;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x51804010;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x52804010;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x53804010;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x54804010;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x51804014;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x52804014;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x53804014;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x54804014;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x51804018;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x52804018;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x53804018;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x54804018;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x5180401c;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x5280401c;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x5380401c;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x5480401c;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x51804020;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x52804020;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x53804020;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x54804020;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x51804024;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x52804024;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x53804024;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x54804024;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x51804028;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x52804028;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x53804028;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x54804028;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x5180402c;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x5280402c;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x5380402c;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x5480402c;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x51804030;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x52804030;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x53804030;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x54804030;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x51804034;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x52804034;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x53804034;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x54804034;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x51804038;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x52804038;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x53804038;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x54804038;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x5180403c;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x5280403c;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x5380403c;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }
    addr = (volatile uint32_t *)0x5480403c;
    for (i = 0; i < 4; i++) {
        val = *addr;
        addr += 0x8000;
        *out_buf++ = val & 0xff;
        *out_buf++ = (val >> 8) & 0xff;
        *out_buf++ = (val >> 16) & 0xff;
        *out_buf++ = (val >> 24) & 0xff;
    }

    return CNN_OK;
}

int cnn_3_enable(uint32_t clock_source, uint32_t clock_divider)
{
    // Reset all domains, restore power to CNN
    MXC_GCFR->reg3 = 0xf; // Reset
    MXC_GCFR->reg1 = 0xf; // Mask memory
    MXC_GCFR->reg0 = 0xf; // Power
    MXC_Delay(MSEC(10)); // Wait for load switches
    MXC_GCFR->reg2 = 0x0; // Iso
    MXC_GCFR->reg3 = 0x0; // Reset

    if (clock_source == MXC_S_GCR_PCLKDIV_CNNCLKSEL_IPLL)
        while ((MXC_GCR->ipll_ctrl & MXC_F_GCR_IPLL_CTRL_RDY) != MXC_F_GCR_IPLL_CTRL_RDY)
            ; // Wait for PLL

    MXC_GCR->pclkdiv =
        (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL)) |
        clock_divider | clock_source;
    MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN); // Enable CNN clock

    MXC_NVIC_SetVector(CNN_IRQn, CNN_3_ISR); // Set CNN complete vector

    return CNN_OK;
}
