var group__simo__registers =
[
    [ "Register Offsets", "group___s_i_m_o___register___offsets.html", "group___s_i_m_o___register___offsets" ],
    [ "SIMO_VREGO_A", "group___s_i_m_o___v_r_e_g_o___a.html", "group___s_i_m_o___v_r_e_g_o___a" ],
    [ "SIMO_VREGO_B", "group___s_i_m_o___v_r_e_g_o___b.html", "group___s_i_m_o___v_r_e_g_o___b" ],
    [ "SIMO_VREGO_C", "group___s_i_m_o___v_r_e_g_o___c.html", "group___s_i_m_o___v_r_e_g_o___c" ],
    [ "SIMO_VREGO_D", "group___s_i_m_o___v_r_e_g_o___d.html", "group___s_i_m_o___v_r_e_g_o___d" ],
    [ "SIMO_IPKA", "group___s_i_m_o___i_p_k_a.html", "group___s_i_m_o___i_p_k_a" ],
    [ "SIMO_IPKB", "group___s_i_m_o___i_p_k_b.html", "group___s_i_m_o___i_p_k_b" ],
    [ "SIMO_MAXTON", "group___s_i_m_o___m_a_x_t_o_n.html", "group___s_i_m_o___m_a_x_t_o_n" ],
    [ "SIMO_ILOAD_A", "group___s_i_m_o___i_l_o_a_d___a.html", "group___s_i_m_o___i_l_o_a_d___a" ],
    [ "SIMO_ILOAD_B", "group___s_i_m_o___i_l_o_a_d___b.html", "group___s_i_m_o___i_l_o_a_d___b" ],
    [ "SIMO_ILOAD_C", "group___s_i_m_o___i_l_o_a_d___c.html", "group___s_i_m_o___i_l_o_a_d___c" ],
    [ "SIMO_ILOAD_D", "group___s_i_m_o___i_l_o_a_d___d.html", "group___s_i_m_o___i_l_o_a_d___d" ],
    [ "SIMO_BUCK_ALERT_THR_A", "group___s_i_m_o___b_u_c_k___a_l_e_r_t___t_h_r___a.html", "group___s_i_m_o___b_u_c_k___a_l_e_r_t___t_h_r___a" ],
    [ "SIMO_BUCK_ALERT_THR_B", "group___s_i_m_o___b_u_c_k___a_l_e_r_t___t_h_r___b.html", "group___s_i_m_o___b_u_c_k___a_l_e_r_t___t_h_r___b" ],
    [ "SIMO_BUCK_ALERT_THR_C", "group___s_i_m_o___b_u_c_k___a_l_e_r_t___t_h_r___c.html", "group___s_i_m_o___b_u_c_k___a_l_e_r_t___t_h_r___c" ],
    [ "SIMO_BUCK_ALERT_THR_D", "group___s_i_m_o___b_u_c_k___a_l_e_r_t___t_h_r___d.html", "group___s_i_m_o___b_u_c_k___a_l_e_r_t___t_h_r___d" ],
    [ "SIMO_BUCK_OUT_READY", "group___s_i_m_o___b_u_c_k___o_u_t___r_e_a_d_y.html", "group___s_i_m_o___b_u_c_k___o_u_t___r_e_a_d_y" ],
    [ "SIMO_ZERO_CROSS_CAL_A", "group___s_i_m_o___z_e_r_o___c_r_o_s_s___c_a_l___a.html", "group___s_i_m_o___z_e_r_o___c_r_o_s_s___c_a_l___a" ],
    [ "SIMO_ZERO_CROSS_CAL_B", "group___s_i_m_o___z_e_r_o___c_r_o_s_s___c_a_l___b.html", "group___s_i_m_o___z_e_r_o___c_r_o_s_s___c_a_l___b" ],
    [ "SIMO_ZERO_CROSS_CAL_C", "group___s_i_m_o___z_e_r_o___c_r_o_s_s___c_a_l___c.html", "group___s_i_m_o___z_e_r_o___c_r_o_s_s___c_a_l___c" ],
    [ "SIMO_ZERO_CROSS_CAL_D", "group___s_i_m_o___z_e_r_o___c_r_o_s_s___c_a_l___d.html", "group___s_i_m_o___z_e_r_o___c_r_o_s_s___c_a_l___d" ],
    [ "mxc_simo_regs_t", "group__simo__registers.html#structmxc__simo__regs__t", [
      [ "buck_alert_thr_a", "group__simo__registers.html#a88fd56309cae950a98d14097de7769a6", null ],
      [ "buck_alert_thr_b", "group__simo__registers.html#a275e507f45261a18723011f3864a7b61", null ],
      [ "buck_alert_thr_c", "group__simo__registers.html#adecd6af58e4101c4087d706fe9e5db84", null ],
      [ "buck_alert_thr_d", "group__simo__registers.html#a3b5cf0009bac670b69e1426a7790fc18", null ],
      [ "buck_out_ready", "group__simo__registers.html#a7a6ddec502cfe337701fb5455675cd11", null ],
      [ "iload_a", "group__simo__registers.html#a51f401ee9d89bfaaa439a889bd337c62", null ],
      [ "iload_b", "group__simo__registers.html#a31d5870b6d5daae6d846432552444f3a", null ],
      [ "iload_c", "group__simo__registers.html#ac6cb7983389729be948c2018123752a2", null ],
      [ "iload_d", "group__simo__registers.html#af2abc3335b933d169fb8519faeeef26b", null ],
      [ "ipka", "group__simo__registers.html#ac91088c3ff031a2c433e1f9bc6d29b00", null ],
      [ "ipkb", "group__simo__registers.html#a495c2bb1e616fe11da1ab39e528bb1d4", null ],
      [ "maxton", "group__simo__registers.html#a4ed97232e1922e09665d19cfe90cad39", null ],
      [ "vrego_a", "group__simo__registers.html#a4f412b1af9b414610392fe33c2277932", null ],
      [ "vrego_b", "group__simo__registers.html#a80dc4426800f8656aa8883cf6cfd6155", null ],
      [ "vrego_c", "group__simo__registers.html#a7ebc6ecc925b7a7011498c020077948d", null ],
      [ "vrego_d", "group__simo__registers.html#a0b4864de4289ade5074a01dd18388ede", null ],
      [ "zero_cross_cal_a", "group__simo__registers.html#a4cbd4d9e653ff45b2097d7900b199583", null ],
      [ "zero_cross_cal_b", "group__simo__registers.html#a6f74277ccb5588c853ad72aa19e9d735", null ],
      [ "zero_cross_cal_c", "group__simo__registers.html#a5b6409d1545b8926433ab148973a6646", null ],
      [ "zero_cross_cal_d", "group__simo__registers.html#aaa2da3e8fece40feb0c73c31d84665a3", null ]
    ] ]
];