var annotated_dup =
[
    [ "mxc_aes_key_regs_t", "group__aes__key__registers.html#structmxc__aes__key__regs__t", "group__aes__key__registers_structmxc__aes__key__regs__t" ],
    [ "mxc_aes_regs_t", "group__aes__registers.html#structmxc__aes__regs__t", "group__aes__registers_structmxc__aes__regs__t" ],
    [ "mxc_aes_req_t", "group__aes.html#structmxc__aes__req__t", "group__aes_structmxc__aes__req__t" ],
    [ "mxc_crc_regs_t", "group__crc__registers.html#structmxc__crc__regs__t", "group__crc__registers_structmxc__crc__regs__t" ],
    [ "mxc_crc_req_t", "group__crc.html#structmxc__crc__req__t", "group__crc_structmxc__crc__req__t" ],
    [ "mxc_dma_adv_config_t", "group__dma.html#structmxc__dma__adv__config__t", "group__dma_structmxc__dma__adv__config__t" ],
    [ "mxc_dma_ch_regs_t", "group__dma__registers.html#structmxc__dma__ch__regs__t", "group__dma__registers_structmxc__dma__ch__regs__t" ],
    [ "mxc_dma_config_t", "group__dma.html#structmxc__dma__config__t", "group__dma_structmxc__dma__config__t" ],
    [ "mxc_dma_srcdst_t", "group__dma.html#structmxc__dma__srcdst__t", "group__dma_structmxc__dma__srcdst__t" ],
    [ "mxc_ecc_regs_t", "group__ecc__registers.html#structmxc__ecc__regs__t", "group__ecc__registers_structmxc__ecc__regs__t" ],
    [ "mxc_fcr_regs_t", "group__fcr__registers.html#structmxc__fcr__regs__t", "group__fcr__registers_structmxc__fcr__regs__t" ],
    [ "mxc_flc_regs_t", "group__flc__registers.html#structmxc__flc__regs__t", "group__flc__registers_structmxc__flc__regs__t" ],
    [ "mxc_gcr_regs_t", "group__gcr__registers.html#structmxc__gcr__regs__t", "group__gcr__registers_structmxc__gcr__regs__t" ],
    [ "mxc_gpio_cfg_t", "group__gpio.html#structmxc__gpio__cfg__t", "group__gpio_structmxc__gpio__cfg__t" ],
    [ "mxc_gpio_regs_t", "group__gpio__registers.html#structmxc__gpio__regs__t", "group__gpio__registers_structmxc__gpio__regs__t" ],
    [ "mxc_i2c_regs_t", "group__i2c__registers.html#structmxc__i2c__regs__t", "group__i2c__registers_structmxc__i2c__regs__t" ],
    [ "mxc_i2c_req_t", "group__i2c.html#struct__i2c__req__t", "group__i2c_struct__i2c__req__t" ],
    [ "mxc_i2s_regs_t", "group__i2s__registers.html#structmxc__i2s__regs__t", "group__i2s__registers_structmxc__i2s__regs__t" ],
    [ "mxc_i2s_req_t", "group__i2s.html#structmxc__i2s__req__t", null ],
    [ "mxc_icc_regs_t", "group__icc__registers.html#structmxc__icc__regs__t", "group__icc__registers_structmxc__icc__regs__t" ],
    [ "mxc_mcr_regs_t", "group__mcr__registers.html#structmxc__mcr__regs__t", "group__mcr__registers_structmxc__mcr__regs__t" ],
    [ "mxc_pwrseq_regs_t", "group__pwrseq__registers.html#structmxc__pwrseq__regs__t", "group__pwrseq__registers_structmxc__pwrseq__regs__t" ],
    [ "mxc_rtc_regs_t", "group__rtc__registers.html#structmxc__rtc__regs__t", "group__rtc__registers_structmxc__rtc__regs__t" ],
    [ "mxc_sir_regs_t", "group__sir__registers.html#structmxc__sir__regs__t", "group__sir__registers_structmxc__sir__regs__t" ],
    [ "mxc_spi_regs_t", "group__spi__registers.html#structmxc__spi__regs__t", "group__spi__registers_structmxc__spi__regs__t" ],
    [ "mxc_spi_req_t", "group__spi.html#struct__mxc__spi__req__t", "group__spi_struct__mxc__spi__req__t" ],
    [ "mxc_tmr_cfg_t", "group__tmr.html#structmxc__tmr__cfg__t", "group__tmr_structmxc__tmr__cfg__t" ],
    [ "mxc_tmr_regs_t", "group__tmr__registers.html#structmxc__tmr__regs__t", "group__tmr__registers_structmxc__tmr__regs__t" ],
    [ "mxc_trng_regs_t", "group__trng__registers.html#structmxc__trng__regs__t", "group__trng__registers_structmxc__trng__regs__t" ],
    [ "mxc_uart_regs_t", "group__uart__registers.html#structmxc__uart__regs__t", "group__uart__registers_structmxc__uart__regs__t" ],
    [ "mxc_uart_req_t", "group__uart.html#struct__mxc__uart__req__t", "group__uart_struct__mxc__uart__req__t" ],
    [ "mxc_wdt_cfg_t", "group__wdt.html#structmxc__wdt__cfg__t", "group__wdt_structmxc__wdt__cfg__t" ],
    [ "mxc_wdt_regs_t", "group__wdt__registers.html#structmxc__wdt__regs__t", "group__wdt__registers_structmxc__wdt__regs__t" ]
];