var annotated_dup =
[
    [ "msr_decoded_track_t", "structmsr__decoded__track__t.html", "structmsr__decoded__track__t" ],
    [ "msr_sample_t", "unionmsr__sample__t.html", null ],
    [ "msr_samples_t", "structmsr__samples__t.html", null ],
    [ "mxc_dma_adv_config_t", "group__dma.html#structmxc__dma__adv__config__t", "group__dma_structmxc__dma__adv__config__t" ],
    [ "mxc_dma_ch_regs_t", "group__dma__registers.html#structmxc__dma__ch__regs__t", "group__dma__registers_structmxc__dma__ch__regs__t" ],
    [ "mxc_dma_config_t", "group__dma.html#structmxc__dma__config__t", "group__dma_structmxc__dma__config__t" ],
    [ "mxc_dma_srcdst_t", "group__dma.html#structmxc__dma__srcdst__t", "group__dma_structmxc__dma__srcdst__t" ],
    [ "mxc_fcr_regs_t", "group__fcr__registers.html#structmxc__fcr__regs__t", "group__fcr__registers_structmxc__fcr__regs__t" ],
    [ "mxc_flc_regs_t", "group__flc__registers.html#structmxc__flc__regs__t", "group__flc__registers_structmxc__flc__regs__t" ],
    [ "mxc_gcr_regs_t", "group__gcr__registers.html#structmxc__gcr__regs__t", "group__gcr__registers_structmxc__gcr__regs__t" ],
    [ "mxc_gpio_cfg_t", "group__gpio.html#structmxc__gpio__cfg__t", "group__gpio_structmxc__gpio__cfg__t" ],
    [ "mxc_gpio_regs_t", "group__gpio__registers.html#structmxc__gpio__regs__t", "group__gpio__registers_structmxc__gpio__regs__t" ],
    [ "mxc_i2c_regs_t", "group__i2c__registers.html#structmxc__i2c__regs__t", "group__i2c__registers_structmxc__i2c__regs__t" ],
    [ "mxc_i2c_req_t", "group__i2c.html#struct__i2c__req__t", "group__i2c_struct__i2c__req__t" ],
    [ "mxc_i2s_config_t", "group__i2s.html#structmxc__i2s__config__t", null ],
    [ "mxc_icc_regs_t", "group__icc__registers.html#structmxc__icc__regs__t", "group__icc__registers_structmxc__icc__regs__t" ],
    [ "mxc_pwrseq_regs_t", "group__pwrseq__registers.html#structmxc__pwrseq__regs__t", "group__pwrseq__registers_structmxc__pwrseq__regs__t" ],
    [ "mxc_rtc_regs_t", "group__rtc__registers.html#structmxc__rtc__regs__t", "group__rtc__registers_structmxc__rtc__regs__t" ],
    [ "mxc_sir_regs_t", "group__sir__registers.html#structmxc__sir__regs__t", "group__sir__registers_structmxc__sir__regs__t" ],
    [ "mxc_spi_regs_t", "group__spi__registers.html#structmxc__spi__regs__t", "group__spi__registers_structmxc__spi__regs__t" ],
    [ "mxc_spi_req_t", "group__spi.html#struct__mxc__spi__req__t", "group__spi_struct__mxc__spi__req__t" ],
    [ "mxc_spimss_regs_t", "group__spimss__registers.html#structmxc__spimss__regs__t", "group__spimss__registers_structmxc__spimss__regs__t" ],
    [ "mxc_spimss_req_t", "group__spimss.html#structmxc__spimss__req", "group__spimss_structmxc__spimss__req" ],
    [ "mxc_tmr_cfg_t", "group__tmr.html#structmxc__tmr__cfg__t", "group__tmr_structmxc__tmr__cfg__t" ],
    [ "mxc_tmr_regs_t", "group__tmr__registers.html#structmxc__tmr__regs__t", "group__tmr__registers_structmxc__tmr__regs__t" ],
    [ "mxc_uart_regs_t", "group__uart__registers.html#structmxc__uart__regs__t", "group__uart__registers_structmxc__uart__regs__t" ],
    [ "mxc_uart_req_t", "group__uart.html#struct__mxc__uart__req__t", "group__uart_struct__mxc__uart__req__t" ],
    [ "mxc_wdt_regs_t", "group__wdt__registers.html#structmxc__wdt__regs__t", "group__wdt__registers_structmxc__wdt__regs__t" ]
];