/******************************************************************************
 *
 * Copyright (C) 2019-2023 Maxim Integrated Products, Inc. All Rights Reserved.
 * (now owned by Analog Devices, Inc.),
 * Copyright (C) 2023-2024 Analog Devices, Inc. All Rights Reserved. This software
 * is proprietary to Analog Devices, Inc. and its licensors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/

// kinetics
// This file was @generated by ai8xize.py --test-dir sdk/Examples/MAX78000/CNN --prefix kinetics --checkpoint-file trained/ai85-kinetics-qat8-q.pth.tar --config-file networks/ai85-kinetics-actiontcn.yaml --overlap-data --softmax --zero-sram --device MAX78000 --timer 0 --display-checkpoint --verbose --overwrite

// DO NOT EDIT - regenerate this file instead!

// Configuring 21 layers
// Input data: HWC
// Layer 0: 96x60x60, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 64x60x60 output
// Layer 1: 64x60x60, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x60x60 output
// Layer 2: 64x60x60, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x30x30 output
// Layer 3: 64x30x30, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x30x30 output
// Layer 4: 64x30x30, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x15x15 output
// Layer 5: 64x15x15, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 64x15x15 output
// Layer 6: 64x30x30, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x15x15 output
// Layer 7: 2x64x15x15, no pooling, 2-element add, no convolution, 64x15x15 output
// Layer 8: 64x15x15, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x7x7 output
// Layer 9: 64x7x7, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 64x7x7 output
// Layer 10: 64x15x15, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x7x7 output
// Layer 11: 2x64x7x7, no pooling, 2-element add, no convolution, 64x7x7 output
// Layer 12: 64x7x7, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x3x3 output
// Layer 13: 64x3x3, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 64x3x3 output
// Layer 14: 64x7x7, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x3x3 output
// Layer 15: 2x64x3x3, no pooling, 2-element add, no convolution, 64x3x3 output
// Layer 16: 32x14x1, no pooling, no convolution, 32x14x1 output
// Layer 17: 64x3x3, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 0/0, ReLU, 32x1x1 output
// Layer 18: 32x15, no pooling, conv1d with kernel size 3, stride 1, pad 0, ReLU, 32x13 output
// Layer 19: 32x13, no pooling, conv1d with kernel size 3, stride 1, pad 0, ReLU, dilation 2, 32x9 output
// Layer 20: 32x9, no pooling, conv1d with kernel size 3, stride 1, pad 0, no activation, dilation 4, 5x1 output

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "cnn.h"
#include "weights.h"

void CNN_ISR(void)
{
  // Acknowledge interrupt to all quadrants
  *((volatile uint32_t *) 0x50100000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50500000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50900000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50d00000) &= ~((1<<12) | 1);

  CNN_COMPLETE; // Signal that processing is complete
#ifdef CNN_INFERENCE_TIMER
  cnn_time = MXC_TMR_SW_Stop(CNN_INFERENCE_TIMER);
#else
  cnn_time = 1;
#endif
}

int cnn_continue(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) |= 1; // Re-enable quadrant 0

  return CNN_OK;
}

int cnn_stop(void)
{
  *((volatile uint32_t *) 0x50100000) &= ~1; // Disable quadrant 0

  return CNN_OK;
}

void memcpy32(uint32_t *dst, const uint32_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

static const uint32_t kernels[] = KERNELS;

int cnn_load_weights(void)
{
  uint32_t len;
  volatile uint32_t *addr;
  const uint32_t *ptr = kernels;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    *((volatile uint8_t *) ((uint32_t) addr | 1)) = 0x01; // Set address
    len = *ptr++;
    while (len-- > 0)
      *addr++ = *ptr++;
  }

  return CNN_OK;
}

static const uint8_t bias_0[] = BIAS_0;
static const uint8_t bias_1[] = BIAS_1;
static const uint8_t bias_2[] = BIAS_2;
static const uint8_t bias_3[] = BIAS_3;

static void memcpy_8to32(uint32_t *dst, const uint8_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

int cnn_load_bias(void)
{
  memcpy_8to32((uint32_t *) 0x50108000, bias_0, sizeof(uint8_t) * 256);
  memcpy_8to32((uint32_t *) 0x50508000, bias_1, sizeof(uint8_t) * 229);
  memcpy_8to32((uint32_t *) 0x50908000, bias_2, sizeof(uint8_t) * 224);
  memcpy_8to32((uint32_t *) 0x50d08000, bias_3, sizeof(uint8_t) * 224);

  return CNN_OK;
}

int cnn_init(void)
{
  *((volatile uint32_t *) 0x50001000) = 0x00000000; // AON control
  *((volatile uint32_t *) 0x50100000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50100004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50100008) = 0x00000014; // Layer count
  *((volatile uint32_t *) 0x50500000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50500004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50500008) = 0x00000014; // Layer count
  *((volatile uint32_t *) 0x50900000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50900004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50900008) = 0x00000014; // Layer count
  *((volatile uint32_t *) 0x50d00000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50d00004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50d00008) = 0x00000014; // Layer count
  *((volatile uint32_t *) 0x5010000c) = 0x00000001; // Data SRAM BIST
  *((volatile uint32_t *) 0x5050000c) = 0x00000001; // Data SRAM BIST
  *((volatile uint32_t *) 0x5090000c) = 0x00000001; // Data SRAM BIST
  *((volatile uint32_t *) 0x50d0000c) = 0x00000001; // Data SRAM BIST
  while ((*((volatile uint32_t *) 0x5010000c) & 0x8040000) != 0x8040000); // Wait for BIST
  while ((*((volatile uint32_t *) 0x5050000c) & 0x8040000) != 0x8040000); // Wait for BIST
  while ((*((volatile uint32_t *) 0x5090000c) & 0x8040000) != 0x8040000); // Wait for BIST
  while ((*((volatile uint32_t *) 0x50d0000c) & 0x8040000) != 0x8040000); // Wait for BIST
  if ((*((volatile uint32_t *) 0x5010000c) & 0x00004000) != 0x00000000) return CNN_FAIL; // Return on BIST error
  if ((*((volatile uint32_t *) 0x5050000c) & 0x00004000) != 0x00000000) return CNN_FAIL; // Return on BIST error
  if ((*((volatile uint32_t *) 0x5090000c) & 0x00004000) != 0x00000000) return CNN_FAIL; // Return on BIST error
  if ((*((volatile uint32_t *) 0x50d0000c) & 0x00004000) != 0x00000000) return CNN_FAIL; // Return on BIST error
  *((volatile uint32_t *) 0x5010000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x5050000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x5090000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x50d0000c) = 0x00000000; // Reset BIST

  *((volatile uint32_t *) 0x5010000c) = 0x00000004; // Mask SRAM BIST
  *((volatile uint32_t *) 0x5050000c) = 0x00000004; // Mask SRAM BIST
  *((volatile uint32_t *) 0x5090000c) = 0x00000004; // Mask SRAM BIST
  *((volatile uint32_t *) 0x50d0000c) = 0x00000004; // Mask SRAM BIST
  while ((*((volatile uint32_t *) 0x5010000c) & 0x8080000) != 0x8080000); // Wait for BIST
  while ((*((volatile uint32_t *) 0x5050000c) & 0x8080000) != 0x8080000); // Wait for BIST
  while ((*((volatile uint32_t *) 0x5090000c) & 0x8080000) != 0x8080000); // Wait for BIST
  while ((*((volatile uint32_t *) 0x50d0000c) & 0x8080000) != 0x8080000); // Wait for BIST
  if ((*((volatile uint32_t *) 0x5010000c) & 0x00008000) != 0x00000000) return CNN_FAIL; // Return on BIST error
  if ((*((volatile uint32_t *) 0x5050000c) & 0x00008000) != 0x00000000) return CNN_FAIL; // Return on BIST error
  if ((*((volatile uint32_t *) 0x5090000c) & 0x00008000) != 0x00000000) return CNN_FAIL; // Return on BIST error
  if ((*((volatile uint32_t *) 0x50d0000c) & 0x00008000) != 0x00000000) return CNN_FAIL; // Return on BIST error
  *((volatile uint32_t *) 0x5010000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x5050000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x5090000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x50d0000c) = 0x00000000; // Reset BIST

  *((volatile uint32_t *) 0x5010000c) = 0x00000010; // Tornado SRAM BIST
  *((volatile uint32_t *) 0x5050000c) = 0x00000010; // Tornado SRAM BIST
  *((volatile uint32_t *) 0x5090000c) = 0x00000010; // Tornado SRAM BIST
  *((volatile uint32_t *) 0x50d0000c) = 0x00000010; // Tornado SRAM BIST
  while ((*((volatile uint32_t *) 0x5010000c) & 0x8100000) != 0x8100000); // Wait for BIST
  while ((*((volatile uint32_t *) 0x5050000c) & 0x8100000) != 0x8100000); // Wait for BIST
  while ((*((volatile uint32_t *) 0x5090000c) & 0x8100000) != 0x8100000); // Wait for BIST
  while ((*((volatile uint32_t *) 0x50d0000c) & 0x8100000) != 0x8100000); // Wait for BIST
  if ((*((volatile uint32_t *) 0x5010000c) & 0x00010000) != 0x00000000) return CNN_FAIL; // Return on BIST error
  if ((*((volatile uint32_t *) 0x5050000c) & 0x00010000) != 0x00000000) return CNN_FAIL; // Return on BIST error
  if ((*((volatile uint32_t *) 0x5090000c) & 0x00010000) != 0x00000000) return CNN_FAIL; // Return on BIST error
  if ((*((volatile uint32_t *) 0x50d0000c) & 0x00010000) != 0x00000000) return CNN_FAIL; // Return on BIST error
  *((volatile uint32_t *) 0x5010000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x5050000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x5090000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x50d0000c) = 0x00000000; // Reset BIST

  *((volatile uint32_t *) 0x5010000c) = 0x00000040; // Bias Rfile BIST
  *((volatile uint32_t *) 0x5050000c) = 0x00000040; // Bias Rfile BIST
  *((volatile uint32_t *) 0x5090000c) = 0x00000040; // Bias Rfile BIST
  *((volatile uint32_t *) 0x50d0000c) = 0x00000040; // Bias Rfile BIST
  while ((*((volatile uint32_t *) 0x5010000c) & 0x8200000) != 0x8200000); // Wait for BIST
  while ((*((volatile uint32_t *) 0x5050000c) & 0x8200000) != 0x8200000); // Wait for BIST
  while ((*((volatile uint32_t *) 0x5090000c) & 0x8200000) != 0x8200000); // Wait for BIST
  while ((*((volatile uint32_t *) 0x50d0000c) & 0x8200000) != 0x8200000); // Wait for BIST
  if ((*((volatile uint32_t *) 0x5010000c) & 0x00020000) != 0x00000000) return CNN_FAIL; // Return on BIST error
  if ((*((volatile uint32_t *) 0x5050000c) & 0x00020000) != 0x00000000) return CNN_FAIL; // Return on BIST error
  if ((*((volatile uint32_t *) 0x5090000c) & 0x00020000) != 0x00000000) return CNN_FAIL; // Return on BIST error
  if ((*((volatile uint32_t *) 0x50d0000c) & 0x00020000) != 0x00000000) return CNN_FAIL; // Return on BIST error
  *((volatile uint32_t *) 0x5010000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x5050000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x5090000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x50d0000c) = 0x00000000; // Reset BIST


  return CNN_OK;
}

int cnn_configure(void)
{
  // Layer 0 quadrant 0
  *((volatile uint32_t *) 0x50100010) = 0x0000003b; // Rows
  *((volatile uint32_t *) 0x50100090) = 0x0000003b; // Columns
  *((volatile uint32_t *) 0x50100310) = 0x0000003e; // SRAM write ptr
  *((volatile uint32_t *) 0x50100390) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100510) = 0x000003c0; // SRAM read ptr
  *((volatile uint32_t *) 0x50100590) = 0x00006b20; // Layer control
  *((volatile uint32_t *) 0x50100a10) = 0x0001f801; // Layer control 2
  *((volatile uint32_t *) 0x50100610) = 0x000003f8; // Mask offset and count
  *((volatile uint32_t *) 0x50100110) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50100790) = 0x00025000; // Post processing register
  *((volatile uint32_t *) 0x50100710) = 0xffffffff; // Mask and processor enables

  // Layer 0 quadrant 1
  *((volatile uint32_t *) 0x50500010) = 0x0000003b; // Rows
  *((volatile uint32_t *) 0x50500090) = 0x0000003b; // Columns
  *((volatile uint32_t *) 0x50500310) = 0x0000003e; // SRAM write ptr
  *((volatile uint32_t *) 0x50500390) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500510) = 0x000003c0; // SRAM read ptr
  *((volatile uint32_t *) 0x50500590) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a10) = 0x0001f801; // Layer control 2
  *((volatile uint32_t *) 0x50500610) = 0x000003f8; // Mask offset and count
  *((volatile uint32_t *) 0x50500110) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50500790) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50500710) = 0xffffffff; // Mask and processor enables

  // Layer 0 quadrant 2
  *((volatile uint32_t *) 0x50900010) = 0x0000003b; // Rows
  *((volatile uint32_t *) 0x50900090) = 0x0000003b; // Columns
  *((volatile uint32_t *) 0x50900310) = 0x0000003e; // SRAM write ptr
  *((volatile uint32_t *) 0x50900390) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900510) = 0x000003c0; // SRAM read ptr
  *((volatile uint32_t *) 0x50900590) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a10) = 0x0001f801; // Layer control 2
  *((volatile uint32_t *) 0x50900610) = 0x000003f8; // Mask offset and count
  *((volatile uint32_t *) 0x50900110) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50900790) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50900710) = 0xffffffff; // Mask and processor enables

  // Layer 0 quadrant 3
  *((volatile uint32_t *) 0x50d00010) = 0x0000003b; // Rows
  *((volatile uint32_t *) 0x50d00090) = 0x0000003b; // Columns
  *((volatile uint32_t *) 0x50d00310) = 0x0000003e; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00390) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00510) = 0x000003c0; // SRAM read ptr
  *((volatile uint32_t *) 0x50d00590) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a10) = 0x0001f801; // Layer control 2
  *((volatile uint32_t *) 0x50d00610) = 0x000003f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00110) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d00790) = 0x00024000; // Post processing register

  // Layer 1 quadrant 0
  *((volatile uint32_t *) 0x50100014) = 0x0001003d; // Rows
  *((volatile uint32_t *) 0x50100094) = 0x0001003d; // Columns
  *((volatile uint32_t *) 0x50100314) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100514) = 0x0000003e; // SRAM read ptr
  *((volatile uint32_t *) 0x50100594) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a14) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100614) = 0x00800278; // Mask offset and count
  *((volatile uint32_t *) 0x50100694) = 0x0000003b; // TRAM ptr max
  *((volatile uint32_t *) 0x50100794) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100714) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 1
  *((volatile uint32_t *) 0x50500014) = 0x0001003d; // Rows
  *((volatile uint32_t *) 0x50500094) = 0x0001003d; // Columns
  *((volatile uint32_t *) 0x50500314) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500514) = 0x0000003e; // SRAM read ptr
  *((volatile uint32_t *) 0x50500594) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a14) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500614) = 0x00800278; // Mask offset and count
  *((volatile uint32_t *) 0x50500694) = 0x0000003b; // TRAM ptr max
  *((volatile uint32_t *) 0x50500794) = 0x00023000; // Post processing register
  *((volatile uint32_t *) 0x50500714) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 2
  *((volatile uint32_t *) 0x50900014) = 0x0001003d; // Rows
  *((volatile uint32_t *) 0x50900094) = 0x0001003d; // Columns
  *((volatile uint32_t *) 0x50900314) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900514) = 0x0000003e; // SRAM read ptr
  *((volatile uint32_t *) 0x50900594) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a14) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900614) = 0x00800278; // Mask offset and count
  *((volatile uint32_t *) 0x50900694) = 0x0000003b; // TRAM ptr max
  *((volatile uint32_t *) 0x50900794) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900714) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 3
  *((volatile uint32_t *) 0x50d00014) = 0x0001003d; // Rows
  *((volatile uint32_t *) 0x50d00094) = 0x0001003d; // Columns
  *((volatile uint32_t *) 0x50d00314) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00514) = 0x0000003e; // SRAM read ptr
  *((volatile uint32_t *) 0x50d00594) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a14) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00614) = 0x00800278; // Mask offset and count
  *((volatile uint32_t *) 0x50d00694) = 0x0000003b; // TRAM ptr max
  *((volatile uint32_t *) 0x50d00794) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00714) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 0
  *((volatile uint32_t *) 0x50100018) = 0x0001003d; // Rows
  *((volatile uint32_t *) 0x50100098) = 0x0001003d; // Columns
  *((volatile uint32_t *) 0x50100198) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100218) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50100298) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100518) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50100598) = 0x0000eba0; // Layer control
  *((volatile uint32_t *) 0x50100a18) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100618) = 0x02800478; // Mask offset and count
  *((volatile uint32_t *) 0x50100698) = 0x0000001d; // TRAM ptr max
  *((volatile uint32_t *) 0x50100798) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 1
  *((volatile uint32_t *) 0x50500018) = 0x0001003d; // Rows
  *((volatile uint32_t *) 0x50500098) = 0x0001003d; // Columns
  *((volatile uint32_t *) 0x50500198) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500218) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50500298) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500518) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50500598) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a18) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500618) = 0x02800478; // Mask offset and count
  *((volatile uint32_t *) 0x50500698) = 0x0000001d; // TRAM ptr max
  *((volatile uint32_t *) 0x50500798) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50500718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 2
  *((volatile uint32_t *) 0x50900018) = 0x0001003d; // Rows
  *((volatile uint32_t *) 0x50900098) = 0x0001003d; // Columns
  *((volatile uint32_t *) 0x50900198) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900218) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50900298) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900518) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50900598) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a18) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900618) = 0x02800478; // Mask offset and count
  *((volatile uint32_t *) 0x50900698) = 0x0000001d; // TRAM ptr max
  *((volatile uint32_t *) 0x50900798) = 0x00023000; // Post processing register
  *((volatile uint32_t *) 0x50900718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 3
  *((volatile uint32_t *) 0x50d00018) = 0x0001003d; // Rows
  *((volatile uint32_t *) 0x50d00098) = 0x0001003d; // Columns
  *((volatile uint32_t *) 0x50d00198) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00218) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d00298) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00518) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d00598) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a18) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00618) = 0x02800478; // Mask offset and count
  *((volatile uint32_t *) 0x50d00698) = 0x0000001d; // TRAM ptr max
  *((volatile uint32_t *) 0x50d00798) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00718) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 0
  *((volatile uint32_t *) 0x5010001c) = 0x0001001f; // Rows
  *((volatile uint32_t *) 0x5010009c) = 0x0001001f; // Columns
  *((volatile uint32_t *) 0x5010031c) = 0x00001400; // SRAM write ptr
  *((volatile uint32_t *) 0x5010041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010059c) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a1c) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x5010061c) = 0x04800678; // Mask offset and count
  *((volatile uint32_t *) 0x5010069c) = 0x0000001d; // TRAM ptr max
  *((volatile uint32_t *) 0x5010079c) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x5010071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 1
  *((volatile uint32_t *) 0x5050001c) = 0x0001001f; // Rows
  *((volatile uint32_t *) 0x5050009c) = 0x0001001f; // Columns
  *((volatile uint32_t *) 0x5050031c) = 0x00001400; // SRAM write ptr
  *((volatile uint32_t *) 0x5050041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a1c) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x5050061c) = 0x04800678; // Mask offset and count
  *((volatile uint32_t *) 0x5050069c) = 0x0000001d; // TRAM ptr max
  *((volatile uint32_t *) 0x5050079c) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x5050071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 2
  *((volatile uint32_t *) 0x5090001c) = 0x0001001f; // Rows
  *((volatile uint32_t *) 0x5090009c) = 0x0001001f; // Columns
  *((volatile uint32_t *) 0x5090031c) = 0x00001400; // SRAM write ptr
  *((volatile uint32_t *) 0x5090041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a1c) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x5090061c) = 0x04800678; // Mask offset and count
  *((volatile uint32_t *) 0x5090069c) = 0x0000001d; // TRAM ptr max
  *((volatile uint32_t *) 0x5090079c) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x5090071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 3
  *((volatile uint32_t *) 0x50d0001c) = 0x0001001f; // Rows
  *((volatile uint32_t *) 0x50d0009c) = 0x0001001f; // Columns
  *((volatile uint32_t *) 0x50d0031c) = 0x00001400; // SRAM write ptr
  *((volatile uint32_t *) 0x50d0041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a1c) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d0061c) = 0x04800678; // Mask offset and count
  *((volatile uint32_t *) 0x50d0069c) = 0x0000001d; // TRAM ptr max
  *((volatile uint32_t *) 0x50d0079c) = 0x00025000; // Post processing register
  *((volatile uint32_t *) 0x50d0071c) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 0
  *((volatile uint32_t *) 0x50100020) = 0x0001001f; // Rows
  *((volatile uint32_t *) 0x501000a0) = 0x0001001f; // Columns
  *((volatile uint32_t *) 0x501001a0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100220) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x501002a0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100520) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x501005a0) = 0x0000eba0; // Layer control
  *((volatile uint32_t *) 0x50100a20) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100620) = 0x06800878; // Mask offset and count
  *((volatile uint32_t *) 0x501006a0) = 0x0000000e; // TRAM ptr max
  *((volatile uint32_t *) 0x501007a0) = 0x00025040; // Post processing register
  *((volatile uint32_t *) 0x50100720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 1
  *((volatile uint32_t *) 0x50500020) = 0x0001001f; // Rows
  *((volatile uint32_t *) 0x505000a0) = 0x0001001f; // Columns
  *((volatile uint32_t *) 0x505001a0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500220) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x505002a0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500520) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x505005a0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a20) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500620) = 0x06800878; // Mask offset and count
  *((volatile uint32_t *) 0x505006a0) = 0x0000000e; // TRAM ptr max
  *((volatile uint32_t *) 0x505007a0) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50500720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 2
  *((volatile uint32_t *) 0x50900020) = 0x0001001f; // Rows
  *((volatile uint32_t *) 0x509000a0) = 0x0001001f; // Columns
  *((volatile uint32_t *) 0x509001a0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900220) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x509002a0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900520) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x509005a0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a20) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900620) = 0x06800878; // Mask offset and count
  *((volatile uint32_t *) 0x509006a0) = 0x0000000e; // TRAM ptr max
  *((volatile uint32_t *) 0x509007a0) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50900720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 3
  *((volatile uint32_t *) 0x50d00020) = 0x0001001f; // Rows
  *((volatile uint32_t *) 0x50d000a0) = 0x0001001f; // Columns
  *((volatile uint32_t *) 0x50d001a0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00220) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d002a0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00520) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005a0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a20) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00620) = 0x06800878; // Mask offset and count
  *((volatile uint32_t *) 0x50d006a0) = 0x0000000e; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007a0) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50d00720) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 0
  *((volatile uint32_t *) 0x50100024) = 0x0000000e; // Rows
  *((volatile uint32_t *) 0x501000a4) = 0x0000000e; // Columns
  *((volatile uint32_t *) 0x50100324) = 0x00000400; // SRAM write ptr
  *((volatile uint32_t *) 0x501003a4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a4) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a24) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100624) = 0x4c804e78; // Mask offset and count
  *((volatile uint32_t *) 0x50100124) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007a4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100724) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 1
  *((volatile uint32_t *) 0x50500024) = 0x0000000e; // Rows
  *((volatile uint32_t *) 0x505000a4) = 0x0000000e; // Columns
  *((volatile uint32_t *) 0x50500324) = 0x00000400; // SRAM write ptr
  *((volatile uint32_t *) 0x505003a4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a24) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500624) = 0x4c804e78; // Mask offset and count
  *((volatile uint32_t *) 0x50500124) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007a4) = 0x00023040; // Post processing register
  *((volatile uint32_t *) 0x50500724) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 2
  *((volatile uint32_t *) 0x50900024) = 0x0000000e; // Rows
  *((volatile uint32_t *) 0x509000a4) = 0x0000000e; // Columns
  *((volatile uint32_t *) 0x50900324) = 0x00000400; // SRAM write ptr
  *((volatile uint32_t *) 0x509003a4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a24) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900624) = 0x4c804e78; // Mask offset and count
  *((volatile uint32_t *) 0x50900124) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007a4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900724) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 3
  *((volatile uint32_t *) 0x50d00024) = 0x0000000e; // Rows
  *((volatile uint32_t *) 0x50d000a4) = 0x0000000e; // Columns
  *((volatile uint32_t *) 0x50d00324) = 0x00000400; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003a4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a24) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00624) = 0x4c804e78; // Mask offset and count
  *((volatile uint32_t *) 0x50d00124) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007a4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00724) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 0
  *((volatile uint32_t *) 0x50100028) = 0x0001001f; // Rows
  *((volatile uint32_t *) 0x501000a8) = 0x0001001f; // Columns
  *((volatile uint32_t *) 0x501001a8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100228) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x501002a8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100328) = 0x00000401; // SRAM write ptr
  *((volatile uint32_t *) 0x50100428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100528) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x501005a8) = 0x0000eba0; // Layer control
  *((volatile uint32_t *) 0x50100a28) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100628) = 0x08c00ab8; // Mask offset and count
  *((volatile uint32_t *) 0x501006a8) = 0x0000000e; // TRAM ptr max
  *((volatile uint32_t *) 0x501007a8) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50100728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 1
  *((volatile uint32_t *) 0x50500028) = 0x0001001f; // Rows
  *((volatile uint32_t *) 0x505000a8) = 0x0001001f; // Columns
  *((volatile uint32_t *) 0x505001a8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500228) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x505002a8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500328) = 0x00000401; // SRAM write ptr
  *((volatile uint32_t *) 0x50500428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500528) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x505005a8) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a28) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500628) = 0x08c00ab8; // Mask offset and count
  *((volatile uint32_t *) 0x505006a8) = 0x0000000e; // TRAM ptr max
  *((volatile uint32_t *) 0x505007a8) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50500728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 2
  *((volatile uint32_t *) 0x50900028) = 0x0001001f; // Rows
  *((volatile uint32_t *) 0x509000a8) = 0x0001001f; // Columns
  *((volatile uint32_t *) 0x509001a8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900228) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x509002a8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900328) = 0x00000401; // SRAM write ptr
  *((volatile uint32_t *) 0x50900428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900528) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x509005a8) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a28) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900628) = 0x08c00ab8; // Mask offset and count
  *((volatile uint32_t *) 0x509006a8) = 0x0000000e; // TRAM ptr max
  *((volatile uint32_t *) 0x509007a8) = 0x00025040; // Post processing register
  *((volatile uint32_t *) 0x50900728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 3
  *((volatile uint32_t *) 0x50d00028) = 0x0001001f; // Rows
  *((volatile uint32_t *) 0x50d000a8) = 0x0001001f; // Columns
  *((volatile uint32_t *) 0x50d001a8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00228) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d002a8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00328) = 0x00000401; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00528) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005a8) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a28) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00628) = 0x08c00ab8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006a8) = 0x0000000e; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007a8) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50d00728) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 0
  *((volatile uint32_t *) 0x5010002c) = 0x0000000e; // Rows
  *((volatile uint32_t *) 0x501000ac) = 0x0000000e; // Columns
  *((volatile uint32_t *) 0x5010032c) = 0x00001400; // SRAM write ptr
  *((volatile uint32_t *) 0x501003ac) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5010052c) = 0x00000400; // SRAM read ptr
  *((volatile uint32_t *) 0x501005ac) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x5010012c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x501007ac) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5010072c) = 0x0000ffff; // Mask and processor enables

  // Layer 7 quadrant 1
  *((volatile uint32_t *) 0x5050002c) = 0x0000000e; // Rows
  *((volatile uint32_t *) 0x505000ac) = 0x0000000e; // Columns
  *((volatile uint32_t *) 0x5050032c) = 0x00009400; // SRAM write ptr
  *((volatile uint32_t *) 0x505003ac) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5050052c) = 0x00000400; // SRAM read ptr
  *((volatile uint32_t *) 0x505005ac) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x5050012c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x505007ac) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5050072c) = 0x0000ffff; // Mask and processor enables

  // Layer 7 quadrant 2
  *((volatile uint32_t *) 0x5090002c) = 0x0000000e; // Rows
  *((volatile uint32_t *) 0x509000ac) = 0x0000000e; // Columns
  *((volatile uint32_t *) 0x5090032c) = 0x00011400; // SRAM write ptr
  *((volatile uint32_t *) 0x509003ac) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5090052c) = 0x00000400; // SRAM read ptr
  *((volatile uint32_t *) 0x509005ac) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x5090012c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x509007ac) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5090072c) = 0x0000ffff; // Mask and processor enables

  // Layer 7 quadrant 3
  *((volatile uint32_t *) 0x50d0002c) = 0x0000000e; // Rows
  *((volatile uint32_t *) 0x50d000ac) = 0x0000000e; // Columns
  *((volatile uint32_t *) 0x50d0032c) = 0x00019400; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003ac) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d0052c) = 0x00000400; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005ac) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d0012c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x50d007ac) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50d0072c) = 0x0000ffff; // Mask and processor enables

  // Layer 8 quadrant 0
  *((volatile uint32_t *) 0x50100030) = 0x00010010; // Rows
  *((volatile uint32_t *) 0x501000b0) = 0x00010010; // Columns
  *((volatile uint32_t *) 0x501001b0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100230) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x501002b0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100530) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x501005b0) = 0x0000eba0; // Layer control
  *((volatile uint32_t *) 0x50100a30) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100630) = 0x0ac00cb8; // Mask offset and count
  *((volatile uint32_t *) 0x501006b0) = 0x00000006; // TRAM ptr max
  *((volatile uint32_t *) 0x501007b0) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50100730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 1
  *((volatile uint32_t *) 0x50500030) = 0x00010010; // Rows
  *((volatile uint32_t *) 0x505000b0) = 0x00010010; // Columns
  *((volatile uint32_t *) 0x505001b0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500230) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x505002b0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500530) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x505005b0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a30) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500630) = 0x0ac00cb8; // Mask offset and count
  *((volatile uint32_t *) 0x505006b0) = 0x00000006; // TRAM ptr max
  *((volatile uint32_t *) 0x505007b0) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50500730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 2
  *((volatile uint32_t *) 0x50900030) = 0x00010010; // Rows
  *((volatile uint32_t *) 0x509000b0) = 0x00010010; // Columns
  *((volatile uint32_t *) 0x509001b0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900230) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x509002b0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900530) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x509005b0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a30) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900630) = 0x0ac00cb8; // Mask offset and count
  *((volatile uint32_t *) 0x509006b0) = 0x00000006; // TRAM ptr max
  *((volatile uint32_t *) 0x509007b0) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50900730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 3
  *((volatile uint32_t *) 0x50d00030) = 0x00010010; // Rows
  *((volatile uint32_t *) 0x50d000b0) = 0x00010010; // Columns
  *((volatile uint32_t *) 0x50d001b0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00230) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d002b0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00530) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005b0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a30) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00630) = 0x0ac00cb8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006b0) = 0x00000006; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007b0) = 0x00025040; // Post processing register
  *((volatile uint32_t *) 0x50d00730) = 0xffffffff; // Mask and processor enables

  // Layer 9 quadrant 0
  *((volatile uint32_t *) 0x50100034) = 0x00000006; // Rows
  *((volatile uint32_t *) 0x501000b4) = 0x00000006; // Columns
  *((volatile uint32_t *) 0x50100334) = 0x00000400; // SRAM write ptr
  *((volatile uint32_t *) 0x501003b4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005b4) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a34) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100634) = 0x72c074b8; // Mask offset and count
  *((volatile uint32_t *) 0x50100134) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007b4) = 0x00023080; // Post processing register
  *((volatile uint32_t *) 0x50100734) = 0xffffffff; // Mask and processor enables

  // Layer 9 quadrant 1
  *((volatile uint32_t *) 0x50500034) = 0x00000006; // Rows
  *((volatile uint32_t *) 0x505000b4) = 0x00000006; // Columns
  *((volatile uint32_t *) 0x50500334) = 0x00000400; // SRAM write ptr
  *((volatile uint32_t *) 0x505003b4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005b4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a34) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500634) = 0x72c074b8; // Mask offset and count
  *((volatile uint32_t *) 0x50500134) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007b4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50500734) = 0xffffffff; // Mask and processor enables

  // Layer 9 quadrant 2
  *((volatile uint32_t *) 0x50900034) = 0x00000006; // Rows
  *((volatile uint32_t *) 0x509000b4) = 0x00000006; // Columns
  *((volatile uint32_t *) 0x50900334) = 0x00000400; // SRAM write ptr
  *((volatile uint32_t *) 0x509003b4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005b4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a34) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900634) = 0x72c074b8; // Mask offset and count
  *((volatile uint32_t *) 0x50900134) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007b4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900734) = 0xffffffff; // Mask and processor enables

  // Layer 9 quadrant 3
  *((volatile uint32_t *) 0x50d00034) = 0x00000006; // Rows
  *((volatile uint32_t *) 0x50d000b4) = 0x00000006; // Columns
  *((volatile uint32_t *) 0x50d00334) = 0x00000400; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003b4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005b4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a34) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00634) = 0x72c074b8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00134) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007b4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00734) = 0xffffffff; // Mask and processor enables

  // Layer 10 quadrant 0
  *((volatile uint32_t *) 0x50100038) = 0x00010010; // Rows
  *((volatile uint32_t *) 0x501000b8) = 0x00010010; // Columns
  *((volatile uint32_t *) 0x501001b8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100238) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x501002b8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100338) = 0x00000401; // SRAM write ptr
  *((volatile uint32_t *) 0x50100438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100538) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x501005b8) = 0x0000eba0; // Layer control
  *((volatile uint32_t *) 0x50100a38) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100638) = 0x0d000ef8; // Mask offset and count
  *((volatile uint32_t *) 0x501006b8) = 0x00000006; // TRAM ptr max
  *((volatile uint32_t *) 0x501007b8) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50100738) = 0xffffffff; // Mask and processor enables

  // Layer 10 quadrant 1
  *((volatile uint32_t *) 0x50500038) = 0x00010010; // Rows
  *((volatile uint32_t *) 0x505000b8) = 0x00010010; // Columns
  *((volatile uint32_t *) 0x505001b8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500238) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x505002b8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500338) = 0x00000401; // SRAM write ptr
  *((volatile uint32_t *) 0x50500438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500538) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x505005b8) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a38) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500638) = 0x0d000ef8; // Mask offset and count
  *((volatile uint32_t *) 0x505006b8) = 0x00000006; // TRAM ptr max
  *((volatile uint32_t *) 0x505007b8) = 0x00025080; // Post processing register
  *((volatile uint32_t *) 0x50500738) = 0xffffffff; // Mask and processor enables

  // Layer 10 quadrant 2
  *((volatile uint32_t *) 0x50900038) = 0x00010010; // Rows
  *((volatile uint32_t *) 0x509000b8) = 0x00010010; // Columns
  *((volatile uint32_t *) 0x509001b8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900238) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x509002b8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900338) = 0x00000401; // SRAM write ptr
  *((volatile uint32_t *) 0x50900438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900538) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x509005b8) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a38) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900638) = 0x0d000ef8; // Mask offset and count
  *((volatile uint32_t *) 0x509006b8) = 0x00000006; // TRAM ptr max
  *((volatile uint32_t *) 0x509007b8) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50900738) = 0xffffffff; // Mask and processor enables

  // Layer 10 quadrant 3
  *((volatile uint32_t *) 0x50d00038) = 0x00010010; // Rows
  *((volatile uint32_t *) 0x50d000b8) = 0x00010010; // Columns
  *((volatile uint32_t *) 0x50d001b8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00238) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d002b8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00338) = 0x00000401; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00538) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005b8) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a38) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00638) = 0x0d000ef8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006b8) = 0x00000006; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007b8) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50d00738) = 0xffffffff; // Mask and processor enables

  // Layer 11 quadrant 0
  *((volatile uint32_t *) 0x5010003c) = 0x00000006; // Rows
  *((volatile uint32_t *) 0x501000bc) = 0x00000006; // Columns
  *((volatile uint32_t *) 0x5010033c) = 0x00001400; // SRAM write ptr
  *((volatile uint32_t *) 0x501003bc) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5010053c) = 0x00000400; // SRAM read ptr
  *((volatile uint32_t *) 0x501005bc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x5010013c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x501007bc) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5010073c) = 0x0000ffff; // Mask and processor enables

  // Layer 11 quadrant 1
  *((volatile uint32_t *) 0x5050003c) = 0x00000006; // Rows
  *((volatile uint32_t *) 0x505000bc) = 0x00000006; // Columns
  *((volatile uint32_t *) 0x5050033c) = 0x00009400; // SRAM write ptr
  *((volatile uint32_t *) 0x505003bc) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5050053c) = 0x00000400; // SRAM read ptr
  *((volatile uint32_t *) 0x505005bc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x5050013c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x505007bc) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5050073c) = 0x0000ffff; // Mask and processor enables

  // Layer 11 quadrant 2
  *((volatile uint32_t *) 0x5090003c) = 0x00000006; // Rows
  *((volatile uint32_t *) 0x509000bc) = 0x00000006; // Columns
  *((volatile uint32_t *) 0x5090033c) = 0x00011400; // SRAM write ptr
  *((volatile uint32_t *) 0x509003bc) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5090053c) = 0x00000400; // SRAM read ptr
  *((volatile uint32_t *) 0x509005bc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x5090013c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x509007bc) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5090073c) = 0x0000ffff; // Mask and processor enables

  // Layer 11 quadrant 3
  *((volatile uint32_t *) 0x50d0003c) = 0x00000006; // Rows
  *((volatile uint32_t *) 0x50d000bc) = 0x00000006; // Columns
  *((volatile uint32_t *) 0x50d0033c) = 0x00019400; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003bc) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d0053c) = 0x00000400; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005bc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d0013c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x50d007bc) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50d0073c) = 0x0000ffff; // Mask and processor enables

  // Layer 12 quadrant 0
  *((volatile uint32_t *) 0x50100040) = 0x00010008; // Rows
  *((volatile uint32_t *) 0x501000c0) = 0x00010008; // Columns
  *((volatile uint32_t *) 0x501001c0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100240) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x501002c0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100440) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100540) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x501005c0) = 0x0000eba0; // Layer control
  *((volatile uint32_t *) 0x50100a40) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100640) = 0x0f0010f8; // Mask offset and count
  *((volatile uint32_t *) 0x501006c0) = 0x00000002; // TRAM ptr max
  *((volatile uint32_t *) 0x501007c0) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50100740) = 0xffffffff; // Mask and processor enables

  // Layer 12 quadrant 1
  *((volatile uint32_t *) 0x50500040) = 0x00010008; // Rows
  *((volatile uint32_t *) 0x505000c0) = 0x00010008; // Columns
  *((volatile uint32_t *) 0x505001c0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500240) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x505002c0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500440) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500540) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x505005c0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a40) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500640) = 0x0f0010f8; // Mask offset and count
  *((volatile uint32_t *) 0x505006c0) = 0x00000002; // TRAM ptr max
  *((volatile uint32_t *) 0x505007c0) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50500740) = 0xffffffff; // Mask and processor enables

  // Layer 12 quadrant 2
  *((volatile uint32_t *) 0x50900040) = 0x00010008; // Rows
  *((volatile uint32_t *) 0x509000c0) = 0x00010008; // Columns
  *((volatile uint32_t *) 0x509001c0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900240) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x509002c0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900440) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900540) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x509005c0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a40) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900640) = 0x0f0010f8; // Mask offset and count
  *((volatile uint32_t *) 0x509006c0) = 0x00000002; // TRAM ptr max
  *((volatile uint32_t *) 0x509007c0) = 0x00025080; // Post processing register
  *((volatile uint32_t *) 0x50900740) = 0xffffffff; // Mask and processor enables

  // Layer 12 quadrant 3
  *((volatile uint32_t *) 0x50d00040) = 0x00010008; // Rows
  *((volatile uint32_t *) 0x50d000c0) = 0x00010008; // Columns
  *((volatile uint32_t *) 0x50d001c0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00240) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d002c0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00440) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00540) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005c0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a40) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00640) = 0x0f0010f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006c0) = 0x00000002; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007c0) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50d00740) = 0xffffffff; // Mask and processor enables

  // Layer 13 quadrant 0
  *((volatile uint32_t *) 0x50100044) = 0x00000002; // Rows
  *((volatile uint32_t *) 0x501000c4) = 0x00000002; // Columns
  *((volatile uint32_t *) 0x50100344) = 0x00000400; // SRAM write ptr
  *((volatile uint32_t *) 0x501003c4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100444) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005c4) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a44) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100644) = 0x99009af8; // Mask offset and count
  *((volatile uint32_t *) 0x50100144) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007c4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100744) = 0xffffffff; // Mask and processor enables

  // Layer 13 quadrant 1
  *((volatile uint32_t *) 0x50500044) = 0x00000002; // Rows
  *((volatile uint32_t *) 0x505000c4) = 0x00000002; // Columns
  *((volatile uint32_t *) 0x50500344) = 0x00000400; // SRAM write ptr
  *((volatile uint32_t *) 0x505003c4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500444) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005c4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a44) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500644) = 0x99009af8; // Mask offset and count
  *((volatile uint32_t *) 0x50500144) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007c4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50500744) = 0xffffffff; // Mask and processor enables

  // Layer 13 quadrant 2
  *((volatile uint32_t *) 0x50900044) = 0x00000002; // Rows
  *((volatile uint32_t *) 0x509000c4) = 0x00000002; // Columns
  *((volatile uint32_t *) 0x50900344) = 0x00000400; // SRAM write ptr
  *((volatile uint32_t *) 0x509003c4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900444) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005c4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a44) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900644) = 0x99009af8; // Mask offset and count
  *((volatile uint32_t *) 0x50900144) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007c4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900744) = 0xffffffff; // Mask and processor enables

  // Layer 13 quadrant 3
  *((volatile uint32_t *) 0x50d00044) = 0x00000002; // Rows
  *((volatile uint32_t *) 0x50d000c4) = 0x00000002; // Columns
  *((volatile uint32_t *) 0x50d00344) = 0x00000400; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003c4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00444) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005c4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a44) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00644) = 0x99009af8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00144) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007c4) = 0x00023080; // Post processing register
  *((volatile uint32_t *) 0x50d00744) = 0xffffffff; // Mask and processor enables

  // Layer 14 quadrant 0
  *((volatile uint32_t *) 0x50100048) = 0x00010008; // Rows
  *((volatile uint32_t *) 0x501000c8) = 0x00010008; // Columns
  *((volatile uint32_t *) 0x501001c8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100248) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x501002c8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100348) = 0x00000401; // SRAM write ptr
  *((volatile uint32_t *) 0x50100448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100548) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x501005c8) = 0x0000eba0; // Layer control
  *((volatile uint32_t *) 0x50100a48) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100648) = 0x11401338; // Mask offset and count
  *((volatile uint32_t *) 0x501006c8) = 0x00000002; // TRAM ptr max
  *((volatile uint32_t *) 0x501007c8) = 0x000250c0; // Post processing register
  *((volatile uint32_t *) 0x50100748) = 0xffffffff; // Mask and processor enables

  // Layer 14 quadrant 1
  *((volatile uint32_t *) 0x50500048) = 0x00010008; // Rows
  *((volatile uint32_t *) 0x505000c8) = 0x00010008; // Columns
  *((volatile uint32_t *) 0x505001c8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500248) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x505002c8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500348) = 0x00000401; // SRAM write ptr
  *((volatile uint32_t *) 0x50500448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500548) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x505005c8) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a48) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500648) = 0x11401338; // Mask offset and count
  *((volatile uint32_t *) 0x505006c8) = 0x00000002; // TRAM ptr max
  *((volatile uint32_t *) 0x505007c8) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50500748) = 0xffffffff; // Mask and processor enables

  // Layer 14 quadrant 2
  *((volatile uint32_t *) 0x50900048) = 0x00010008; // Rows
  *((volatile uint32_t *) 0x509000c8) = 0x00010008; // Columns
  *((volatile uint32_t *) 0x509001c8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900248) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x509002c8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900348) = 0x00000401; // SRAM write ptr
  *((volatile uint32_t *) 0x50900448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900548) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x509005c8) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a48) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900648) = 0x11401338; // Mask offset and count
  *((volatile uint32_t *) 0x509006c8) = 0x00000002; // TRAM ptr max
  *((volatile uint32_t *) 0x509007c8) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50900748) = 0xffffffff; // Mask and processor enables

  // Layer 14 quadrant 3
  *((volatile uint32_t *) 0x50d00048) = 0x00010008; // Rows
  *((volatile uint32_t *) 0x50d000c8) = 0x00010008; // Columns
  *((volatile uint32_t *) 0x50d001c8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00248) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d002c8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00348) = 0x00000401; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00548) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005c8) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a48) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00648) = 0x11401338; // Mask offset and count
  *((volatile uint32_t *) 0x50d006c8) = 0x00000002; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007c8) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50d00748) = 0xffffffff; // Mask and processor enables

  // Layer 15 quadrant 0
  *((volatile uint32_t *) 0x5010004c) = 0x00000002; // Rows
  *((volatile uint32_t *) 0x501000cc) = 0x00000002; // Columns
  *((volatile uint32_t *) 0x5010034c) = 0x00001400; // SRAM write ptr
  *((volatile uint32_t *) 0x501003cc) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5010054c) = 0x00000400; // SRAM read ptr
  *((volatile uint32_t *) 0x501005cc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x5010014c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x501007cc) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5010074c) = 0x0000ffff; // Mask and processor enables

  // Layer 15 quadrant 1
  *((volatile uint32_t *) 0x5050004c) = 0x00000002; // Rows
  *((volatile uint32_t *) 0x505000cc) = 0x00000002; // Columns
  *((volatile uint32_t *) 0x5050034c) = 0x00009400; // SRAM write ptr
  *((volatile uint32_t *) 0x505003cc) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5050054c) = 0x00000400; // SRAM read ptr
  *((volatile uint32_t *) 0x505005cc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x5050014c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x505007cc) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5050074c) = 0x0000ffff; // Mask and processor enables

  // Layer 15 quadrant 2
  *((volatile uint32_t *) 0x5090004c) = 0x00000002; // Rows
  *((volatile uint32_t *) 0x509000cc) = 0x00000002; // Columns
  *((volatile uint32_t *) 0x5090034c) = 0x00011400; // SRAM write ptr
  *((volatile uint32_t *) 0x509003cc) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5090054c) = 0x00000400; // SRAM read ptr
  *((volatile uint32_t *) 0x509005cc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x5090014c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x509007cc) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5090074c) = 0x0000ffff; // Mask and processor enables

  // Layer 15 quadrant 3
  *((volatile uint32_t *) 0x50d0004c) = 0x00000002; // Rows
  *((volatile uint32_t *) 0x50d000cc) = 0x00000002; // Columns
  *((volatile uint32_t *) 0x50d0034c) = 0x00019400; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003cc) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d0054c) = 0x00000400; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005cc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d0014c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x50d007cc) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50d0074c) = 0x0000ffff; // Mask and processor enables

  // Layer 16 quadrant 0
  *((volatile uint32_t *) 0x50100050) = 0x0000000d; // Rows
  *((volatile uint32_t *) 0x50100350) = 0x00001ff1; // SRAM write ptr
  *((volatile uint32_t *) 0x501003d0) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100550) = 0x00001ff2; // SRAM read ptr
  *((volatile uint32_t *) 0x501005d0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50100150) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x501007d0) = 0x03000000; // Post processing register

  // Layer 16 quadrant 1
  *((volatile uint32_t *) 0x50500050) = 0x0000000d; // Rows
  *((volatile uint32_t *) 0x50500350) = 0x00001ff1; // SRAM write ptr
  *((volatile uint32_t *) 0x505003d0) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500550) = 0x00001ff2; // SRAM read ptr
  *((volatile uint32_t *) 0x505005d0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500150) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x505007d0) = 0x03000000; // Post processing register

  // Layer 16 quadrant 2
  *((volatile uint32_t *) 0x50900050) = 0x0000000d; // Rows
  *((volatile uint32_t *) 0x50900350) = 0x00011ff1; // SRAM write ptr
  *((volatile uint32_t *) 0x509003d0) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900550) = 0x00001ff2; // SRAM read ptr
  *((volatile uint32_t *) 0x509005d0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900150) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x509007d0) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50900750) = 0x0000ffff; // Mask and processor enables

  // Layer 16 quadrant 3
  *((volatile uint32_t *) 0x50d00050) = 0x0000000d; // Rows
  *((volatile uint32_t *) 0x50d00350) = 0x00019ff1; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003d0) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00550) = 0x00001ff2; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005d0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00150) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x50d007d0) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50d00750) = 0x0000ffff; // Mask and processor enables

  // Layer 17 quadrant 0
  *((volatile uint32_t *) 0x50100054) = 0x00000002; // Rows
  *((volatile uint32_t *) 0x501000d4) = 0x00000002; // Columns
  *((volatile uint32_t *) 0x50100354) = 0x00011fff; // SRAM write ptr
  *((volatile uint32_t *) 0x50100454) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100554) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x501005d4) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a54) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50100654) = 0x13401438; // Mask offset and count
  *((volatile uint32_t *) 0x501007d4) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50100754) = 0xffffffff; // Mask and processor enables

  // Layer 17 quadrant 1
  *((volatile uint32_t *) 0x50500054) = 0x00000002; // Rows
  *((volatile uint32_t *) 0x505000d4) = 0x00000002; // Columns
  *((volatile uint32_t *) 0x50500354) = 0x00011fff; // SRAM write ptr
  *((volatile uint32_t *) 0x50500454) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500554) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x505005d4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a54) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50500654) = 0x13401438; // Mask offset and count
  *((volatile uint32_t *) 0x505007d4) = 0x000250c0; // Post processing register
  *((volatile uint32_t *) 0x50500754) = 0xffffffff; // Mask and processor enables

  // Layer 17 quadrant 2
  *((volatile uint32_t *) 0x50900054) = 0x00000002; // Rows
  *((volatile uint32_t *) 0x509000d4) = 0x00000002; // Columns
  *((volatile uint32_t *) 0x50900354) = 0x00011fff; // SRAM write ptr
  *((volatile uint32_t *) 0x50900454) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900554) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x509005d4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a54) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50900654) = 0x13401438; // Mask offset and count
  *((volatile uint32_t *) 0x509007d4) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50900754) = 0xffffffff; // Mask and processor enables

  // Layer 17 quadrant 3
  *((volatile uint32_t *) 0x50d00054) = 0x00000002; // Rows
  *((volatile uint32_t *) 0x50d000d4) = 0x00000002; // Columns
  *((volatile uint32_t *) 0x50d00354) = 0x00011fff; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00454) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00554) = 0x00001400; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005d4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a54) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00654) = 0x13401438; // Mask offset and count
  *((volatile uint32_t *) 0x50d007d4) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50d00754) = 0xffffffff; // Mask and processor enables

  // Layer 18 quadrant 0
  *((volatile uint32_t *) 0x50100058) = 0x0000000e; // Rows
  *((volatile uint32_t *) 0x50100358) = 0x00000400; // SRAM write ptr
  *((volatile uint32_t *) 0x50100458) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100558) = 0x00001ff1; // SRAM read ptr
  *((volatile uint32_t *) 0x501005d8) = 0x0000cb20; // Layer control
  *((volatile uint32_t *) 0x50100a58) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50100658) = 0x3cc03db8; // Mask offset and count
  *((volatile uint32_t *) 0x50100158) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x501007d8) = 0x00022000; // Post processing register

  // Layer 18 quadrant 1
  *((volatile uint32_t *) 0x50500058) = 0x0000000e; // Rows
  *((volatile uint32_t *) 0x50500358) = 0x00000400; // SRAM write ptr
  *((volatile uint32_t *) 0x50500458) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500558) = 0x00001ff1; // SRAM read ptr
  *((volatile uint32_t *) 0x505005d8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a58) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50500658) = 0x3cc03db8; // Mask offset and count
  *((volatile uint32_t *) 0x50500158) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x505007d8) = 0x00022000; // Post processing register

  // Layer 18 quadrant 2
  *((volatile uint32_t *) 0x50900058) = 0x0000000e; // Rows
  *((volatile uint32_t *) 0x50900358) = 0x00000400; // SRAM write ptr
  *((volatile uint32_t *) 0x50900458) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900558) = 0x00001ff1; // SRAM read ptr
  *((volatile uint32_t *) 0x509005d8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a58) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50900658) = 0x3cc03db8; // Mask offset and count
  *((volatile uint32_t *) 0x50900158) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x509007d8) = 0x000230c0; // Post processing register
  *((volatile uint32_t *) 0x50900758) = 0xffffffff; // Mask and processor enables

  // Layer 18 quadrant 3
  *((volatile uint32_t *) 0x50d00058) = 0x0000000e; // Rows
  *((volatile uint32_t *) 0x50d00358) = 0x00000400; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00458) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00558) = 0x00001ff1; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005d8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a58) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00658) = 0x3cc03db8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00158) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d007d8) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00758) = 0xffffffff; // Mask and processor enables

  // Layer 19 quadrant 0
  *((volatile uint32_t *) 0x5010005c) = 0x0000000c; // Rows
  *((volatile uint32_t *) 0x5010035c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x5010045c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010055c) = 0x00000400; // SRAM read ptr
  *((volatile uint32_t *) 0x501005dc) = 0x0000ab20; // Layer control
  *((volatile uint32_t *) 0x50100a5c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5010065c) = 0x24702568; // Mask offset and count
  *((volatile uint32_t *) 0x5010015c) = 0x00001520; // 1D
  *((volatile uint32_t *) 0x501007dc) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x5010075c) = 0xffffffff; // Mask and processor enables

  // Layer 19 quadrant 1
  *((volatile uint32_t *) 0x5050005c) = 0x0000000c; // Rows
  *((volatile uint32_t *) 0x5050035c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x5050045c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050055c) = 0x00000400; // SRAM read ptr
  *((volatile uint32_t *) 0x505005dc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a5c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5050065c) = 0x24702568; // Mask offset and count
  *((volatile uint32_t *) 0x5050015c) = 0x00001520; // 1D
  *((volatile uint32_t *) 0x505007dc) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x5050075c) = 0xffffffff; // Mask and processor enables

  // Layer 19 quadrant 2
  *((volatile uint32_t *) 0x5090005c) = 0x0000000c; // Rows
  *((volatile uint32_t *) 0x5090035c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x5090045c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090055c) = 0x00000400; // SRAM read ptr
  *((volatile uint32_t *) 0x509005dc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a5c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5090065c) = 0x24702568; // Mask offset and count
  *((volatile uint32_t *) 0x5090015c) = 0x00001520; // 1D
  *((volatile uint32_t *) 0x509007dc) = 0x00024000; // Post processing register

  // Layer 19 quadrant 3
  *((volatile uint32_t *) 0x50d0005c) = 0x0000000c; // Rows
  *((volatile uint32_t *) 0x50d0035c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d0045c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0055c) = 0x00000400; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005dc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a5c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d0065c) = 0x24702568; // Mask offset and count
  *((volatile uint32_t *) 0x50d0015c) = 0x00001520; // 1D
  *((volatile uint32_t *) 0x50d007dc) = 0x000250c0; // Post processing register

  // Layer 20 quadrant 0
  *((volatile uint32_t *) 0x50100060) = 0x00000008; // Rows
  *((volatile uint32_t *) 0x50100460) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100560) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005e0) = 0x00012920; // Layer control
  *((volatile uint32_t *) 0x50100a60) = 0x00002000; // Layer control 2
  *((volatile uint32_t *) 0x50100660) = 0x14e01500; // Mask offset and count
  *((volatile uint32_t *) 0x50100160) = 0x00001900; // 1D
  *((volatile uint32_t *) 0x501007e0) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100760) = 0xffffffff; // Mask and processor enables

  // Layer 20 quadrant 1
  *((volatile uint32_t *) 0x50500060) = 0x00000008; // Rows
  *((volatile uint32_t *) 0x50500460) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500560) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005e0) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x50500a60) = 0x00002000; // Layer control 2
  *((volatile uint32_t *) 0x50500660) = 0x14e01500; // Mask offset and count
  *((volatile uint32_t *) 0x50500160) = 0x00001900; // 1D
  *((volatile uint32_t *) 0x505007e0) = 0x000230e0; // Post processing register
  *((volatile uint32_t *) 0x50500760) = 0xffffffff; // Mask and processor enables

  // Layer 20 quadrant 2
  *((volatile uint32_t *) 0x50900060) = 0x00000008; // Rows
  *((volatile uint32_t *) 0x50900460) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900560) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005e0) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x50900a60) = 0x00002000; // Layer control 2
  *((volatile uint32_t *) 0x50900660) = 0x14e01500; // Mask offset and count
  *((volatile uint32_t *) 0x50900160) = 0x00001900; // 1D
  *((volatile uint32_t *) 0x509007e0) = 0x00022000; // Post processing register

  // Layer 20 quadrant 3
  *((volatile uint32_t *) 0x50d00060) = 0x00000008; // Rows
  *((volatile uint32_t *) 0x50d00460) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00560) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005e0) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x50d00a60) = 0x00002000; // Layer control 2
  *((volatile uint32_t *) 0x50d00660) = 0x14e01500; // Mask offset and count
  *((volatile uint32_t *) 0x50d00160) = 0x00001900; // 1D
  *((volatile uint32_t *) 0x50d007e0) = 0x00022000; // Post processing register


  return CNN_OK;
}

int cnn_start(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) = 0x00100808; // Enable quadrant 0
  *((volatile uint32_t *) 0x50500000) = 0x00100809; // Enable quadrant 1
  *((volatile uint32_t *) 0x50900000) = 0x00100809; // Enable quadrant 2
  *((volatile uint32_t *) 0x50d00000) = 0x00100809; // Enable quadrant 3

#ifdef CNN_INFERENCE_TIMER
  MXC_TMR_SW_Start(CNN_INFERENCE_TIMER);
#endif

  CNN_START; // Allow capture of processing time
  *((volatile uint32_t *) 0x50100000) = 0x00100009; // Master enable quadrant 0

  return CNN_OK;
}

int cnn_unload(uint32_t *out_buf)
{
  volatile uint32_t *addr;

  // Custom unload for this network, layer 20 (tcn2): 32-bit data, shape: (5, 1, 1)
  addr = (volatile uint32_t *) 0x50400000;
  *out_buf++ = *addr++;
  *out_buf++ = *addr++;
  *out_buf++ = *addr++;
  *out_buf++ = *addr++;
  addr = (volatile uint32_t *) 0x50408000;
  *out_buf++ = *addr++;

  return CNN_OK;
}

int cnn_enable(uint32_t clock_source, uint32_t clock_divider)
{
  // Reset all domains, restore power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg1 = 0xf; // Mask memory
  MXC_GCFR->reg0 = 0xf; // Power
  MXC_GCFR->reg2 = 0x0; // Iso
  MXC_GCFR->reg3 = 0x0; // Reset

  MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                     | clock_divider | clock_source;
  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN); // Enable CNN clock

  MXC_NVIC_SetVector(CNN_IRQn, CNN_ISR); // Set CNN complete vector

  return CNN_OK;
}

int cnn_boost_enable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutSet(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_boost_disable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutClr(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_disable(void)
{
  // Disable CNN clock
  MXC_SYS_ClockDisable(MXC_SYS_PERIPH_CLOCK_CNN);

  // Disable power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg2 |= 0xf; // Iso
  MXC_GCFR->reg0 = 0x0; // Power
  MXC_GCFR->reg1 = 0x0; // Mask memory
  MXC_GCFR->reg3 = 0x0; // Reset

  return CNN_OK;
}

