var group__crypto__registers =
[
    [ "Register Offsets", "group___c_r_y_p_t_o___register___offsets.html", "group___c_r_y_p_t_o___register___offsets" ],
    [ "CRYPTO_CTRL", "group___c_r_y_p_t_o___c_t_r_l.html", "group___c_r_y_p_t_o___c_t_r_l" ],
    [ "CRYPTO_CIPHER_CTRL", "group___c_r_y_p_t_o___c_i_p_h_e_r___c_t_r_l.html", "group___c_r_y_p_t_o___c_i_p_h_e_r___c_t_r_l" ],
    [ "CRYPTO_HASH_CTRL", "group___c_r_y_p_t_o___h_a_s_h___c_t_r_l.html", "group___c_r_y_p_t_o___h_a_s_h___c_t_r_l" ],
    [ "CRYPTO_CRC_CTRL", "group___c_r_y_p_t_o___c_r_c___c_t_r_l.html", "group___c_r_y_p_t_o___c_r_c___c_t_r_l" ],
    [ "CRYPTO_DMA_SRC", "group___c_r_y_p_t_o___d_m_a___s_r_c.html", "group___c_r_y_p_t_o___d_m_a___s_r_c" ],
    [ "CRYPTO_DMA_DEST", "group___c_r_y_p_t_o___d_m_a___d_e_s_t.html", "group___c_r_y_p_t_o___d_m_a___d_e_s_t" ],
    [ "CRYPTO_DMA_CNT", "group___c_r_y_p_t_o___d_m_a___c_n_t.html", "group___c_r_y_p_t_o___d_m_a___c_n_t" ],
    [ "CRYPTO_MAA_CTRL", "group___c_r_y_p_t_o___m_a_a___c_t_r_l.html", "group___c_r_y_p_t_o___m_a_a___c_t_r_l" ],
    [ "CRYPTO_DIN", "group___c_r_y_p_t_o___d_i_n.html", "group___c_r_y_p_t_o___d_i_n" ],
    [ "CRYPTO_DOUT", "group___c_r_y_p_t_o___d_o_u_t.html", "group___c_r_y_p_t_o___d_o_u_t" ],
    [ "CRYPTO_CRC_POLY", "group___c_r_y_p_t_o___c_r_c___p_o_l_y.html", "group___c_r_y_p_t_o___c_r_c___p_o_l_y" ],
    [ "CRYPTO_CRC_VAL", "group___c_r_y_p_t_o___c_r_c___v_a_l.html", "group___c_r_y_p_t_o___c_r_c___v_a_l" ],
    [ "CRYPTO_CRC_PRNG", "group___c_r_y_p_t_o___c_r_c___p_r_n_g.html", "group___c_r_y_p_t_o___c_r_c___p_r_n_g" ],
    [ "CRYPTO_HAM_ECC", "group___c_r_y_p_t_o___h_a_m___e_c_c.html", "group___c_r_y_p_t_o___h_a_m___e_c_c" ],
    [ "CRYPTO_CIPHER_INIT", "group___c_r_y_p_t_o___c_i_p_h_e_r___i_n_i_t.html", "group___c_r_y_p_t_o___c_i_p_h_e_r___i_n_i_t" ],
    [ "CRYPTO_CIPHER_KEY", "group___c_r_y_p_t_o___c_i_p_h_e_r___k_e_y.html", "group___c_r_y_p_t_o___c_i_p_h_e_r___k_e_y" ],
    [ "CRYPTO_HASH_DIGEST", "group___c_r_y_p_t_o___h_a_s_h___d_i_g_e_s_t.html", "group___c_r_y_p_t_o___h_a_s_h___d_i_g_e_s_t" ],
    [ "CRYPTO_HASH_MSG_SZ", "group___c_r_y_p_t_o___h_a_s_h___m_s_g___s_z.html", "group___c_r_y_p_t_o___h_a_s_h___m_s_g___s_z" ],
    [ "CRYPTO_MAA_MAWS", "group___c_r_y_p_t_o___m_a_a___m_a_w_s.html", "group___c_r_y_p_t_o___m_a_a___m_a_w_s" ],
    [ "mxc_crypto_regs_t", "group__crypto__registers.html#structmxc__crypto__regs__t", [
      [ "cipher_ctrl", "group__crypto__registers.html#ac2afd62d12a270c7db8a7090f7f783ac", null ],
      [ "cipher_init", "group__crypto__registers.html#ab0a9cd31e9876264786d25a2fdf69c41", null ],
      [ "cipher_key", "group__crypto__registers.html#a785e6822a015300103dc4e9e4248480c", null ],
      [ "crc_ctrl", "group__crypto__registers.html#a116e20263f4e37b2de139dbb8d3c4374", null ],
      [ "crc_poly", "group__crypto__registers.html#a246835946902ef53647e6f0e33612788", null ],
      [ "crc_prng", "group__crypto__registers.html#a7f78d0a4efa9fb019a0c1d5eb49f39af", null ],
      [ "crc_val", "group__crypto__registers.html#a3aa1e114f572bce143167b2b2f64a267", null ],
      [ "ctrl", "group__crypto__registers.html#a5f3ab705a4a67b17dcc04560cef193f3", null ],
      [ "din", "group__crypto__registers.html#ac0cfce503ea540c0cfc31ab4c9724a29", null ],
      [ "dma_cnt", "group__crypto__registers.html#a4b2f4c201d54bcb8150a141789bdf022", null ],
      [ "dma_dest", "group__crypto__registers.html#a42724774a6f9928233a4469515b58374", null ],
      [ "dma_src", "group__crypto__registers.html#a602e02e60799eaf0b02e55b4481bf32c", null ],
      [ "dout", "group__crypto__registers.html#acbf23bc1499dfff7c18d18c779389b51", null ],
      [ "ham_ecc", "group__crypto__registers.html#ac699beaeeed2c55ca58b352b2fafdf87", null ],
      [ "hash_ctrl", "group__crypto__registers.html#aa347553b1bbc7d4265c194d73f408f3b", null ],
      [ "hash_digest", "group__crypto__registers.html#a7d1fd61e8572bdb0073455b3d324eee6", null ],
      [ "hash_msg_sz", "group__crypto__registers.html#aca985e364705cabb381dc54db55cfd98", null ],
      [ "maa_ctrl", "group__crypto__registers.html#afd17b9508eb5f17d19468507275bbab2", null ],
      [ "maa_maws", "group__crypto__registers.html#a0c681b18c7d76a83a17358e70e0d62a3", null ]
    ] ]
];