var modules =
[
    [ "Analog Digital Converter (ADC)", "group__adc.html", "group__adc" ],
    [ "Color LCD (CLCD)", "group__clcd.html", "group__clcd" ],
    [ "Direct Memory Access (DMA)", "group__dma.html", "group__dma" ],
    [ "External Memory Cache Controller (EMCC)", "group__emcc.html", "group__emcc" ],
    [ "Flash Controller", "group__flc.html", "group__flc" ],
    [ "General-Purpose Input/Output (GPIO)", "group__gpio.html", "group__gpio" ],
    [ "HyperBus (HPB)", "group__hpb.html", "group__hpb" ],
    [ "I2C", "group__i2c.html", "group__i2c" ],
    [ "SPIMSS", "group__spimss.html", "group__spimss" ],
    [ "Internal Cache Controller (ICC)", "group__icc.html", "group__icc" ],
    [ "Low Power (LP)", "group__pwrseq.html", "group__pwrseq" ],
    [ "Memory Utility Functions", "group__mem__utils.html", "group__mem__utils" ],
    [ "Assertion Checks for Debugging", "group__mxc__assertions.html", "group__mxc__assertions" ],
    [ "Delay Utility Functions", "group___m_x_c__delay.html", "group___m_x_c__delay" ],
    [ "Error Codes", "group___m_x_c___error___codes.html", "group___m_x_c___error___codes" ],
    [ "Exclusive Access Locks", "group__mxc__lock__utilities.html", "group__mxc__lock__utilities" ],
    [ "System Configuration (MXC_SYS)", "group__mxc__sys.html", "group__mxc__sys" ],
    [ "NVIC Table", "group__nvic.html", "group__nvic" ],
    [ "1-Wire Master (OWM)", "group__owm.html", "group__owm" ],
    [ "Pulse Train Engine", "group__pt.html", "group__pt" ],
    [ "RTC", "group__rtc.html", "group__rtc" ],
    [ "Secure Digital High Capacity(SDHC)", "group__sdhc.html", "group__sdhc" ],
    [ "Semaphore (SEMA)", "group__sema.html", "group__sema" ],
    [ "SPI", "group__spi.html", "group__spi" ],
    [ "SPI External Flash (SPIXF)", "group__spixf.html", "group__spixf" ],
    [ "SPI External Ram (SPIXR)", "group__spixr.html", "group__spixr" ],
    [ "Timer (TMR)", "group__tmr.html", "group__tmr" ],
    [ "TPU", "group__tpu.html", "group__tpu" ],
    [ "TRNG", "group__trng.html", "group__trng" ],
    [ "UART", "group__uart.html", "group__uart" ],
    [ "Watchdog Timer (WDT)", "group__wdt.html", "group__wdt" ],
    [ "AES_KEY_Registers", "group__aes__key__registers.html", "group__aes__key__registers" ],
    [ "AESKEYS_Registers", "group__aeskeys__registers.html", "group__aeskeys__registers" ],
    [ "BBFC_Registers", "group__bbfc__registers.html", "group__bbfc__registers" ],
    [ "GCR_Registers", "group__gcr__registers.html", "group__gcr__registers" ],
    [ "NBBFC_Registers", "group__nbbfc__registers.html", "group__nbbfc__registers" ],
    [ "PTG_Registers", "group__ptg__registers.html", "group__ptg__registers" ],
    [ "SDMA_Registers", "group__sdma__registers.html", "group__sdma__registers" ],
    [ "SIR_Registers", "group__sir__registers.html", "group__sir__registers" ],
    [ "SMON_Registers", "group__smon__registers.html", "group__smon__registers" ],
    [ "SPIXFC_FIFO_Registers", "group__spixfc__fifo__registers.html", "group__spixfc__fifo__registers" ],
    [ "SPIXFC_Registers", "group__spixfc__registers.html", "group__spixfc__registers" ],
    [ "TRIMSIR_Registers", "group__trimsir__registers.html", "group__trimsir__registers" ],
    [ "USBHS_Registers", "group__usbhs__registers.html", "group__usbhs__registers" ]
];