# An example of a trigger service.
# This can be used for testing but a semantically meaningful
# one should be created to be built upon.

---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages.
