var searchData=
[
  ['sir_5fregisters_4323',['SIR_Registers',['../group__sir__registers.html',1,'']]],
  ['sir_5fsir_5faddr_4324',['SIR_SIR_ADDR',['../group___s_i_r___s_i_r___a_d_d_r.html',1,'']]],
  ['sir_5fsir_5fstatus_4325',['SIR_SIR_STATUS',['../group___s_i_r___s_i_r___s_t_a_t_u_s.html',1,'']]],
  ['spi_4326',['SPI',['../group__spi.html',1,'']]],
  ['spi_5fclkctrl_4327',['SPI_CLKCTRL',['../group___s_p_i___c_l_k_c_t_r_l.html',1,'']]],
  ['spi_5fctrl0_4328',['SPI_CTRL0',['../group___s_p_i___c_t_r_l0.html',1,'']]],
  ['spi_5fctrl1_4329',['SPI_CTRL1',['../group___s_p_i___c_t_r_l1.html',1,'']]],
  ['spi_5fctrl2_4330',['SPI_CTRL2',['../group___s_p_i___c_t_r_l2.html',1,'']]],
  ['spi_5fdma_4331',['SPI_DMA',['../group___s_p_i___d_m_a.html',1,'']]],
  ['spi_5ffifo16_4332',['SPI_FIFO16',['../group___s_p_i___f_i_f_o16.html',1,'']]],
  ['spi_5ffifo32_4333',['SPI_FIFO32',['../group___s_p_i___f_i_f_o32.html',1,'']]],
  ['spi_5ffifo8_4334',['SPI_FIFO8',['../group___s_p_i___f_i_f_o8.html',1,'']]],
  ['spi_5finten_4335',['SPI_INTEN',['../group___s_p_i___i_n_t_e_n.html',1,'']]],
  ['spi_5fintfl_4336',['SPI_INTFL',['../group___s_p_i___i_n_t_f_l.html',1,'']]],
  ['spi_5fregisters_4337',['SPI_Registers',['../group__spi__registers.html',1,'']]],
  ['spi_5fsstime_4338',['SPI_SSTIME',['../group___s_p_i___s_s_t_i_m_e.html',1,'']]],
  ['spi_5fstat_4339',['SPI_STAT',['../group___s_p_i___s_t_a_t.html',1,'']]],
  ['spi_5fwken_4340',['SPI_WKEN',['../group___s_p_i___w_k_e_n.html',1,'']]],
  ['spi_5fwkfl_4341',['SPI_WKFL',['../group___s_p_i___w_k_f_l.html',1,'']]]
];
