/**
 * @file        main.c
 * @brief      True Random Number Generator (TRNG) example
 * @details
 */

/******************************************************************************
 *
 * Copyright (C) 2022-2023 Maxim Integrated Products, Inc. All Rights Reserved.
 * (now owned by Analog Devices, Inc.),
 * Copyright (C) 2023 Analog Devices, Inc. All Rights Reserved. This software
 * is proprietary to Analog Devices, Inc. and its licensors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "max32672.h"
#include "nvic_table.h"
#include "trng.h"

#define NUM_RND_BYTES 20

volatile int done;
volatile int callback_result;

/***** Globals *****/
uint8_t var_rnd_no[NUM_RND_BYTES] = { 0 };

void TRNG_IRQHandler(void)
{
    MXC_TRNG_Handler();
}

void trng_cb(void *req, int result)
{
    done = 1;
    callback_result = result;
}

void print_rnd_data(char *rnd_data)
{
    // Print four bytes per line
    for (int i = 0; i < NUM_RND_BYTES; ++i) {
        printf("0x%02x ", rnd_data[i]);

        if (i % 4 == 3) {
            printf("\n"); // Start new line after fourth byte
        }
    }

    return;
}

void Test_TRNG(int asynchronous)
{
    printf(asynchronous ? "\nTest TRNG Async\n" : "\nTest TRNG Sync\n");

    // Initialize data array
    memset(var_rnd_no, 0, sizeof(var_rnd_no));

    // Initialize TRNG
    MXC_TRNG_Init();

    if (asynchronous) {
        // Do asynchronous TRNG generation
        done = 0;
        NVIC_EnableIRQ(TRNG_IRQn);
        MXC_TRNG_RandomAsync(var_rnd_no, NUM_RND_BYTES, &trng_cb);

        while (!done) {} //Wait for result
    } else {
        // Do blocking TRNG generation
        MXC_TRNG_Random(var_rnd_no, NUM_RND_BYTES);
    }

    // Print TRNG generated bytes to terminal
    print_rnd_data((char *)var_rnd_no);

    MXC_TRNG_Shutdown();
}

int main(void)
{
    printf("\n\n********** TRNG Example **********\n");

    // Test blocking TRNG Generation
    Test_TRNG(0);

    // Test Asynchronus TRNG Generation
    Test_TRNG(1);

    printf("\n********** Test Complete **********\n");

    return 0;
}
