# Examples

The MSDK contains examples for each microcontroller that demonstrate the usage of its [Peripheral APIs](#peripheral-driver-api) and other supported libraries. They can be found in the `Examples` folder of an MSDK installation.

![Figure 40](res/Fig40.jpg)

???+ warning "**⚠️ Copying Examples**"
    It's strongly recommended to copy example projects to an _outside_ folder before modifying them.  This keeps the MSDK's "source" copy preserved for reference.  Project folders must be copied to a location _without_ any spaces in its filepath.

Each example contains a `README.md` file describing what it does. In general, there is at least one example per peripheral block, and the example's name will indicate what it matches (i.e., `DMA`, `ADC`, `SPI`).

The tables below are offered to facilitate easier browsing through the MSDK examples.  They are autogenerated from the available projects for each microcontroller.  A link to the example's source code on Github is available, as well as its location inside of the MSDK.

<!-- Note for maintainers: The autogeneration is handled in "Documentation/build.py" -->
{{EXAMPLES_LIST}}
