/*******************************************************************************
* Copyright (C) 2019-2023 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// facedet_tinierssd
// This file was @generated by ai8xize.py --test-dir sdk/Examples/MAX78000/CNN --prefix facedet_tinierssd --checkpoint-file trained/ai85-facedet-tinierssd-qat8-q.pth.tar --config-file networks/ai85-facedet-tinierssd.yaml --sample-input tests/sample_vggface2_facedetection.npy --fifo --device MAX78000 --timer 0 --display-checkpoint --verbose

// DO NOT EDIT - regenerate this file instead!

// Configuring 16 layers
// Input data: HWC
// Layer 0: 3x224x168 streaming, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 16x112x84 output
// Layer 1: 16x112x84 streaming, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x56x42 output
// Layer 2: 32x56x42, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x56x42 output
// Layer 3: 64x56x42, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x56x42 output
// Layer 4: 64x56x42, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x56x42 output
// Layer 5: 64x56x42, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x56x42 output
// Layer 6: 64x56x42, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 128x56x42 output
// Layer 7: 128x56x42, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x56x42 output
// Layer 8: 32x56x42, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x28x21 output
// Layer 9: 32x28x21, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x14x10 output
// Layer 10: 32x14x10, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 16x14x10 output
// Layer 11: 16x14x10, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 16x7x5 output
// Layer 12: 32x28x21, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, no activation, 8x28x21 output
// Layer 13: 16x7x5, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, no activation, 8x7x5 output
// Layer 14: 32x28x21, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, no activation, 4x28x21 output
// Layer 15: 16x7x5, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, no activation, 4x7x5 output

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "cnn.h"
#include "weights.h"

void CNN_ISR(void)
{
  // Acknowledge interrupt to all quadrants
  *((volatile uint32_t *) 0x50100000) &= ~((1<<12) | (1<<14) | 1);
  *((volatile uint32_t *) 0x50500000) &= ~((1<<12) | (1<<14) | 1);
  *((volatile uint32_t *) 0x50900000) &= ~((1<<12) | (1<<14) | 1);
  *((volatile uint32_t *) 0x50d00000) &= ~((1<<12) | (1<<14) | 1);

//   CNN_COMPLETE; // Signal that processing is complete
#ifdef CNN_INFERENCE_TIMER
  cnn_time = MXC_TMR_SW_Stop(CNN_INFERENCE_TIMER);
#else
  cnn_time = 1;
#endif
}

int cnn_continue(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) |= 1; // Re-enable quadrant 0

  return CNN_OK;
}

int cnn_stop(void)
{
  *((volatile uint32_t *) 0x50100000) &= ~1; // Disable quadrant 0

  return CNN_OK;
}

void memcpy32(uint32_t *dst, const uint32_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

static const uint32_t kernels[] = KERNELS;

int cnn_load_weights(void)
{
  uint32_t len;
  volatile uint32_t *addr;
  const uint32_t *ptr = kernels;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    *((volatile uint8_t *) ((uint32_t) addr | 1)) = 0x01; // Set address
    len = *ptr++;
    while (len-- > 0)
      *addr++ = *ptr++;
  }

  return CNN_OK;
}

static const uint8_t bias_0[] = BIAS_0;
static const uint8_t bias_1[] = BIAS_1;
static const uint8_t bias_2[] = BIAS_2;
static const uint8_t bias_3[] = BIAS_3;

static void memcpy_8to32(uint32_t *dst, const uint8_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

int cnn_load_bias(void)
{
  memcpy_8to32((uint32_t *) 0x50108000, bias_0, sizeof(uint8_t) * 136);
  memcpy_8to32((uint32_t *) 0x50508000, bias_1, sizeof(uint8_t) * 136);
  memcpy_8to32((uint32_t *) 0x50908000, bias_2, sizeof(uint8_t) * 132);
  memcpy_8to32((uint32_t *) 0x50d08000, bias_3, sizeof(uint8_t) * 132);

  return CNN_OK;
}

int cnn_init(void)
{
  *((volatile uint32_t *) 0x50001000) = 0x00000000; // AON control
  *((volatile uint32_t *) 0x50100000) = 0x00108008; // Stop SM
  *((volatile uint32_t *) 0x50100004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50100008) = 0x0000000f; // Layer count
  *((volatile uint32_t *) 0x50500000) = 0x00108008; // Stop SM
  *((volatile uint32_t *) 0x50500004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50500008) = 0x0000000f; // Layer count
  *((volatile uint32_t *) 0x50900000) = 0x00108008; // Stop SM
  *((volatile uint32_t *) 0x50900004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50900008) = 0x0000000f; // Layer count
  *((volatile uint32_t *) 0x50d00000) = 0x00108008; // Stop SM
  *((volatile uint32_t *) 0x50d00004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50d00008) = 0x0000000f; // Layer count

  return CNN_OK;
}

int cnn_configure(void)
{
  // Layer 0 quadrant 0
  *((volatile uint32_t *) 0x50100010) = 0x000100e1; // Rows
  *((volatile uint32_t *) 0x50100090) = 0x000100a9; // Columns
  *((volatile uint32_t *) 0x50100190) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100210) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50100290) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100310) = 0x00008800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100590) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50100a10) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100610) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50100690) = 0x00000053; // TRAM ptr max
  *((volatile uint32_t *) 0x50100710) = 0x00070007; // Mask and processor enables
  *((volatile uint32_t *) 0x50100810) = 0x00000154; // Stream processing start
  *((volatile uint32_t *) 0x50100890) = 0x00a80010; // Stream processing delta
  *((volatile uint32_t *) 0x50100910) = 0x000001fe; // Rollover
  *((volatile uint32_t *) 0x50100990) = 0x00009300; // Input frame size

  // Layer 0 quadrant 1
  *((volatile uint32_t *) 0x50500010) = 0x000100e1; // Rows
  *((volatile uint32_t *) 0x50500090) = 0x000100a9; // Columns
  *((volatile uint32_t *) 0x50500190) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500210) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50500290) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500310) = 0x00008800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500590) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a10) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500610) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50500690) = 0x00000053; // TRAM ptr max
  *((volatile uint32_t *) 0x50500810) = 0x00000154; // Stream processing start
  *((volatile uint32_t *) 0x50500890) = 0x00a80010; // Stream processing delta
  *((volatile uint32_t *) 0x50500910) = 0x000001fe; // Rollover
  *((volatile uint32_t *) 0x50500990) = 0x00009300; // Input frame size

  // Layer 0 quadrant 2
  *((volatile uint32_t *) 0x50900010) = 0x000100e1; // Rows
  *((volatile uint32_t *) 0x50900090) = 0x000100a9; // Columns
  *((volatile uint32_t *) 0x50900190) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900210) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50900290) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900310) = 0x00008800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900590) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a10) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900610) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50900690) = 0x00000053; // TRAM ptr max
  *((volatile uint32_t *) 0x50900810) = 0x00000154; // Stream processing start
  *((volatile uint32_t *) 0x50900890) = 0x00a80010; // Stream processing delta
  *((volatile uint32_t *) 0x50900910) = 0x000001fe; // Rollover
  *((volatile uint32_t *) 0x50900990) = 0x00009300; // Input frame size

  // Layer 0 quadrant 3
  *((volatile uint32_t *) 0x50d00010) = 0x000100e1; // Rows
  *((volatile uint32_t *) 0x50d00090) = 0x000100a9; // Columns
  *((volatile uint32_t *) 0x50d00190) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00210) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d00290) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00310) = 0x00008800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00590) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a10) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00610) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50d00690) = 0x00000053; // TRAM ptr max
  *((volatile uint32_t *) 0x50d00810) = 0x00000154; // Stream processing start
  *((volatile uint32_t *) 0x50d00890) = 0x00a80010; // Stream processing delta
  *((volatile uint32_t *) 0x50d00910) = 0x000001fe; // Rollover
  *((volatile uint32_t *) 0x50d00990) = 0x00009300; // Input frame size

  // Layer 1 quadrant 0
  *((volatile uint32_t *) 0x50100014) = 0x00010071; // Rows
  *((volatile uint32_t *) 0x50100094) = 0x00010055; // Columns
  *((volatile uint32_t *) 0x50100194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100214) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50100294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100314) = 0x00011000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50100594) = 0x00002ba0; // Layer control
  *((volatile uint32_t *) 0x50100a14) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50100614) = 0x000000f8; // Mask offset and count
  *((volatile uint32_t *) 0x50100694) = 0x0054007d; // TRAM ptr max
  *((volatile uint32_t *) 0x50100794) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50100814) = 0x00000108; // Stream processing start
  *((volatile uint32_t *) 0x50100894) = 0x00580021; // Stream processing delta
  *((volatile uint32_t *) 0x50100914) = 0x0000015e; // Rollover

  // Layer 1 quadrant 1
  *((volatile uint32_t *) 0x50500014) = 0x00010071; // Rows
  *((volatile uint32_t *) 0x50500094) = 0x00010055; // Columns
  *((volatile uint32_t *) 0x50500194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500214) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50500294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500314) = 0x00011000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50500594) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a14) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50500614) = 0x000000f8; // Mask offset and count
  *((volatile uint32_t *) 0x50500694) = 0x0054007d; // TRAM ptr max
  *((volatile uint32_t *) 0x50500794) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50500714) = 0xffffffff; // Mask and processor enables
  *((volatile uint32_t *) 0x50500814) = 0x00000108; // Stream processing start
  *((volatile uint32_t *) 0x50500894) = 0x00580021; // Stream processing delta
  *((volatile uint32_t *) 0x50500914) = 0x0000015e; // Rollover

  // Layer 1 quadrant 2
  *((volatile uint32_t *) 0x50900014) = 0x00010071; // Rows
  *((volatile uint32_t *) 0x50900094) = 0x00010055; // Columns
  *((volatile uint32_t *) 0x50900194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900214) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50900294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900314) = 0x00011000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50900594) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a14) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50900614) = 0x000000f8; // Mask offset and count
  *((volatile uint32_t *) 0x50900694) = 0x0054007d; // TRAM ptr max
  *((volatile uint32_t *) 0x50900794) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50900814) = 0x00000108; // Stream processing start
  *((volatile uint32_t *) 0x50900894) = 0x00580021; // Stream processing delta
  *((volatile uint32_t *) 0x50900914) = 0x0000015e; // Rollover

  // Layer 1 quadrant 3
  *((volatile uint32_t *) 0x50d00014) = 0x00010071; // Rows
  *((volatile uint32_t *) 0x50d00094) = 0x00010055; // Columns
  *((volatile uint32_t *) 0x50d00194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00214) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d00294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00314) = 0x00011000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d00594) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a14) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00614) = 0x000000f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00694) = 0x0054007d; // TRAM ptr max
  *((volatile uint32_t *) 0x50d00794) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50d00814) = 0x00000108; // Stream processing start
  *((volatile uint32_t *) 0x50d00894) = 0x00580021; // Stream processing delta
  *((volatile uint32_t *) 0x50d00914) = 0x0000015e; // Rollover

  // Layer 2 quadrant 0
  *((volatile uint32_t *) 0x50100018) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x50100098) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50100318) = 0x00000c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50100418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100518) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50100598) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a18) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100618) = 0x000001f8; // Mask offset and count
  *((volatile uint32_t *) 0x50100698) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x50100798) = 0x00026000; // Post processing register

  // Layer 2 quadrant 1
  *((volatile uint32_t *) 0x50500018) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x50500098) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50500318) = 0x00000c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50500418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500518) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50500598) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a18) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500618) = 0x000001f8; // Mask offset and count
  *((volatile uint32_t *) 0x50500698) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x50500798) = 0x00027000; // Post processing register

  // Layer 2 quadrant 2
  *((volatile uint32_t *) 0x50900018) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x50900098) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50900318) = 0x00000c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50900418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900518) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50900598) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a18) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900618) = 0x000001f8; // Mask offset and count
  *((volatile uint32_t *) 0x50900698) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x50900798) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50900718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 3
  *((volatile uint32_t *) 0x50d00018) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x50d00098) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50d00318) = 0x00000c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00518) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d00598) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a18) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00618) = 0x000001f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00698) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x50d00798) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50d00718) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 0
  *((volatile uint32_t *) 0x5010001c) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x5010009c) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x5010041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010051c) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x5010059c) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a1c) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x5010061c) = 0x020003f8; // Mask offset and count
  *((volatile uint32_t *) 0x5010069c) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x5010079c) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x5010071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 1
  *((volatile uint32_t *) 0x5050001c) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x5050009c) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x5050041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050051c) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x5050059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a1c) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x5050061c) = 0x020003f8; // Mask offset and count
  *((volatile uint32_t *) 0x5050069c) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x5050079c) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x5050071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 2
  *((volatile uint32_t *) 0x5090001c) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x5090009c) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x5090041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090051c) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x5090059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a1c) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x5090061c) = 0x020003f8; // Mask offset and count
  *((volatile uint32_t *) 0x5090069c) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x5090079c) = 0x00027000; // Post processing register
  *((volatile uint32_t *) 0x5090071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 3
  *((volatile uint32_t *) 0x50d0001c) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x50d0009c) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50d0041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0051c) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x50d0059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a1c) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d0061c) = 0x020003f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d0069c) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x50d0079c) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50d0071c) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 0
  *((volatile uint32_t *) 0x50100020) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x501000a0) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50100320) = 0x00000c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50100420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a0) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a20) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100620) = 0x040005f8; // Mask offset and count
  *((volatile uint32_t *) 0x501006a0) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x501007a0) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50100720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 1
  *((volatile uint32_t *) 0x50500020) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x505000a0) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50500320) = 0x00000c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50500420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a20) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500620) = 0x040005f8; // Mask offset and count
  *((volatile uint32_t *) 0x505006a0) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x505007a0) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50500720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 2
  *((volatile uint32_t *) 0x50900020) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x509000a0) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50900320) = 0x00000c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50900420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a20) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900620) = 0x040005f8; // Mask offset and count
  *((volatile uint32_t *) 0x509006a0) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x509007a0) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50900720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 3
  *((volatile uint32_t *) 0x50d00020) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x50d000a0) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50d00320) = 0x00000c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a20) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00620) = 0x040005f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006a0) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007a0) = 0x00027000; // Post processing register
  *((volatile uint32_t *) 0x50d00720) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 0
  *((volatile uint32_t *) 0x50100024) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x501000a4) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50100424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100524) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x501005a4) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a24) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100624) = 0x060007f8; // Mask offset and count
  *((volatile uint32_t *) 0x501006a4) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x501007a4) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50100724) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 1
  *((volatile uint32_t *) 0x50500024) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x505000a4) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50500424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500524) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x505005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a24) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500624) = 0x060007f8; // Mask offset and count
  *((volatile uint32_t *) 0x505006a4) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x505007a4) = 0x00027040; // Post processing register
  *((volatile uint32_t *) 0x50500724) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 2
  *((volatile uint32_t *) 0x50900024) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x509000a4) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50900424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900524) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x509005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a24) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900624) = 0x060007f8; // Mask offset and count
  *((volatile uint32_t *) 0x509006a4) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x509007a4) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50900724) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 3
  *((volatile uint32_t *) 0x50d00024) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x50d000a4) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50d00424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00524) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a24) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00624) = 0x060007f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006a4) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007a4) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50d00724) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 0
  *((volatile uint32_t *) 0x50100028) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x501000a8) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50100328) = 0x00000c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50100428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501004a8) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x501005a8) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a28) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100628) = 0x08000bf8; // Mask offset and count
  *((volatile uint32_t *) 0x501006a8) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x501007a8) = 0x00027000; // Post processing register
  *((volatile uint32_t *) 0x50100728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 1
  *((volatile uint32_t *) 0x50500028) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x505000a8) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50500328) = 0x00000c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50500428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505004a8) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x505005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a28) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500628) = 0x08000bf8; // Mask offset and count
  *((volatile uint32_t *) 0x505006a8) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x505007a8) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50500728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 2
  *((volatile uint32_t *) 0x50900028) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x509000a8) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50900328) = 0x00000c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50900428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509004a8) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x509005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a28) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900628) = 0x08000bf8; // Mask offset and count
  *((volatile uint32_t *) 0x509006a8) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x509007a8) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50900728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 3
  *((volatile uint32_t *) 0x50d00028) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x50d000a8) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50d00328) = 0x00000c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d004a8) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50d005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a28) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00628) = 0x08000bf8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006a8) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007a8) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50d00728) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 0
  *((volatile uint32_t *) 0x5010002c) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x501000ac) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x5010042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010052c) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x501005ac) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a2c) = 0x0000f801; // Layer control 2
  *((volatile uint32_t *) 0x5010062c) = 0x0c000df8; // Mask offset and count
  *((volatile uint32_t *) 0x501006ac) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x501007ac) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x5010072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 1
  *((volatile uint32_t *) 0x5050002c) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x505000ac) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x5050042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050052c) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x505005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a2c) = 0x0000f801; // Layer control 2
  *((volatile uint32_t *) 0x5050062c) = 0x0c000df8; // Mask offset and count
  *((volatile uint32_t *) 0x505006ac) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x505007ac) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x5050072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 2
  *((volatile uint32_t *) 0x5090002c) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x509000ac) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x5090042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090052c) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x509005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a2c) = 0x0000f801; // Layer control 2
  *((volatile uint32_t *) 0x5090062c) = 0x0c000df8; // Mask offset and count
  *((volatile uint32_t *) 0x509006ac) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x509007ac) = 0x00027040; // Post processing register
  *((volatile uint32_t *) 0x5090072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 3
  *((volatile uint32_t *) 0x50d0002c) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x50d000ac) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50d0042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0052c) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a2c) = 0x0000f801; // Layer control 2
  *((volatile uint32_t *) 0x50d0062c) = 0x0c000df8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006ac) = 0x00000029; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007ac) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50d0072c) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 0
  *((volatile uint32_t *) 0x50100030) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x501000b0) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x501001b0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100230) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x501002b0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100330) = 0x00010c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50100430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005b0) = 0x0000aba0; // Layer control
  *((volatile uint32_t *) 0x50100a30) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50100630) = 0x010001f8; // Mask offset and count
  *((volatile uint32_t *) 0x501006b0) = 0x00000014; // TRAM ptr max
  *((volatile uint32_t *) 0x501007b0) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50100730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 1
  *((volatile uint32_t *) 0x50500030) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x505000b0) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x505001b0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500230) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x505002b0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500330) = 0x00010c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50500430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005b0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a30) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50500630) = 0x010001f8; // Mask offset and count
  *((volatile uint32_t *) 0x505006b0) = 0x00000014; // TRAM ptr max
  *((volatile uint32_t *) 0x505007b0) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50500730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 2
  *((volatile uint32_t *) 0x50900030) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x509000b0) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x509001b0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900230) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x509002b0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900330) = 0x00010c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50900430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005b0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a30) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50900630) = 0x010001f8; // Mask offset and count
  *((volatile uint32_t *) 0x509006b0) = 0x00000014; // TRAM ptr max
  *((volatile uint32_t *) 0x509007b0) = 0x00024000; // Post processing register

  // Layer 8 quadrant 3
  *((volatile uint32_t *) 0x50d00030) = 0x00010039; // Rows
  *((volatile uint32_t *) 0x50d000b0) = 0x0001002b; // Columns
  *((volatile uint32_t *) 0x50d001b0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00230) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d002b0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00330) = 0x00010c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005b0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a30) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00630) = 0x010001f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006b0) = 0x00000014; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007b0) = 0x00025040; // Post processing register

  // Layer 9 quadrant 0
  *((volatile uint32_t *) 0x50100034) = 0x0001001d; // Rows
  *((volatile uint32_t *) 0x501000b4) = 0x00010016; // Columns
  *((volatile uint32_t *) 0x501001b4) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100234) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x501002b4) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100334) = 0x0001079c; // SRAM write ptr
  *((volatile uint32_t *) 0x50100434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100534) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x501005b4) = 0x0000cba0; // Layer control
  *((volatile uint32_t *) 0x50100a34) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50100634) = 0x0e000ef8; // Mask offset and count
  *((volatile uint32_t *) 0x501006b4) = 0x00000009; // TRAM ptr max
  *((volatile uint32_t *) 0x501007b4) = 0x00028000; // Post processing register

  // Layer 9 quadrant 1
  *((volatile uint32_t *) 0x50500034) = 0x0001001d; // Rows
  *((volatile uint32_t *) 0x505000b4) = 0x00010016; // Columns
  *((volatile uint32_t *) 0x505001b4) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500234) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x505002b4) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500334) = 0x0001079c; // SRAM write ptr
  *((volatile uint32_t *) 0x50500434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500534) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x505005b4) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a34) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50500634) = 0x0e000ef8; // Mask offset and count
  *((volatile uint32_t *) 0x505006b4) = 0x00000009; // TRAM ptr max
  *((volatile uint32_t *) 0x505007b4) = 0x00028000; // Post processing register

  // Layer 9 quadrant 2
  *((volatile uint32_t *) 0x50900034) = 0x0001001d; // Rows
  *((volatile uint32_t *) 0x509000b4) = 0x00010016; // Columns
  *((volatile uint32_t *) 0x509001b4) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900234) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x509002b4) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900334) = 0x0001079c; // SRAM write ptr
  *((volatile uint32_t *) 0x50900434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900534) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x509005b4) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a34) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50900634) = 0x0e000ef8; // Mask offset and count
  *((volatile uint32_t *) 0x509006b4) = 0x00000009; // TRAM ptr max
  *((volatile uint32_t *) 0x509007b4) = 0x00029060; // Post processing register
  *((volatile uint32_t *) 0x50900734) = 0xffffffff; // Mask and processor enables

  // Layer 9 quadrant 3
  *((volatile uint32_t *) 0x50d00034) = 0x0001001d; // Rows
  *((volatile uint32_t *) 0x50d000b4) = 0x00010016; // Columns
  *((volatile uint32_t *) 0x50d001b4) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00234) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d002b4) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00334) = 0x0001079c; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00534) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005b4) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a34) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00634) = 0x0e000ef8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006b4) = 0x00000009; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007b4) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50d00734) = 0xffffffff; // Mask and processor enables

  // Layer 10 quadrant 0
  *((volatile uint32_t *) 0x50100038) = 0x0001000f; // Rows
  *((volatile uint32_t *) 0x501000b8) = 0x0001000b; // Columns
  *((volatile uint32_t *) 0x50100338) = 0x00018020; // SRAM write ptr
  *((volatile uint32_t *) 0x50100438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100538) = 0x0000079c; // SRAM read ptr
  *((volatile uint32_t *) 0x501005b8) = 0x0000cb20; // Layer control
  *((volatile uint32_t *) 0x50100a38) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100638) = 0x0f000f78; // Mask offset and count
  *((volatile uint32_t *) 0x501006b8) = 0x00000009; // TRAM ptr max
  *((volatile uint32_t *) 0x501007b8) = 0x00026000; // Post processing register

  // Layer 10 quadrant 1
  *((volatile uint32_t *) 0x50500038) = 0x0001000f; // Rows
  *((volatile uint32_t *) 0x505000b8) = 0x0001000b; // Columns
  *((volatile uint32_t *) 0x50500338) = 0x00018020; // SRAM write ptr
  *((volatile uint32_t *) 0x50500438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500538) = 0x0000079c; // SRAM read ptr
  *((volatile uint32_t *) 0x505005b8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a38) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500638) = 0x0f000f78; // Mask offset and count
  *((volatile uint32_t *) 0x505006b8) = 0x00000009; // TRAM ptr max
  *((volatile uint32_t *) 0x505007b8) = 0x00026000; // Post processing register

  // Layer 10 quadrant 2
  *((volatile uint32_t *) 0x50900038) = 0x0001000f; // Rows
  *((volatile uint32_t *) 0x509000b8) = 0x0001000b; // Columns
  *((volatile uint32_t *) 0x50900338) = 0x00018020; // SRAM write ptr
  *((volatile uint32_t *) 0x50900438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900538) = 0x0000079c; // SRAM read ptr
  *((volatile uint32_t *) 0x509005b8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a38) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900638) = 0x0f000f78; // Mask offset and count
  *((volatile uint32_t *) 0x509006b8) = 0x00000009; // TRAM ptr max
  *((volatile uint32_t *) 0x509007b8) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50900738) = 0xffffffff; // Mask and processor enables

  // Layer 10 quadrant 3
  *((volatile uint32_t *) 0x50d00038) = 0x0001000f; // Rows
  *((volatile uint32_t *) 0x50d000b8) = 0x0001000b; // Columns
  *((volatile uint32_t *) 0x50d00338) = 0x00018020; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00538) = 0x0000079c; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005b8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a38) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00638) = 0x0f000f78; // Mask offset and count
  *((volatile uint32_t *) 0x50d006b8) = 0x00000009; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007b8) = 0x00027060; // Post processing register
  *((volatile uint32_t *) 0x50d00738) = 0xffffffff; // Mask and processor enables

  // Layer 11 quadrant 0
  *((volatile uint32_t *) 0x5010003c) = 0x0001000f; // Rows
  *((volatile uint32_t *) 0x501000bc) = 0x0001000b; // Columns
  *((volatile uint32_t *) 0x501001bc) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x5010023c) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x501002bc) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x5010033c) = 0x00010820; // SRAM write ptr
  *((volatile uint32_t *) 0x5010043c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010053c) = 0x00000020; // SRAM read ptr
  *((volatile uint32_t *) 0x501005bc) = 0x00008ba0; // Layer control
  *((volatile uint32_t *) 0x50100a3c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5010063c) = 0x0f800ff8; // Mask offset and count
  *((volatile uint32_t *) 0x501006bc) = 0x00000004; // TRAM ptr max
  *((volatile uint32_t *) 0x501007bc) = 0x00024000; // Post processing register

  // Layer 11 quadrant 1
  *((volatile uint32_t *) 0x5050003c) = 0x0001000f; // Rows
  *((volatile uint32_t *) 0x505000bc) = 0x0001000b; // Columns
  *((volatile uint32_t *) 0x505001bc) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x5050023c) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x505002bc) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x5050033c) = 0x00010820; // SRAM write ptr
  *((volatile uint32_t *) 0x5050043c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050053c) = 0x00000020; // SRAM read ptr
  *((volatile uint32_t *) 0x505005bc) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a3c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5050063c) = 0x0f800ff8; // Mask offset and count
  *((volatile uint32_t *) 0x505006bc) = 0x00000004; // TRAM ptr max
  *((volatile uint32_t *) 0x505007bc) = 0x00024000; // Post processing register

  // Layer 11 quadrant 2
  *((volatile uint32_t *) 0x5090003c) = 0x0001000f; // Rows
  *((volatile uint32_t *) 0x509000bc) = 0x0001000b; // Columns
  *((volatile uint32_t *) 0x509001bc) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x5090023c) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x509002bc) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x5090033c) = 0x00010820; // SRAM write ptr
  *((volatile uint32_t *) 0x5090043c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090053c) = 0x00000020; // SRAM read ptr
  *((volatile uint32_t *) 0x509005bc) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a3c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5090063c) = 0x0f800ff8; // Mask offset and count
  *((volatile uint32_t *) 0x509006bc) = 0x00000004; // TRAM ptr max
  *((volatile uint32_t *) 0x509007bc) = 0x00024000; // Post processing register

  // Layer 11 quadrant 3
  *((volatile uint32_t *) 0x50d0003c) = 0x0001000f; // Rows
  *((volatile uint32_t *) 0x50d000bc) = 0x0001000b; // Columns
  *((volatile uint32_t *) 0x50d001bc) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d0023c) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d002bc) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d0033c) = 0x00010820; // SRAM write ptr
  *((volatile uint32_t *) 0x50d0043c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0053c) = 0x00000020; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005bc) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a3c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d0063c) = 0x0f800ff8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006bc) = 0x00000004; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007bc) = 0x00025070; // Post processing register
  *((volatile uint32_t *) 0x50d0073c) = 0xffffffff; // Mask and processor enables

  // Layer 12 quadrant 0
  *((volatile uint32_t *) 0x50100040) = 0x0001001d; // Rows
  *((volatile uint32_t *) 0x501000c0) = 0x00010016; // Columns
  *((volatile uint32_t *) 0x50100440) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100540) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x501005c0) = 0x0000c920; // Layer control
  *((volatile uint32_t *) 0x50100a40) = 0x00003800; // Layer control 2
  *((volatile uint32_t *) 0x50100640) = 0x10001038; // Mask offset and count
  *((volatile uint32_t *) 0x501006c0) = 0x00000014; // TRAM ptr max
  *((volatile uint32_t *) 0x501007c0) = 0x00025080; // Post processing register

  // Layer 12 quadrant 1
  *((volatile uint32_t *) 0x50500040) = 0x0001001d; // Rows
  *((volatile uint32_t *) 0x505000c0) = 0x00010016; // Columns
  *((volatile uint32_t *) 0x50500440) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500540) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x505005c0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500a40) = 0x00003800; // Layer control 2
  *((volatile uint32_t *) 0x50500640) = 0x10001038; // Mask offset and count
  *((volatile uint32_t *) 0x505006c0) = 0x00000014; // TRAM ptr max
  *((volatile uint32_t *) 0x505007c0) = 0x00024000; // Post processing register

  // Layer 12 quadrant 2
  *((volatile uint32_t *) 0x50900040) = 0x0001001d; // Rows
  *((volatile uint32_t *) 0x509000c0) = 0x00010016; // Columns
  *((volatile uint32_t *) 0x50900440) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900540) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x509005c0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900a40) = 0x00003800; // Layer control 2
  *((volatile uint32_t *) 0x50900640) = 0x10001038; // Mask offset and count
  *((volatile uint32_t *) 0x509006c0) = 0x00000014; // TRAM ptr max
  *((volatile uint32_t *) 0x509007c0) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50900740) = 0xffffffff; // Mask and processor enables

  // Layer 12 quadrant 3
  *((volatile uint32_t *) 0x50d00040) = 0x0001001d; // Rows
  *((volatile uint32_t *) 0x50d000c0) = 0x00010016; // Columns
  *((volatile uint32_t *) 0x50d00440) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00540) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005c0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00a40) = 0x00003800; // Layer control 2
  *((volatile uint32_t *) 0x50d00640) = 0x10001038; // Mask offset and count
  *((volatile uint32_t *) 0x50d006c0) = 0x00000014; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007c0) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50d00740) = 0xffffffff; // Mask and processor enables

  // Layer 13 quadrant 0
  *((volatile uint32_t *) 0x50100044) = 0x00010008; // Rows
  *((volatile uint32_t *) 0x501000c4) = 0x00010006; // Columns
  *((volatile uint32_t *) 0x50100344) = 0x0000024c; // SRAM write ptr
  *((volatile uint32_t *) 0x50100444) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100544) = 0x00000820; // SRAM read ptr
  *((volatile uint32_t *) 0x501005c4) = 0x00006920; // Layer control
  *((volatile uint32_t *) 0x50100a44) = 0x00003800; // Layer control 2
  *((volatile uint32_t *) 0x50100644) = 0x0f800fb8; // Mask offset and count
  *((volatile uint32_t *) 0x501006c4) = 0x00000004; // TRAM ptr max
  *((volatile uint32_t *) 0x501007c4) = 0x00024000; // Post processing register

  // Layer 13 quadrant 1
  *((volatile uint32_t *) 0x50500044) = 0x00010008; // Rows
  *((volatile uint32_t *) 0x505000c4) = 0x00010006; // Columns
  *((volatile uint32_t *) 0x50500344) = 0x0000024c; // SRAM write ptr
  *((volatile uint32_t *) 0x50500444) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500544) = 0x00000820; // SRAM read ptr
  *((volatile uint32_t *) 0x505005c4) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500a44) = 0x00003800; // Layer control 2
  *((volatile uint32_t *) 0x50500644) = 0x0f800fb8; // Mask offset and count
  *((volatile uint32_t *) 0x505006c4) = 0x00000004; // TRAM ptr max
  *((volatile uint32_t *) 0x505007c4) = 0x00025080; // Post processing register

  // Layer 13 quadrant 2
  *((volatile uint32_t *) 0x50900044) = 0x00010008; // Rows
  *((volatile uint32_t *) 0x509000c4) = 0x00010006; // Columns
  *((volatile uint32_t *) 0x50900344) = 0x0000024c; // SRAM write ptr
  *((volatile uint32_t *) 0x50900444) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900544) = 0x00000820; // SRAM read ptr
  *((volatile uint32_t *) 0x509005c4) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900a44) = 0x00003800; // Layer control 2
  *((volatile uint32_t *) 0x50900644) = 0x0f800fb8; // Mask offset and count
  *((volatile uint32_t *) 0x509006c4) = 0x00000004; // TRAM ptr max
  *((volatile uint32_t *) 0x509007c4) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50900744) = 0xffffffff; // Mask and processor enables

  // Layer 13 quadrant 3
  *((volatile uint32_t *) 0x50d00044) = 0x00010008; // Rows
  *((volatile uint32_t *) 0x50d000c4) = 0x00010006; // Columns
  *((volatile uint32_t *) 0x50d00344) = 0x0000024c; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00444) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00544) = 0x00000820; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005c4) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00a44) = 0x00003800; // Layer control 2
  *((volatile uint32_t *) 0x50d00644) = 0x0f800fb8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006c4) = 0x00000004; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007c4) = 0x00024000; // Post processing register

  // Layer 14 quadrant 0
  *((volatile uint32_t *) 0x50100048) = 0x0001001d; // Rows
  *((volatile uint32_t *) 0x501000c8) = 0x00010016; // Columns
  *((volatile uint32_t *) 0x50100348) = 0x00004000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100548) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x501005c8) = 0x0000c920; // Layer control
  *((volatile uint32_t *) 0x50100a48) = 0x00001800; // Layer control 2
  *((volatile uint32_t *) 0x50100648) = 0x10401058; // Mask offset and count
  *((volatile uint32_t *) 0x501006c8) = 0x00000014; // TRAM ptr max

  // Layer 14 quadrant 1
  *((volatile uint32_t *) 0x50500048) = 0x0001001d; // Rows
  *((volatile uint32_t *) 0x505000c8) = 0x00010016; // Columns
  *((volatile uint32_t *) 0x50500348) = 0x00004000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500548) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x505005c8) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500a48) = 0x00001800; // Layer control 2
  *((volatile uint32_t *) 0x50500648) = 0x10401058; // Mask offset and count
  *((volatile uint32_t *) 0x505006c8) = 0x00000014; // TRAM ptr max

  // Layer 14 quadrant 2
  *((volatile uint32_t *) 0x50900048) = 0x0001001d; // Rows
  *((volatile uint32_t *) 0x509000c8) = 0x00010016; // Columns
  *((volatile uint32_t *) 0x50900348) = 0x00004000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900548) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x509005c8) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900a48) = 0x00001800; // Layer control 2
  *((volatile uint32_t *) 0x50900648) = 0x10401058; // Mask offset and count
  *((volatile uint32_t *) 0x509006c8) = 0x00000014; // TRAM ptr max
  *((volatile uint32_t *) 0x509007c8) = 0x00001080; // Post processing register
  *((volatile uint32_t *) 0x50900748) = 0xffffffff; // Mask and processor enables

  // Layer 14 quadrant 3
  *((volatile uint32_t *) 0x50d00048) = 0x0001001d; // Rows
  *((volatile uint32_t *) 0x50d000c8) = 0x00010016; // Columns
  *((volatile uint32_t *) 0x50d00348) = 0x00004000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00548) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005c8) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00a48) = 0x00001800; // Layer control 2
  *((volatile uint32_t *) 0x50d00648) = 0x10401058; // Mask offset and count
  *((volatile uint32_t *) 0x50d006c8) = 0x00000014; // TRAM ptr max
  *((volatile uint32_t *) 0x50d00748) = 0xffffffff; // Mask and processor enables

  // Layer 15 quadrant 0
  *((volatile uint32_t *) 0x5010004c) = 0x00010008; // Rows
  *((volatile uint32_t *) 0x501000cc) = 0x00010006; // Columns
  *((volatile uint32_t *) 0x5010034c) = 0x0000424c; // SRAM write ptr
  *((volatile uint32_t *) 0x5010044c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010054c) = 0x00000820; // SRAM read ptr
  *((volatile uint32_t *) 0x501005cc) = 0x0000c920; // Layer control
  *((volatile uint32_t *) 0x50100a4c) = 0x00001800; // Layer control 2
  *((volatile uint32_t *) 0x5010064c) = 0x0fc00fd8; // Mask offset and count
  *((volatile uint32_t *) 0x501006cc) = 0x00000004; // TRAM ptr max
  *((volatile uint32_t *) 0x501007cc) = 0x00022000; // Post processing register

  // Layer 15 quadrant 1
  *((volatile uint32_t *) 0x5050004c) = 0x00010008; // Rows
  *((volatile uint32_t *) 0x505000cc) = 0x00010006; // Columns
  *((volatile uint32_t *) 0x5050034c) = 0x0000424c; // SRAM write ptr
  *((volatile uint32_t *) 0x5050044c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050054c) = 0x00000820; // SRAM read ptr
  *((volatile uint32_t *) 0x505005cc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500a4c) = 0x00001800; // Layer control 2
  *((volatile uint32_t *) 0x5050064c) = 0x0fc00fd8; // Mask offset and count
  *((volatile uint32_t *) 0x505006cc) = 0x00000004; // TRAM ptr max
  *((volatile uint32_t *) 0x505007cc) = 0x00022000; // Post processing register

  // Layer 15 quadrant 2
  *((volatile uint32_t *) 0x5090004c) = 0x00010008; // Rows
  *((volatile uint32_t *) 0x509000cc) = 0x00010006; // Columns
  *((volatile uint32_t *) 0x5090034c) = 0x0000424c; // SRAM write ptr
  *((volatile uint32_t *) 0x5090044c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090054c) = 0x00000820; // SRAM read ptr
  *((volatile uint32_t *) 0x509005cc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900a4c) = 0x00001800; // Layer control 2
  *((volatile uint32_t *) 0x5090064c) = 0x0fc00fd8; // Mask offset and count
  *((volatile uint32_t *) 0x509006cc) = 0x00000004; // TRAM ptr max
  *((volatile uint32_t *) 0x509007cc) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x5090074c) = 0xffffffff; // Mask and processor enables

  // Layer 15 quadrant 3
  *((volatile uint32_t *) 0x50d0004c) = 0x00010008; // Rows
  *((volatile uint32_t *) 0x50d000cc) = 0x00010006; // Columns
  *((volatile uint32_t *) 0x50d0034c) = 0x0000424c; // SRAM write ptr
  *((volatile uint32_t *) 0x50d0044c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0054c) = 0x00000820; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005cc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00a4c) = 0x00001800; // Layer control 2
  *((volatile uint32_t *) 0x50d0064c) = 0x0fc00fd8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006cc) = 0x00000004; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007cc) = 0x00023080; // Post processing register


  *((volatile uint32_t *) 0x50000000) = 0x00001908; // FIFO control

  return CNN_OK;
}

int cnn_start(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) = 0x0018c808; // Enable quadrant 0
  *((volatile uint32_t *) 0x50500000) = 0x0018c809; // Enable quadrant 1
  *((volatile uint32_t *) 0x50900000) = 0x0018c809; // Enable quadrant 2
  *((volatile uint32_t *) 0x50d00000) = 0x0018c809; // Enable quadrant 3

#ifdef CNN_INFERENCE_TIMER
  MXC_TMR_SW_Start(CNN_INFERENCE_TIMER);
#endif

//   CNN_START; // Allow capture of processing time
  *((volatile uint32_t *) 0x50100000) = 0x0018c809; // Master enable quadrant 0

  return CNN_OK;
}

int cnn_unload(uint32_t *out_buf32)
{
  uint8_t *out_buf = (uint8_t *) out_buf32;
  uint32_t val;
  volatile uint32_t *addr;
  int i;
  uint32_t offs;

  // Custom unload for this network, layer 12: 8-bit data, shape: (8, 28, 21)
  offs = 0x0000;
  addr = (volatile uint32_t *) 0x50400000;
  for (i = 0; i < 588; i++) {
    val = *addr++;
    out_buf[offs] = val & 0xff;
    out_buf[offs+0x24c] = (val >> 8) & 0xff;
    out_buf[offs+0x498] = (val >> 16) & 0xff;
    out_buf[offs+0x6e4] = (val >> 24) & 0xff;
    offs++;
  }
  offs += 0x06e4;
  addr = (volatile uint32_t *) 0x50408000;
  for (i = 0; i < 588; i++) {
    val = *addr++;
    out_buf[offs] = val & 0xff;
    out_buf[offs+0x24c] = (val >> 8) & 0xff;
    out_buf[offs+0x498] = (val >> 16) & 0xff;
    out_buf[offs+0x6e4] = (val >> 24) & 0xff;
    offs++;
  }

  // Custom unload for this network, layer 13: 8-bit data, shape: (8, 7, 5)
  offs = 0x0000;
  out_buf = ((uint8_t *) out_buf32) + 0x1260;
  addr = (volatile uint32_t *) 0x50400930;
  for (i = 0; i < 35; i++) {
    val = *addr++;
    out_buf[offs] = val & 0xff;
    out_buf[offs+0x23] = (val >> 8) & 0xff;
    out_buf[offs+0x46] = (val >> 16) & 0xff;
    out_buf[offs+0x69] = (val >> 24) & 0xff;
    offs++;
  }
  offs += 0x0069;
  addr = (volatile uint32_t *) 0x50408930;
  for (i = 0; i < 35; i++) {
    val = *addr++;
    out_buf[offs] = val & 0xff;
    out_buf[offs+0x23] = (val >> 8) & 0xff;
    out_buf[offs+0x46] = (val >> 16) & 0xff;
    out_buf[offs+0x69] = (val >> 24) & 0xff;
    offs++;
  }

  // Custom unload for this network, layer 14: 8-bit data, shape: (4, 28, 21)
  offs = 0x0000;
  out_buf = ((uint8_t *) out_buf32) + 0x1378;
  addr = (volatile uint32_t *) 0x50410000;
  for (i = 0; i < 588; i++) {
    val = *addr++;
    out_buf[offs] = val & 0xff;
    out_buf[offs+0x24c] = (val >> 8) & 0xff;
    out_buf[offs+0x498] = (val >> 16) & 0xff;
    out_buf[offs+0x6e4] = (val >> 24) & 0xff;
    offs++;
  }

  // Custom unload for this network, layer 15: 8-bit data, shape: (4, 7, 5)
  offs = 0x0000;
  out_buf = ((uint8_t *) out_buf32) + 0x1ca8;
  for (i = 0; i < 35; i++) {
    val = *addr++;
    out_buf[offs] = val & 0xff;
    out_buf[offs+0x23] = (val >> 8) & 0xff;
    out_buf[offs+0x46] = (val >> 16) & 0xff;
    out_buf[offs+0x69] = (val >> 24) & 0xff;
    offs++;
  }

  return CNN_OK;
}

int cnn_enable(uint32_t clock_source, uint32_t clock_divider)
{
  // Reset all domains, restore power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg1 = 0xf; // Mask memory
  MXC_GCFR->reg0 = 0xf; // Power
  MXC_GCFR->reg2 = 0x0; // Iso
  MXC_GCFR->reg3 = 0x0; // Reset

  MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                     | clock_divider | clock_source;
  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN); // Enable CNN clock

  MXC_NVIC_SetVector(CNN_IRQn, CNN_ISR); // Set CNN complete vector

  return CNN_OK;
}

int cnn_boost_enable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutSet(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_boost_disable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutClr(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_disable(void)
{
  // Disable CNN clock
  MXC_SYS_ClockDisable(MXC_SYS_PERIPH_CLOCK_CNN);

  // Disable power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg2 |= 0xf; // Iso
  MXC_GCFR->reg0 = 0x0; // Power
  MXC_GCFR->reg1 = 0x0; // Mask memory
  MXC_GCFR->reg3 = 0x0; // Reset

  return CNN_OK;
}

