var group__tpu__registers =
[
    [ "Register Offsets", "group___t_p_u___register___offsets.html", "group___t_p_u___register___offsets" ],
    [ "TPU_CTRL", "group___t_p_u___c_t_r_l.html", "group___t_p_u___c_t_r_l" ],
    [ "TPU_CIPHER_CTRL", "group___t_p_u___c_i_p_h_e_r___c_t_r_l.html", "group___t_p_u___c_i_p_h_e_r___c_t_r_l" ],
    [ "TPU_HASH_CTRL", "group___t_p_u___h_a_s_h___c_t_r_l.html", "group___t_p_u___h_a_s_h___c_t_r_l" ],
    [ "TPU_CRC_CTRL", "group___t_p_u___c_r_c___c_t_r_l.html", "group___t_p_u___c_r_c___c_t_r_l" ],
    [ "TPU_DMA_SRC", "group___t_p_u___d_m_a___s_r_c.html", "group___t_p_u___d_m_a___s_r_c" ],
    [ "TPU_DMA_DST", "group___t_p_u___d_m_a___d_s_t.html", "group___t_p_u___d_m_a___d_s_t" ],
    [ "TPU_DMA_CNT", "group___t_p_u___d_m_a___c_n_t.html", "group___t_p_u___d_m_a___c_n_t" ],
    [ "TPU_MAA_CTRL", "group___t_p_u___m_a_a___c_t_r_l.html", "group___t_p_u___m_a_a___c_t_r_l" ],
    [ "TPU_DATA_IN", "group___t_p_u___d_a_t_a___i_n.html", "group___t_p_u___d_a_t_a___i_n" ],
    [ "TPU_DATA_OUT", "group___t_p_u___d_a_t_a___o_u_t.html", "group___t_p_u___d_a_t_a___o_u_t" ],
    [ "TPU_CRC_POLY", "group___t_p_u___c_r_c___p_o_l_y.html", "group___t_p_u___c_r_c___p_o_l_y" ],
    [ "TPU_CRC_VAL", "group___t_p_u___c_r_c___v_a_l.html", "group___t_p_u___c_r_c___v_a_l" ],
    [ "TPU_CRC_PRNG", "group___t_p_u___c_r_c___p_r_n_g.html", "group___t_p_u___c_r_c___p_r_n_g" ],
    [ "TPU_HAM_ECC", "group___t_p_u___h_a_m___e_c_c.html", "group___t_p_u___h_a_m___e_c_c" ],
    [ "TPU_CIPHER_INIT", "group___t_p_u___c_i_p_h_e_r___i_n_i_t.html", "group___t_p_u___c_i_p_h_e_r___i_n_i_t" ],
    [ "TPU_CIPHER_KEY", "group___t_p_u___c_i_p_h_e_r___k_e_y.html", "group___t_p_u___c_i_p_h_e_r___k_e_y" ],
    [ "TPU_HASH_DIGEST", "group___t_p_u___h_a_s_h___d_i_g_e_s_t.html", "group___t_p_u___h_a_s_h___d_i_g_e_s_t" ],
    [ "TPU_HASH_MSG_SZ", "group___t_p_u___h_a_s_h___m_s_g___s_z.html", "group___t_p_u___h_a_s_h___m_s_g___s_z" ],
    [ "TPU_MAA_MAWS", "group___t_p_u___m_a_a___m_a_w_s.html", "group___t_p_u___m_a_a___m_a_w_s" ],
    [ "mxc_tpu_regs_t", "group__tpu__registers.html#structmxc__tpu__regs__t", [
      [ "cipher_ctrl", "group__tpu__registers.html#ac2afd62d12a270c7db8a7090f7f783ac", null ],
      [ "cipher_init", "group__tpu__registers.html#ab0a9cd31e9876264786d25a2fdf69c41", null ],
      [ "cipher_key", "group__tpu__registers.html#a785e6822a015300103dc4e9e4248480c", null ],
      [ "crc_ctrl", "group__tpu__registers.html#a116e20263f4e37b2de139dbb8d3c4374", null ],
      [ "crc_poly", "group__tpu__registers.html#a246835946902ef53647e6f0e33612788", null ],
      [ "crc_prng", "group__tpu__registers.html#a7f78d0a4efa9fb019a0c1d5eb49f39af", null ],
      [ "crc_val", "group__tpu__registers.html#a3aa1e114f572bce143167b2b2f64a267", null ],
      [ "ctrl", "group__tpu__registers.html#a5f3ab705a4a67b17dcc04560cef193f3", null ],
      [ "data_in", "group__tpu__registers.html#abdb90590935909f5a51b7cbb31ddae93", null ],
      [ "data_out", "group__tpu__registers.html#aa0c93c03090c47d3da53edb01aaa3f23", null ],
      [ "dma_cnt", "group__tpu__registers.html#a4b2f4c201d54bcb8150a141789bdf022", null ],
      [ "dma_dst", "group__tpu__registers.html#aab5885c46623cd230264db0760af42d2", null ],
      [ "dma_src", "group__tpu__registers.html#a602e02e60799eaf0b02e55b4481bf32c", null ],
      [ "ham_ecc", "group__tpu__registers.html#ac699beaeeed2c55ca58b352b2fafdf87", null ],
      [ "hash_ctrl", "group__tpu__registers.html#aa347553b1bbc7d4265c194d73f408f3b", null ],
      [ "hash_digest", "group__tpu__registers.html#a7d1fd61e8572bdb0073455b3d324eee6", null ],
      [ "hash_msg_sz", "group__tpu__registers.html#aca985e364705cabb381dc54db55cfd98", null ],
      [ "maa_ctrl", "group__tpu__registers.html#afd17b9508eb5f17d19468507275bbab2", null ],
      [ "maa_maws", "group__tpu__registers.html#a0c681b18c7d76a83a17358e70e0d62a3", null ]
    ] ]
];