var modules =
[
    [ "Analog to Digital Converter (ADC)", "group__adc.html", "group__adc" ],
    [ "Direct Memory Access (DMA)", "group__dma.html", "group__dma" ],
    [ "Flash Controller  (FLC)", "group__flc.html", "group__flc" ],
    [ "General-Purpose Input/Output (GPIO)", "group__gpio.html", "group__gpio" ],
    [ "HTMR", "group__htmr.html", "group__htmr" ],
    [ "I2C", "group__i2c.html", "group__i2c" ],
    [ "ICC", "group__icc.html", "group__icc" ],
    [ "Low Power (LP)", "group__pwrseq.html", "group__pwrseq" ],
    [ "Assertion Checks for Debugging", "group__mxc__assertions.html", "group__mxc__assertions" ],
    [ "Delay Utility Functions", "group___m_x_c__delay.html", "group___m_x_c__delay" ],
    [ "Error Codes", "group___m_x_c___error___codes.html", "group___m_x_c___error___codes" ],
    [ "Exclusive Access Locks", "group__mxc__lock__utilities.html", "group__mxc__lock__utilities" ],
    [ "1-Wire Master (OWM)", "group__owm.html", "group__owm" ],
    [ "Pulse Train Engine", "group__pt.html", "group__pt" ],
    [ "Resource Protection Unit", "group__rpu.html", "group__rpu" ],
    [ "Real Time Clock (RTC)", "group__rtc.html", "group__rtc" ],
    [ "SDHC", "group__sdhc.html", "group__sdhc" ],
    [ "Semaphore (SEMA)", "group__sema.html", "group__sema" ],
    [ "SPI", "group__spi.html", "group__spi" ],
    [ "SPI External Flash (SPIXF)", "group__spixf.html", "group__spixf" ],
    [ "SPI External RAM (SPIXR)", "group__spixr.html", "group__spixr" ],
    [ "SPIX Cache Controller (SRCC)", "group__srcc.html", "group__srcc" ],
    [ "Timer (TMR)", "group__tmr.html", "group__tmr" ],
    [ "Trust Protection Unit (TPU)", "group__tpu.html", "group__tpu" ],
    [ "TRNG", "group__trng.html", "group__trng" ],
    [ "UART", "group__uart.html", "group__uart" ],
    [ "Watchdog Timer (WDT)", "group__wdt.html", "group__wdt" ],
    [ "Wakeup Timer (WUT)", "group__wut.html", "group__wut" ],
    [ "AES_KEY_Registers", "group__aes__key__registers.html", "group__aes__key__registers" ],
    [ "DVS_Registers", "group__dvs__registers.html", "group__dvs__registers" ],
    [ "FCR_Registers", "group__fcr__registers.html", "group__fcr__registers" ],
    [ "GCR_Registers", "group__gcr__registers.html", "group__gcr__registers" ],
    [ "MCR_Registers", "group__mcr__registers.html", "group__mcr__registers" ],
    [ "PTG_Registers", "group__ptg__registers.html", "group__ptg__registers" ],
    [ "SDMA_Registers", "group__sdma__registers.html", "group__sdma__registers" ],
    [ "SIMO_Registers", "group__simo__registers.html", "group__simo__registers" ],
    [ "SIR_Registers", "group__sir__registers.html", "group__sir__registers" ],
    [ "SMON_Registers", "group__smon__registers.html", "group__smon__registers" ],
    [ "TRIMSIR_Registers", "group__trimsir__registers.html", "group__trimsir__registers" ],
    [ "USBHS_Registers", "group__usbhs__registers.html", "group__usbhs__registers" ]
];