var modules =
[
    [ "ADC", "group__adc.html", "group__adc" ],
    [ "AES", "group__aes.html", "group__aes" ],
    [ "CAN", "group__can.html", "group__can" ],
    [ "CRC", "group__crc.html", "group__crc" ],
    [ "Direct Memory Access (DMA)", "group__dma.html", "group__dma" ],
    [ "Flash Controller  (FLC)", "group__flc.html", "group__flc" ],
    [ "General-Purpose Input/Output (GPIO)", "group__gpio.html", "group__gpio" ],
    [ "I2C", "group__i2c.html", "group__i2c" ],
    [ "Inter-Integrated Sound (I2S)", "group__i2s.html", "group__i2s" ],
    [ "ICC", "group__icc.html", "group__icc" ],
    [ "Low Power (LP)", "group__pwrseq.html", "group__pwrseq" ],
    [ "Assertion Checks for Debugging", "group__mxc__assertions.html", "group__mxc__assertions" ],
    [ "Delay Utility Functions", "group___m_x_c__delay.html", "group___m_x_c__delay" ],
    [ "Error Codes", "group___m_x_c___error___codes.html", "group___m_x_c___error___codes" ],
    [ "Exclusive Access Locks", "group__mxc__lock__utilities.html", "group__mxc__lock__utilities" ],
    [ "System Configuration (MXC_SYS)", "group__mxc__sys.html", "group__mxc__sys" ],
    [ "Pulse Train Engine", "group__pulsetrain.html", "group__pulsetrain" ],
    [ "Real Time Clock (RTC)", "group__rtc.html", "group__rtc" ],
    [ "SPI", "group__spi.html", "group__spi" ],
    [ "Timer (TMR)", "group__tmr.html", "group__tmr" ],
    [ "TRNG", "group__trng.html", "group__trng" ],
    [ "UART", "group__uart.html", "group__uart" ],
    [ "WDT", "group__wdt.html", "group__wdt" ],
    [ "AES_KEY_Registers", "group__aes__key__registers.html", "group__aes__key__registers" ],
    [ "AESKEYS_Registers", "group__aeskeys__registers.html", "group__aeskeys__registers" ],
    [ "FCR_Registers", "group__fcr__registers.html", "group__fcr__registers" ],
    [ "GCR_Registers", "group__gcr__registers.html", "group__gcr__registers" ],
    [ "MCR_Registers", "group__mcr__registers.html", "group__mcr__registers" ],
    [ "PT_Registers", "group__pt__registers.html", "group__pt__registers" ],
    [ "PTG_Registers", "group__ptg__registers.html", "group__ptg__registers" ],
    [ "SIR_Registers", "group__sir__registers.html", "group__sir__registers" ],
    [ "TRIMSIR_Registers", "group__trimsir__registers.html", "group__trimsir__registers" ]
];