var modules =
[
    [ "Analog to Digital Converter (ADC)", "group__adc.html", "group__adc" ],
    [ "CTB", "group__ctb.html", "group__ctb" ],
    [ "Direct Memory Access (DMA)", "group__dma.html", "group__dma" ],
    [ "General-Purpose Input/Output (GPIO)", "group__gpio.html", "group__gpio" ],
    [ "HTMR", "group__htmr.html", "group__htmr" ],
    [ "I2C", "group__i2c.html", "group__i2c" ],
    [ "Low Power (LP)", "group__pwrseq.html", "group__pwrseq" ],
    [ "Assertion Checks for Debugging", "group__mxc__assertions.html", "group__mxc__assertions" ],
    [ "Delay Utility Functions", "group___m_x_c__delay.html", "group___m_x_c__delay" ],
    [ "Error Codes", "group___m_x_c___error___codes.html", "group___m_x_c___error___codes" ],
    [ "Exclusive Access Locks", "group__mxc__lock__utilities.html", "group__mxc__lock__utilities" ],
    [ "One-Time Programmable Memory Controller", "group__otp.html", "group__otp" ],
    [ "Pulse Train Engine", "group__pt.html", "group__pt" ],
    [ "Real Time Clock (RTC)", "group__rtc.html", "group__rtc" ],
    [ "Smart Card (SC)", "group__scn.html", "group__scn" ],
    [ "Secure Keyboard (SKBD)", "group__skbd.html", "group__skbd" ],
    [ "Security Monitor(SMON)", "group__smon.html", "group__smon" ],
    [ "Serial Peripheral Interface (SPI)", "group__spi.html", "group__spi" ],
    [ "SPI External Flash (SPIXF)", "group__spixf.html", "group__spixf" ],
    [ "Timer (TMR)", "group__tmr.html", "group__tmr" ],
    [ "UART", "group__uart.html", "group__uart" ],
    [ "Watchdog Timer (WDT)", "group__wdt.html", "group__wdt" ],
    [ "AES_KEY_Registers", "group__aes__key__registers.html", "group__aes__key__registers" ],
    [ "FCR_Registers", "group__fcr__registers.html", "group__fcr__registers" ],
    [ "GCR_Registers", "group__gcr__registers.html", "group__gcr__registers" ],
    [ "MCR_Registers", "group__mcr__registers.html", "group__mcr__registers" ],
    [ "MSRADC_Registers", "group__msradc__registers.html", "group__msradc__registers" ],
    [ "PTG_Registers", "group__ptg__registers.html", "group__ptg__registers" ],
    [ "SDMA_Registers", "group__sdma__registers.html", "group__sdma__registers" ],
    [ "SEMA_Registers", "group__sema__registers.html", "group__sema__registers" ],
    [ "SFCC_Registers", "group__sfcc__registers.html", "group__sfcc__registers" ],
    [ "SIR_Registers", "group__sir__registers.html", "group__sir__registers" ],
    [ "TRIMSIR_Registers", "group__trimsir__registers.html", "group__trimsir__registers" ],
    [ "TRNG_Registers", "group__trng__registers.html", "group__trng__registers" ],
    [ "USBHS_Registers", "group__usbhs__registers.html", "group__usbhs__registers" ]
];