var modules =
[
    [ "Analog to Digital Converter (ADC)", "group__adc.html", "group__adc" ],
    [ "AES", "group__aes.html", "group__aes" ],
    [ "Cameraif", "group__cameraif.html", "group__cameraif" ],
    [ "CRC", "group__crc.html", "group__crc" ],
    [ "Direct Memory Access (DMA)", "group__dma.html", "group__dma" ],
    [ "Flash Controller  (FLC)", "group__flc.html", "group__flc" ],
    [ "General-Purpose Input/Output (GPIO)", "group__gpio.html", "group__gpio" ],
    [ "I2C", "group__i2c.html", "group__i2c" ],
    [ "Inter-Integrated Sound (I2S)", "group__i2s.html", "group__i2s" ],
    [ "ICC", "group__icc.html", "group__icc" ],
    [ "Low Power (LP)", "group__pwrseq.html", "group__pwrseq" ],
    [ "Assertion Checks for Debugging", "group__mxc__assertions.html", "group__mxc__assertions" ],
    [ "Delay Utility Functions", "group___m_x_c__delay.html", "group___m_x_c__delay" ],
    [ "Error Codes", "group___m_x_c___error___codes.html", "group___m_x_c___error___codes" ],
    [ "Exclusive Access Locks", "group__mxc__lock__utilities.html", "group__mxc__lock__utilities" ],
    [ "1-Wire Master (OWM)", "group__owm.html", "group__owm" ],
    [ "Pulse Train Engine", "group__pulsetrain.html", "group__pulsetrain" ],
    [ "Real Time Clock (RTC)", "group__rtc.html", "group__rtc" ],
    [ "Semaphore (SEMA)", "group__sema.html", "group__sema" ],
    [ "SPI", "group__spi.html", "group__spi" ],
    [ "Timer (TMR)", "group__tmr.html", "group__tmr" ],
    [ "TRNG", "group__trng.html", "group__trng" ],
    [ "UART", "group__uart.html", "group__uart" ],
    [ "WDT", "group__wdt.html", "group__wdt" ],
    [ "Wakeup Timer (WUT)", "group__wut.html", "group__wut" ],
    [ "AES_KEY_Registers", "group__aes__key__registers.html", "group__aes__key__registers" ],
    [ "DVS_Registers", "group__dvs__registers.html", "group__dvs__registers" ],
    [ "FCR_Registers", "group__fcr__registers.html", "group__fcr__registers" ],
    [ "GCFR_Registers", "group__gcfr__registers.html", "group__gcfr__registers" ],
    [ "GCR_Registers", "group__gcr__registers.html", "group__gcr__registers" ],
    [ "LPGCR_Registers", "group__lpgcr__registers.html", "group__lpgcr__registers" ],
    [ "MCR_Registers", "group__mcr__registers.html", "group__mcr__registers" ],
    [ "SIMO_Registers", "group__simo__registers.html", "group__simo__registers" ],
    [ "SIR_Registers", "group__sir__registers.html", "group__sir__registers" ],
    [ "TRIMSIR_Registers", "group__trimsir__registers.html", "group__trimsir__registers" ],
    [ "External Memory Cache Controller (EMCC)", "group__emcc.html", "group__emcc" ]
];