var searchData=
[
  ['sir_5fregisters_5671',['SIR_Registers',['../group__sir__registers.html',1,'']]],
  ['sir_5fsiaddr_5672',['SIR_SIADDR',['../group___s_i_r___s_i_a_d_d_r.html',1,'']]],
  ['sir_5fsistat_5673',['SIR_SISTAT',['../group___s_i_r___s_i_s_t_a_t.html',1,'']]],
  ['spi_5674',['SPI',['../group__spi.html',1,'']]],
  ['spi_5fclkctrl_5675',['SPI_CLKCTRL',['../group___s_p_i___c_l_k_c_t_r_l.html',1,'']]],
  ['spi_5fctrl0_5676',['SPI_CTRL0',['../group___s_p_i___c_t_r_l0.html',1,'']]],
  ['spi_5fctrl1_5677',['SPI_CTRL1',['../group___s_p_i___c_t_r_l1.html',1,'']]],
  ['spi_5fctrl2_5678',['SPI_CTRL2',['../group___s_p_i___c_t_r_l2.html',1,'']]],
  ['spi_5fdma_5679',['SPI_DMA',['../group___s_p_i___d_m_a.html',1,'']]],
  ['spi_5ffifo16_5680',['SPI_FIFO16',['../group___s_p_i___f_i_f_o16.html',1,'']]],
  ['spi_5ffifo32_5681',['SPI_FIFO32',['../group___s_p_i___f_i_f_o32.html',1,'']]],
  ['spi_5ffifo8_5682',['SPI_FIFO8',['../group___s_p_i___f_i_f_o8.html',1,'']]],
  ['spi_5finten_5683',['SPI_INTEN',['../group___s_p_i___i_n_t_e_n.html',1,'']]],
  ['spi_5fintfl_5684',['SPI_INTFL',['../group___s_p_i___i_n_t_f_l.html',1,'']]],
  ['spi_5fregisters_5685',['SPI_Registers',['../group__spi__registers.html',1,'']]],
  ['spi_5fsstime_5686',['SPI_SSTIME',['../group___s_p_i___s_s_t_i_m_e.html',1,'']]],
  ['spi_5fstat_5687',['SPI_STAT',['../group___s_p_i___s_t_a_t.html',1,'']]],
  ['spi_5fwken_5688',['SPI_WKEN',['../group___s_p_i___w_k_e_n.html',1,'']]],
  ['spi_5fwkfl_5689',['SPI_WKFL',['../group___s_p_i___w_k_f_l.html',1,'']]]
];
