# Found using the command "find -L . -name \*.c" run from inside this directory
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/animimg/lv_animimg.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/colorwheel/lv_colorwheel.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/calendar/lv_calendar_header_arrow.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/calendar/lv_calendar.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/calendar/lv_calendar_header_dropdown.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/menu/lv_menu.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/msgbox/lv_msgbox.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/span/lv_span.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/spinbox/lv_spinbox.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/win/lv_win.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/led/lv_led.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/keyboard/lv_keyboard.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/spinner/lv_spinner.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/meter/lv_meter.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/imgbtn/lv_imgbtn.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/chart/lv_chart.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/list/lv_list.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/tabview/lv_tabview.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/tileview/lv_tileview.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/gif/lv_gif.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/gif/gifdec.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/bmp/lv_bmp.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/sjpg/lv_sjpg.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/sjpg/tjpgd.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/ffmpeg/lv_ffmpeg.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/rlottie/lv_rlottie.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/png/lv_png.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/png/lodepng.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/freetype/lv_freetype.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/qrcode/qrcodegen.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/qrcode/lv_qrcode.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/fsdrv/lv_fs_stdio.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/fsdrv/lv_fs_posix.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/fsdrv/lv_fs_fatfs.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/fsdrv/lv_fs_win32.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/layouts/flex/lv_flex.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/layouts/grid/lv_grid.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/imgfont/lv_imgfont.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/snapshot/lv_snapshot.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/gridnav/lv_gridnav.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/monkey/lv_monkey.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/fragment/lv_fragment_manager.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/fragment/lv_fragment.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/msg/lv_msg.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/ime/lv_ime_pinyin.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/lv_extra.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/themes/mono/lv_theme_mono.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/themes/default/lv_theme_default.c
CSRCS += $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/themes/basic/lv_theme_basic.c

DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/animimg
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/colorwheel
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/calendar
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/menu
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/msgbox
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/span
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/spinbox
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/win
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/led
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/keyboard
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/spinner
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/meter
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/imgbtn
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/chart
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/list
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/tabview
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/tileview
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/gif
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/bmp
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/sjpg
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/ffmpeg
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/rlottie
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/png
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/freetype
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/qrcode
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/fsdrv
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/layouts/flex
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/layouts/grid
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/imgfont
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/snapshot
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/gridnav
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/monkey
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/fragment
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/msg
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/ime
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/themes/mono
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/themes/default
DEPPATH += --dep-path $(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/themes/basic

VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/animimg
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/colorwheel
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/calendar
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/menu
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/msgbox
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/span
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/spinbox
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/win
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/led
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/keyboard
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/spinner
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/meter
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/imgbtn
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/chart
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/list
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/tabview
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/tileview
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/gif
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/bmp
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/sjpg
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/ffmpeg
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/rlottie
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/png
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/freetype
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/qrcode
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/fsdrv
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/layouts/flex
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/layouts/grid
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/imgfont
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/snapshot
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/gridnav
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/monkey
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/fragment
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/msg
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/ime
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/themes/mono
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/themes/default
VPATH += :$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/themes/basic

CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/animimg"
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/colorwheel
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/calendar
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/menu
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/msgbox
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/span
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/spinbox
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/win
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/led
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/keyboard
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/spinner
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/meter
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/imgbtn
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/chart
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/list
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/tabview
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/widgets/tileview
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/gif
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/bmp
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/sjpg
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/ffmpeg
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/rlottie
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/png
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/freetype
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/qrcode
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/libs/fsdrv
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/layouts/flex
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/layouts/grid
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/imgfont
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/snapshot
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/gridnav
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/monkey
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/fragment
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/msg
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/others/ime
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/themes/mono
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/themes/default
CFLAGS += "-I$(LVGL_DIR)/$(LVGL_DIR_NAME)/src/extra/themes/basic
