var searchData=
[
  ['timer_20_28tmr_29_0',['Timer (TMR)',['../group__tmr.html',1,'']]],
  ['tmr_5fcn_1',['TMR_CN',['../group___t_m_r___c_n.html',1,'']]],
  ['tmr_5fintr_2',['TMR_INTR',['../group___t_m_r___i_n_t_r.html',1,'']]],
  ['tmr_5fnolcmp_3',['TMR_NOLCMP',['../group___t_m_r___n_o_l_c_m_p.html',1,'']]],
  ['tmr_5fregisters_4',['TMR_Registers',['../group__tmr__registers.html',1,'']]],
  ['tpu_5fcipher_5fctrl_5',['TPU_CIPHER_CTRL',['../group___t_p_u___c_i_p_h_e_r___c_t_r_l.html',1,'']]],
  ['tpu_5fcipher_5finit_6',['TPU_CIPHER_INIT',['../group___t_p_u___c_i_p_h_e_r___i_n_i_t.html',1,'']]],
  ['tpu_5fcipher_5fkey_7',['TPU_CIPHER_KEY',['../group___t_p_u___c_i_p_h_e_r___k_e_y.html',1,'']]],
  ['tpu_5fcrc_5fctrl_8',['TPU_CRC_CTRL',['../group___t_p_u___c_r_c___c_t_r_l.html',1,'']]],
  ['tpu_5fcrc_5fpoly_9',['TPU_CRC_POLY',['../group___t_p_u___c_r_c___p_o_l_y.html',1,'']]],
  ['tpu_5fcrc_5fprng_10',['TPU_CRC_PRNG',['../group___t_p_u___c_r_c___p_r_n_g.html',1,'']]],
  ['tpu_5fcrc_5fval_11',['TPU_CRC_VAL',['../group___t_p_u___c_r_c___v_a_l.html',1,'']]],
  ['tpu_5fctrl_12',['TPU_CTRL',['../group___t_p_u___c_t_r_l.html',1,'']]],
  ['tpu_5fdata_5fin_13',['TPU_DATA_IN',['../group___t_p_u___d_a_t_a___i_n.html',1,'']]],
  ['tpu_5fdata_5fout_14',['TPU_DATA_OUT',['../group___t_p_u___d_a_t_a___o_u_t.html',1,'']]],
  ['tpu_5fdma_5fcnt_15',['TPU_DMA_CNT',['../group___t_p_u___d_m_a___c_n_t.html',1,'']]],
  ['tpu_5fdma_5fdst_16',['TPU_DMA_DST',['../group___t_p_u___d_m_a___d_s_t.html',1,'']]],
  ['tpu_5fdma_5fsrc_17',['TPU_DMA_SRC',['../group___t_p_u___d_m_a___s_r_c.html',1,'']]],
  ['tpu_5fham_5fecc_18',['TPU_HAM_ECC',['../group___t_p_u___h_a_m___e_c_c.html',1,'']]],
  ['tpu_5fhash_5fctrl_19',['TPU_HASH_CTRL',['../group___t_p_u___h_a_s_h___c_t_r_l.html',1,'']]],
  ['tpu_5fhash_5fdigest_20',['TPU_HASH_DIGEST',['../group___t_p_u___h_a_s_h___d_i_g_e_s_t.html',1,'']]],
  ['tpu_5fhash_5fmsg_5fsz_21',['TPU_HASH_MSG_SZ',['../group___t_p_u___h_a_s_h___m_s_g___s_z.html',1,'']]],
  ['tpu_5fmaa_5fctrl_22',['TPU_MAA_CTRL',['../group___t_p_u___m_a_a___c_t_r_l.html',1,'']]],
  ['tpu_5fmaa_5fmaws_23',['TPU_MAA_MAWS',['../group___t_p_u___m_a_a___m_a_w_s.html',1,'']]],
  ['tpu_5fregisters_24',['TPU_Registers',['../group__tpu__registers.html',1,'']]],
  ['trimsir_5fregisters_25',['TRIMSIR_Registers',['../group__trimsir__registers.html',1,'']]],
  ['trimsir_5frtc_26',['TRIMSIR_RTC',['../group___t_r_i_m_s_i_r___r_t_c.html',1,'']]],
  ['trimsir_5fsir13_27',['TRIMSIR_SIR13',['../group___t_r_i_m_s_i_r___s_i_r13.html',1,'']]],
  ['trimsir_5fsir17_28',['TRIMSIR_SIR17',['../group___t_r_i_m_s_i_r___s_i_r17.html',1,'']]],
  ['trng_29',['TRNG',['../group__trng.html',1,'']]],
  ['trng_5fcn_30',['TRNG_CN',['../group___t_r_n_g___c_n.html',1,'']]],
  ['trng_5fdata_31',['TRNG_DATA',['../group___t_r_n_g___d_a_t_a.html',1,'']]],
  ['trng_5fregisters_32',['TRNG_Registers',['../group__trng__registers.html',1,'']]],
  ['trng_5fst_33',['TRNG_ST',['../group___t_r_n_g___s_t.html',1,'']]],
  ['trust_20protection_20unit_20_28tpu_29_34',['Trust Protection Unit (TPU)',['../group__tpu.html',1,'']]]
];
