var searchData=
[
  ['delay_20utility_20functions_0',['Delay Utility Functions',['../group___m_x_c__delay.html',1,'']]],
  ['direct_20memory_20access_20_28dma_29_1',['Direct Memory Access (DMA)',['../group__dma.html',1,'']]],
  ['dma_5fcfg_2',['DMA_CFG',['../group___d_m_a___c_f_g.html',1,'']]],
  ['dma_5fcn_3',['DMA_CN',['../group___d_m_a___c_n.html',1,'']]],
  ['dma_5fcnt_4',['DMA_CNT',['../group___d_m_a___c_n_t.html',1,'']]],
  ['dma_5fcnt_5frld_5',['DMA_CNT_RLD',['../group___d_m_a___c_n_t___r_l_d.html',1,'']]],
  ['dma_5fdst_6',['DMA_DST',['../group___d_m_a___d_s_t.html',1,'']]],
  ['dma_5fdst_5frld_7',['DMA_DST_RLD',['../group___d_m_a___d_s_t___r_l_d.html',1,'']]],
  ['dma_5fintr_8',['DMA_INTR',['../group___d_m_a___i_n_t_r.html',1,'']]],
  ['dma_5fregisters_9',['DMA_Registers',['../group__dma__registers.html',1,'']]],
  ['dma_5fsrc_10',['DMA_SRC',['../group___d_m_a___s_r_c.html',1,'']]],
  ['dma_5fsrc_5frld_11',['DMA_SRC_RLD',['../group___d_m_a___s_r_c___r_l_d.html',1,'']]],
  ['dma_5fst_12',['DMA_ST',['../group___d_m_a___s_t.html',1,'']]],
  ['dvs_5fadj_5fdwn_13',['DVS_ADJ_DWN',['../group___d_v_s___a_d_j___d_w_n.html',1,'']]],
  ['dvs_5fadj_5fup_14',['DVS_ADJ_UP',['../group___d_v_s___a_d_j___u_p.html',1,'']]],
  ['dvs_5fctl_15',['DVS_CTL',['../group___d_v_s___c_t_l.html',1,'']]],
  ['dvs_5fdirect_16',['DVS_DIRECT',['../group___d_v_s___d_i_r_e_c_t.html',1,'']]],
  ['dvs_5fmon_17',['DVS_MON',['../group___d_v_s___m_o_n.html',1,'']]],
  ['dvs_5fregisters_18',['DVS_Registers',['../group__dvs__registers.html',1,'']]],
  ['dvs_5fstat_19',['DVS_STAT',['../group___d_v_s___s_t_a_t.html',1,'']]],
  ['dvs_5ftap_5fsel_20',['DVS_TAP_SEL',['../group___d_v_s___t_a_p___s_e_l.html',1,'']]],
  ['dvs_5fthres_5fcmp_21',['DVS_THRES_CMP',['../group___d_v_s___t_h_r_e_s___c_m_p.html',1,'']]]
];
