var searchData=
[
  ['delay_20utility_20functions_5496',['Delay Utility Functions',['../group___m_x_c__delay.html',1,'']]],
  ['direct_20memory_20access_20_28dma_29_5497',['Direct Memory Access (DMA)',['../group__dma.html',1,'']]],
  ['dma_5fcnt_5498',['DMA_CNT',['../group___d_m_a___c_n_t.html',1,'']]],
  ['dma_5fcntrld_5499',['DMA_CNTRLD',['../group___d_m_a___c_n_t_r_l_d.html',1,'']]],
  ['dma_5fctrl_5500',['DMA_CTRL',['../group___d_m_a___c_t_r_l.html',1,'']]],
  ['dma_5fdst_5501',['DMA_DST',['../group___d_m_a___d_s_t.html',1,'']]],
  ['dma_5fdstrld_5502',['DMA_DSTRLD',['../group___d_m_a___d_s_t_r_l_d.html',1,'']]],
  ['dma_5finten_5503',['DMA_INTEN',['../group___d_m_a___i_n_t_e_n.html',1,'']]],
  ['dma_5fintfl_5504',['DMA_INTFL',['../group___d_m_a___i_n_t_f_l.html',1,'']]],
  ['dma_5fregisters_5505',['DMA_Registers',['../group__dma__registers.html',1,'']]],
  ['dma_5fsrc_5506',['DMA_SRC',['../group___d_m_a___s_r_c.html',1,'']]],
  ['dma_5fsrcrld_5507',['DMA_SRCRLD',['../group___d_m_a___s_r_c_r_l_d.html',1,'']]],
  ['dma_5fstatus_5508',['DMA_STATUS',['../group___d_m_a___s_t_a_t_u_s.html',1,'']]],
  ['dvs_5fadj_5fdwn_5509',['DVS_ADJ_DWN',['../group___d_v_s___a_d_j___d_w_n.html',1,'']]],
  ['dvs_5fadj_5fup_5510',['DVS_ADJ_UP',['../group___d_v_s___a_d_j___u_p.html',1,'']]],
  ['dvs_5fctl_5511',['DVS_CTL',['../group___d_v_s___c_t_l.html',1,'']]],
  ['dvs_5fdirect_5512',['DVS_DIRECT',['../group___d_v_s___d_i_r_e_c_t.html',1,'']]],
  ['dvs_5fmon_5513',['DVS_MON',['../group___d_v_s___m_o_n.html',1,'']]],
  ['dvs_5fregisters_5514',['DVS_Registers',['../group__dvs__registers.html',1,'']]],
  ['dvs_5fstat_5515',['DVS_STAT',['../group___d_v_s___s_t_a_t.html',1,'']]],
  ['dvs_5ftap_5fsel_5516',['DVS_TAP_SEL',['../group___d_v_s___t_a_p___s_e_l.html',1,'']]],
  ['dvs_5fthres_5fcmp_5517',['DVS_THRES_CMP',['../group___d_v_s___t_h_r_e_s___c_m_p.html',1,'']]]
];
