/******************************************************************************
 *
 * Copyright (C) 2024 Analog Devices, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/
/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum)            \
    {                                              \
        Unity.CurrentTestName = #TestFunc;         \
        Unity.CurrentTestLineNumber = TestLineNum; \
        Unity.NumberOfTests++;                     \
        if (TEST_PROTECT()) {                      \
            setUp();                               \
            TestFunc();                            \
        }                                          \
        if (TEST_PROTECT()) {                      \
            tearDown();                            \
        }                                          \
        UnityConcludeTest();                       \
    }

/*=======Automagically Detected Files To Include=====*/
#include <setjmp.h>
#include <stdio.h>
#include "unity.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_simple_add_ok(void);
extern void test_simple_add_fail(void);

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
    tearDown();
    setUp();
}

/*=======MAIN=====*/
int main(void)
{
    UnityBegin("test_functions.c");
    RUN_TEST(test_simple_add_ok, __LINE__);
    RUN_TEST(test_simple_add_fail, __LINE__);

    return (UnityEnd());
}
